const ARTICLE_POOL_UI_COPY = {
  english: {
    common: {
      close: "Close",
      cancel: "Cancel",
      create: "Create",
      update: "Update",
      delete: "Delete",
      save: "Save",
      saving: "Saving...",
      search: "Search",
      loading: "Loading",
      noAccess: "No Access",
      copied: (label) => `${label} copied.`,
      copyFailed: (label) => `Failed to copy ${String(label || "").toLowerCase()}.`,
      imageAddress: "Image address",
      yes: "Yes",
      no: "No",
      notAvailable: "-",
      words: (count) => `${count} words`,
    },
    page: {
      title: "Content Pool",
      description: "Create and manage brand content with access controlled by Content Pool privileges.",
      importCsv: "Import CSV",
      exportCsv: "Export CSV",
      exporting: "Exporting...",
      addContent: "Add Content",
      totalContent: "Total content",
      loadError: "Failed to load content pool data",
      loadingTitle: "Loading",
      loadingDescription: "Fetching content pool data...",
      tableTitle: "Content Table",
      tableDescription: "Review content ownership and manage records allowed by your privileges.",
      searchPlaceholder: "Brand, title, created by",
      date: "Date",
      createdDate: "Created Date",
      brand: "Brand",
      titleColumn: "Title",
      createdBy: "Created By",
      preview: "Preview",
      actions: "Actions",
      previewContent: "Preview content",
      update: "Update",
      delete: "Delete",
      noData: "No data available in table",
      noPrivileges: "You do not have content pool privileges.",
      updateSuccess: "Content updated successfully.",
      createSuccess: "Content created successfully.",
      saveError: "Failed to save content",
      createError: "Failed to create content",
      updateError: "Failed to update content",
      deleteError: "Failed to delete content",
      deleteConfirm: "Delete this content?",
      exportError: "Failed to export content pool CSV",
    },
    emptyState: {
      title: "No content yet",
      description: "Add content with brand, title, description, and content body.",
    },
    form: {
      createTitle: "Create Content",
      updateTitle: "Update Content",
      description: "Add the brand, title, description, content body, notes, and resource links.",
      brand: "Brand",
      selectBrand: "Select brand",
      title: "Title",
      titlePlaceholder: "Best online casino safety guide",
      descriptionLabel: "Description",
      descriptionPlaceholder: "Short description for the content",
      content: "Content",
      contentPlaceholder: "Write or paste the content here.",
      note: "Note",
      notePlaceholder: "Add note here",
      resourceLinks: "Resource Links",
      resourceLinksDescription:
        "Use the same Blogger or Blogspot logo, banner, favicon, and button links used in development content.",
      logo: "Logo",
      logoPlaceholder: "Paste logo Blogger or Blogspot link here",
      banner: "Banner",
      bannerPlaceholder: "Paste banner Blogger or Blogspot link here",
      favicon: "Favicon",
      faviconPlaceholder: "Paste favicon Blogger or Blogspot link here",
      button: "Button",
      buttonPlaceholder: "Paste button Blogger or Blogspot link here",
      resourcePreview: "Resource Preview",
      resourcePreviewDescription: "Images from the links above appear here.",
      resourcePreviewEmpty: "Add logo, banner, favicon, or button links to preview them here.",
      openResourceImage: "Open resource image",
      validation: {
        selectBrand: "Select a brand.",
        titleRequired: "Content title is required.",
        descriptionRequired: "Content description is required.",
        bodyRequired: "Content body is required.",
      },
      saveError: "Failed to save content",
      deleteConfirm: "Delete this content?",
      deleteError: "Failed to delete content",
    },
    previewModal: {
      title: "Content Preview",
      close: "Close",
      titleLabel: "Title",
      descriptionLabel: "Description",
      contentLabel: "Content",
      noteLabel: "Note",
      resourcesLabel: "Resources",
      noResources: "No resource images available.",
      copyImageAddress: "Click to copy image address",
    },
    importPage: {
      title: "Import Content Pool",
      noPermission: "You do not have permission to import content pool records.",
      backToList: "Back to Content Pool",
    },
    importForm: {
      title: "Import Content Pool",
      uploadTitle: "Upload CSV",
      uploadDescription:
        "Upload a CSV file or paste the CSV text to preview new, updated, unchanged, and invalid content pool rows before importing.",
      hideCsvView: "Hide CSV View",
      showCsvView: "Show CSV View",
      downloadTemplate: "Download Template",
      chooseFile: "Choose CSV file",
      fileHelp:
        "Use the export format: Brand, Title, Description, Content, Note, Logo, Banner, Favicon, Button.",
      csvContent: "CSV content",
      noCsvLoaded: "No CSV content loaded yet",
      loadedLines: (count) => `Loaded ${count} non-empty line${count === 1 ? "" : "s"}`,
      csvReady: "CSV content is ready for preview.",
      csvHidden: "CSV editor is hidden.",
      templatePreview: "Template preview",
      templateLines: (count) => `Sample template with ${count} non-empty line${count === 1 ? "" : "s"}`,
      templateHidden: "Template preview is hidden.",
      importPreview: "Import Preview",
      checkingRows: "Checking CSV rows...",
      uploadToPreview: "Upload CSV content to generate an import preview.",
      readyCount: (count) => `Ready: ${count}`,
      filteredCount: (count) => `Filtered: ${count}`,
      importAction: "Import Content",
      cards: {
        ready: "Ready To Apply",
        new: "New",
        update: "Update",
        unchanged: "Unchanged",
        invalid: "Invalid",
      },
      searchPreview: "Search preview",
      searchPlaceholder: "Brand, title, description, note",
      all: "All",
      ready: "Ready",
      resetPreviewFilters: "Reset preview filters",
      tableHeaders: {
        row: "Row",
        incoming: "Incoming Content",
        current: "Current Record",
        difference: "Difference",
        result: "Result",
      },
      rowLabel: (rowNumber) => `Row ${rowNumber}`,
      incoming: "Incoming",
      current: "Current",
      noExistingRecord: "No existing record",
      needsCorrection: "Needs correction",
      rowWillBeApplied: "This row will be applied.",
      rowWillNotChange: "This row will not change existing data.",
      noRowsMatch: "No rows match the current preview filters.",
      confirmTitle: "Confirm Import",
      confirmDescription:
        "Review the summary below and confirm before importing content pool rows from this CSV.",
      reviewedConfirmation:
        "I reviewed the import preview and want to import these content pool changes.",
      importing: "Importing...",
      importResult: (createdCount, updatedCount, skippedCount) =>
        `Imported ${createdCount || 0} new content item${(createdCount || 0) === 1 ? "" : "s"}, updated ${updatedCount || 0} existing item${(updatedCount || 0) === 1 ? "" : "s"}, and skipped ${skippedCount || 0} row${(skippedCount || 0) === 1 ? "" : "s"}.`,
      summary: (summary = {}) =>
        `${summary.actionableCount || 0} ready, ${summary.newCount || 0} new, ${summary.updateCount || 0} updates, ${summary.unchangedCount || 0} unchanged, ${summary.invalidCount || 0} invalid.`,
      previewError: "Failed to preview CSV import",
      readFileError: "Failed to read the CSV file.",
      csvRequired: "CSV content is required.",
      waitForPreview: "Please wait until the preview finishes.",
      noValidRows: "No valid rows are ready to import.",
      reviewRequired: "Confirm that you reviewed the import preview before importing.",
      importError: "Failed to import content pool CSV",
      actionLabels: {
        create: "Create",
        update: "Update",
        invalid: "Invalid",
        unchanged: "Unchanged",
        skip: "Skip",
      },
      fieldLabels: {
        brand: "Brand",
        description: "Description",
        note: "Note",
        content: "Content",
        preview: "Preview",
        resources: "Resources",
      },
      resourceSummary: (resources = {}) =>
        `Logo: ${resources.logoCount || 0} | Banner: ${resources.hasBanner ? "Yes" : "No"} | Favicon: ${resources.hasFavicon ? "Yes" : "No"} | Button: ${resources.buttonCount || 0}`,
      previewMessages: {
        invalid: "Row has validation errors",
        create: "New content will be imported",
        unchanged: "Existing content already matches current data",
        update: (changedLabels) => `Existing content will update: ${changedLabels}`,
        needsPrivilege: (changedLabels) =>
          `Change detected (${changedLabels}) but update requires Update Content Pool privilege`,
        skipped: (changedLabels) => `Change detected (${changedLabels}) and will be skipped`,
      },
    },
  },
  indonesian: {
    common: {
      close: "Tutup",
      cancel: "Batal",
      create: "Buat",
      update: "Perbarui",
      delete: "Hapus",
      save: "Simpan",
      saving: "Menyimpan...",
      search: "Cari",
      loading: "Memuat",
      noAccess: "Tidak Ada Akses",
      copied: (label) => `${label} berhasil disalin.`,
      copyFailed: (label) => `Gagal menyalin ${String(label || "").toLowerCase()}.`,
      imageAddress: "Alamat gambar",
      yes: "Ya",
      no: "Tidak",
      notAvailable: "-",
      words: (count) => `${count} kata`,
    },
    page: {
      title: "Kumpulan Konten",
      description: "Buat dan kelola konten brand dengan akses yang dikontrol oleh hak akses Content Pool.",
      importCsv: "Impor CSV",
      exportCsv: "Ekspor CSV",
      exporting: "Mengekspor...",
      addContent: "Tambah Konten",
      totalContent: "Total konten",
      loadError: "Gagal memuat data content pool",
      loadingTitle: "Memuat",
      loadingDescription: "Mengambil data content pool...",
      tableTitle: "Tabel Konten",
      tableDescription: "Tinjau kepemilikan konten dan kelola data yang diizinkan oleh hak akses Anda.",
      searchPlaceholder: "Brand, judul, dibuat oleh",
      date: "Tanggal",
      createdDate: "Tanggal Dibuat",
      brand: "Brand",
      titleColumn: "Judul",
      createdBy: "Dibuat Oleh",
      preview: "Pratinjau",
      actions: "Aksi",
      previewContent: "Pratinjau konten",
      update: "Perbarui",
      delete: "Hapus",
      noData: "Tidak ada data di tabel",
      noPrivileges: "Anda tidak memiliki hak akses content pool.",
      updateSuccess: "Konten berhasil diperbarui.",
      createSuccess: "Konten berhasil dibuat.",
      saveError: "Gagal menyimpan konten",
      createError: "Gagal membuat konten",
      updateError: "Gagal memperbarui konten",
      deleteError: "Gagal menghapus konten",
      deleteConfirm: "Hapus konten ini?",
      exportError: "Gagal mengekspor CSV content pool",
    },
    emptyState: {
      title: "Belum ada konten",
      description: "Tambahkan konten dengan brand, judul, deskripsi, dan isi konten.",
    },
    form: {
      createTitle: "Buat Konten",
      updateTitle: "Perbarui Konten",
      description: "Tambahkan brand, judul, deskripsi, isi konten, catatan, dan tautan resource.",
      brand: "Brand",
      selectBrand: "Pilih brand",
      title: "Judul",
      titlePlaceholder: "Panduan keamanan kasino online terbaik",
      descriptionLabel: "Deskripsi",
      descriptionPlaceholder: "Deskripsi singkat untuk konten",
      content: "Konten",
      contentPlaceholder: "Tulis atau tempel konten di sini.",
      note: "Catatan",
      notePlaceholder: "Tambahkan catatan di sini",
      resourceLinks: "Tautan Resource",
      resourceLinksDescription:
        "Gunakan tautan logo, banner, favicon, dan tombol Blogger atau Blogspot yang sama seperti pada konten development.",
      logo: "Logo",
      logoPlaceholder: "Tempel tautan logo Blogger atau Blogspot di sini",
      banner: "Banner",
      bannerPlaceholder: "Tempel tautan banner Blogger atau Blogspot di sini",
      favicon: "Favicon",
      faviconPlaceholder: "Tempel tautan favicon Blogger atau Blogspot di sini",
      button: "Tombol",
      buttonPlaceholder: "Tempel tautan tombol Blogger atau Blogspot di sini",
      resourcePreview: "Pratinjau Resource",
      resourcePreviewDescription: "Gambar dari tautan di atas akan muncul di sini.",
      resourcePreviewEmpty: "Tambahkan tautan logo, banner, favicon, atau tombol untuk melihat pratinjaunya di sini.",
      openResourceImage: "Buka gambar resource",
      validation: {
        selectBrand: "Pilih brand.",
        titleRequired: "Judul konten wajib diisi.",
        descriptionRequired: "Deskripsi konten wajib diisi.",
        bodyRequired: "Isi konten wajib diisi.",
      },
      saveError: "Gagal menyimpan konten",
      deleteConfirm: "Hapus konten ini?",
      deleteError: "Gagal menghapus konten",
    },
    previewModal: {
      title: "Pratinjau Konten",
      close: "Tutup",
      titleLabel: "Judul",
      descriptionLabel: "Deskripsi",
      contentLabel: "Konten",
      noteLabel: "Catatan",
      resourcesLabel: "Resource",
      noResources: "Tidak ada gambar resource tersedia.",
      copyImageAddress: "Klik untuk menyalin alamat gambar",
    },
    importPage: {
      title: "Impor Content Pool",
      noPermission: "Anda tidak memiliki izin untuk mengimpor data content pool.",
      backToList: "Kembali ke Content Pool",
    },
    importForm: {
      title: "Impor Content Pool",
      uploadTitle: "Unggah CSV",
      uploadDescription:
        "Unggah file CSV atau tempel teks CSV untuk melihat pratinjau baris content pool baru, diperbarui, tidak berubah, dan tidak valid sebelum impor.",
      hideCsvView: "Sembunyikan Tampilan CSV",
      showCsvView: "Tampilkan Tampilan CSV",
      downloadTemplate: "Unduh Template",
      chooseFile: "Pilih file CSV",
      fileHelp:
        "Gunakan format ekspor: Brand, Title, Description, Content, Note, Logo, Banner, Favicon, Button.",
      csvContent: "Konten CSV",
      noCsvLoaded: "Belum ada konten CSV dimuat",
      loadedLines: (count) => `${count} baris tidak kosong dimuat`,
      csvReady: "Konten CSV siap untuk pratinjau.",
      csvHidden: "Editor CSV disembunyikan.",
      templatePreview: "Pratinjau template",
      templateLines: (count) => `Contoh template dengan ${count} baris tidak kosong`,
      templateHidden: "Pratinjau template disembunyikan.",
      importPreview: "Pratinjau Impor",
      checkingRows: "Memeriksa baris CSV...",
      uploadToPreview: "Unggah konten CSV untuk membuat pratinjau impor.",
      readyCount: (count) => `Siap: ${count}`,
      filteredCount: (count) => `Tersaring: ${count}`,
      importAction: "Impor Konten",
      cards: {
        ready: "Siap Diterapkan",
        new: "Baru",
        update: "Perbarui",
        unchanged: "Tidak Berubah",
        invalid: "Tidak Valid",
      },
      searchPreview: "Cari pratinjau",
      searchPlaceholder: "Brand, judul, deskripsi, catatan",
      all: "Semua",
      ready: "Siap",
      resetPreviewFilters: "Reset filter pratinjau",
      tableHeaders: {
        row: "Baris",
        incoming: "Konten Masuk",
        current: "Data Saat Ini",
        difference: "Perbedaan",
        result: "Hasil",
      },
      rowLabel: (rowNumber) => `Baris ${rowNumber}`,
      incoming: "Masuk",
      current: "Saat Ini",
      noExistingRecord: "Tidak ada data saat ini",
      needsCorrection: "Perlu diperbaiki",
      rowWillBeApplied: "Baris ini akan diterapkan.",
      rowWillNotChange: "Baris ini tidak akan mengubah data yang ada.",
      noRowsMatch: "Tidak ada baris yang cocok dengan filter pratinjau saat ini.",
      confirmTitle: "Konfirmasi Impor",
      confirmDescription:
        "Tinjau ringkasan di bawah ini dan konfirmasi sebelum mengimpor baris content pool dari CSV ini.",
      reviewedConfirmation:
        "Saya sudah meninjau pratinjau impor dan ingin mengimpor perubahan content pool ini.",
      importing: "Mengimpor...",
      importResult: (createdCount, updatedCount, skippedCount) =>
        `Berhasil mengimpor ${createdCount || 0} item konten baru, memperbarui ${updatedCount || 0} item yang ada, dan melewati ${skippedCount || 0} baris.`,
      summary: (summary = {}) =>
        `${summary.actionableCount || 0} siap, ${summary.newCount || 0} baru, ${summary.updateCount || 0} diperbarui, ${summary.unchangedCount || 0} tidak berubah, ${summary.invalidCount || 0} tidak valid.`,
      previewError: "Gagal membuat pratinjau impor CSV",
      readFileError: "Gagal membaca file CSV.",
      csvRequired: "Konten CSV wajib diisi.",
      waitForPreview: "Harap tunggu sampai pratinjau selesai.",
      noValidRows: "Tidak ada baris valid yang siap diimpor.",
      reviewRequired: "Konfirmasi bahwa Anda sudah meninjau pratinjau impor sebelum mengimpor.",
      importError: "Gagal mengimpor CSV content pool",
      actionLabels: {
        create: "Buat",
        update: "Perbarui",
        invalid: "Tidak Valid",
        unchanged: "Tidak Berubah",
        skip: "Lewati",
      },
      fieldLabels: {
        brand: "Brand",
        description: "Deskripsi",
        note: "Catatan",
        content: "Konten",
        preview: "Pratinjau",
        resources: "Resource",
      },
      resourceSummary: (resources = {}) =>
        `Logo: ${resources.logoCount || 0} | Banner: ${resources.hasBanner ? "Ya" : "Tidak"} | Favicon: ${resources.hasFavicon ? "Ya" : "Tidak"} | Tombol: ${resources.buttonCount || 0}`,
      previewMessages: {
        invalid: "Baris memiliki error validasi",
        create: "Konten baru akan diimpor",
        unchanged: "Konten yang ada sudah sama dengan data saat ini",
        update: (changedLabels) => `Konten yang ada akan diperbarui: ${changedLabels}`,
        needsPrivilege: (changedLabels) =>
          `Perubahan terdeteksi (${changedLabels}) tetapi pembaruan memerlukan hak akses Update Content Pool`,
        skipped: (changedLabels) => `Perubahan terdeteksi (${changedLabels}) dan akan dilewati`,
      },
    },
  },
};

export function normalizeArticlePoolLanguage(value) {
  return value === "indonesian" ? "indonesian" : "english";
}

export function getArticlePoolUiCopy(language) {
  return ARTICLE_POOL_UI_COPY[normalizeArticlePoolLanguage(language)];
}

export function getArticlePoolLocale(language) {
  return normalizeArticlePoolLanguage(language) === "indonesian" ? "id-ID" : "en-US";
}
