const SCREENSHOT_TAKER_UI_COPY = {
  english: {
    common: {
      close: "Close",
      cancel: "Cancel",
      refresh: "Refresh",
      refreshing: "Refreshing...",
      saving: "Saving...",
      search: "Search",
      status: "Status",
      reset: "Reset",
      noBrand: "No Brand",
      notCaptured: "Not captured",
      success: "Success",
      failed: "Failed",
      running: "Running",
      stopped: "Stopped",
      idle: "Idle",
      loading: "Loading...",
    },
    helpers: {
      byteFallback: "-",
      storageByteFallback: "0 B",
      notScheduled: "Not scheduled",
      runningNow: "Running now",
      calculating: "Calculating...",
      starting: "Starting...",
      scanQueued: "Scan queued",
      retryingErrorSites: "Retrying error sites",
      stopping: "Stopping",
      queued: "queued",
      preparingRetries: "Preparing retries",
      retries: (retriedCount, retryTotal) => `${retriedCount}/${retryTotal} retries`,
      scanningSite: (domain) => `Scanning ${domain}`,
      scanningSites: (count) => `Scanning ${count} sites`,
      retryingSite: (domain) => `Retrying ${domain}`,
      retryingSites: (count) => `Retrying ${count} sites`,
      previewUnavailable: "Preview unavailable",
      loadingPreview: "Loading preview...",
      previewPending: "Preview pending",
      previewFailedDetail: "Refresh to try again.",
      previewPendingDetail: "The image will appear shortly.",
      noScreenshotYet: "No screenshot yet",
      noScreenshotDetail: "Run Capture Now to create the first preview.",
      fileFallback: "screenshot",
    },
    page: {
      badge: "Website Preview",
      title: "Screenshot Taker",
      description: "Preview assigned Nawala websites by visiting them from the separate screenshot service.",
      autoScheduleOn: "Auto Schedule: On",
      autoSchedule: "Auto Schedule",
      loadErrorFallback: "Failed to load Screenshot Taker",
      loadStorageError: "Failed to load screenshot image storage",
      refreshStatusError: "Failed to refresh screenshot scan status",
      captureQueued: "Capture queued. It will run without interrupting the current scan.",
      captureError: "Failed to capture screenshot",
      removeConfirm: (domain) => `Remove ${domain} from Screenshot Taker?`,
      removeSuccess: "Website removed from Screenshot Taker.",
      removeError: "Failed to remove website",
      clearImagesSuccess: (removedFileCount, removedBytes, failedFileCount) =>
        `Cleared ${removedFileCount || 0} screenshot files (${removedBytes}).${
          failedFileCount ? ` ${failedFileCount} files could not be removed.` : ""
        }`,
      clearImagesError: "Failed to clear screenshot images",
      scheduleUpdateError: "Failed to update screenshot schedule",
      scheduleStarted: "Schedule started. First scan is queued now.",
      scheduleStopped: "Schedule stopped.",
      scheduleSaved: "Schedule settings saved.",
      noAssignedUrls: "No assigned site URLs are available to open.",
      popupBlocked:
        "Some tabs were blocked by the browser. Please allow pop-ups for this site and try again.",
      openedSites: (count) => `Opened ${count} assigned sites in new tabs.`,
      live: {
        autoSchedule: "Auto schedule",
        running: "Running",
        stopped: "Stopped",
        scanStatus: "Scan status",
        progress: "Progress",
        nextScanIn: "Next scan in",
        nextAt: (value) => `Next at: ${value}`,
        stopSchedule: "Stop Schedule",
      },
      storage: {
        badge: "Admin Storage",
        title: "Screenshot Storage",
        description: "Cleanup keeps the current and previous scheduled scans when storage reaches 10 GB.",
        totalUnavailable: "Storage total unavailable",
        refreshToLoadTotals: "Refresh storage to load totals",
        noCleanupYet: "No cleanup yet",
        percentUsed: (value) => `${value}% used`,
        usageAria: "Screenshot storage usage",
        remaining: (value) => `${value} free`,
        fileCount: (count) => `${count} files`,
        protectedBatches: (count) => `${count} scan batches protected`,
        lastCleanup: (value) => `Last cleanup: ${value}`,
        removedFiles: (count, bytes) => `Removed ${count} files (${bytes})`,
        refresh: "Refresh Storage",
        checking: "Checking...",
      },
      filters: {
        badge: "Filters",
        title: "Screenshot Outputs",
        summary: (shownCount, totalCount) => `Showing ${shownCount} of ${totalCount} assigned sites.`,
        searchPlaceholder: "Search brand, domain, URL...",
        scanned: (count) => `${count} scanned`,
        success: (count) => `${count} success`,
        failed: (count) => `${count} failed`,
        clearImages: "Clear Images",
      },
      table: {
        title: "Assigned Website Previews",
        description: "Select websites from the Money Site Checker table using the Shot button.",
        openAllSites: "Open All Sites",
        assigned: (count) => `${count} assigned`,
        loading: "Loading assigned websites...",
        emptyFiltered: "No screenshot outputs match the selected filters.",
        empty: "No websites assigned yet. Open Money Site Checker and click Assign on a site to add it here.",
        viewOriginal: "View Original",
        viewOutput: "View Output",
        captureNow: "Capture Now",
        queuing: "Queuing...",
        scanning: "Scanning...",
        queued: "Queued",
        remove: "Remove",
        openTitle: (domain) => `Open ${domain}`,
        openAria: (domain) => `Open ${domain} in a new tab`,
        previewAlt: (domain) => `${domain} screenshot`,
        retryingOverlay: "Retrying...",
        scanningOverlay: "Scanning...",
        queuedNext: "Queued next",
        retryAfterError: "Retry after error",
        manualCapture: "Manual capture",
        scheduledScan: "Scheduled scan",
        retryingThisSite: "Retrying this site",
        scanningThisSite: "Scanning this site",
        autoRetry: "Auto retry",
        autoSchedule: "Auto schedule",
      },
    },
    scanFilterOptions: {
      all: "All",
      success: "Success",
      failed: "Failed",
    },
    scheduleModal: {
      telegramEnabled: "Telegram image alerts enabled",
      telegramNeedsToken: "Add bot token to enable Telegram",
      telegramDisabled: "Telegram image alerts off",
      scheduled: "Scheduled",
      stopped: "Stopped",
      title: "Auto Capture Schedule",
      description: "Capture assigned sites, wait the delay, then run again.",
      delayMinutes: "Delay Minutes",
      parallelCaptures: "Parallel Captures",
      parallelHelp: "Use up to 100. Each site opens in its own isolated browser context.",
      sendToTelegram: "Send scheduled screenshots to Telegram",
      sendToTelegramHelp: "Only auto-schedule captures send images. Manual Capture Now stays silent.",
      chatId: "Group / Chat ID",
      botToken: "Bot Token",
      savedTokenPlaceholder: "Saved. Leave blank to keep current token",
      tokenPlaceholder: "123456:ABC...",
      sentFailed: (sentCount, failedCount) => `Sent ${sentCount || 0}, failed ${failedCount || 0}`,
      lastTelegramIssue: (message) => `Last Telegram issue: ${message}`,
      status: "Status",
      progress: "Progress",
      nextScan: "Next scan",
      saveSettings: "Save Settings",
      stopSchedule: "Stop Schedule",
      startSchedule: "Start Schedule",
      lastIssue: (message) => `Last issue: ${message}`,
    },
    outputModal: {
      openSite: "Open Site",
      openOriginal: "Open Original",
      downloadOriginal: "Download Original",
      loadingTitle: "Loading original image...",
      noImageTitle: "No output image available",
      loadingDescription: "The original capture will appear shortly.",
      noImageDescription:
        "Run Capture Now and the latest screenshot will appear here once it finishes.",
      captured: "Captured",
      originalSize: "Original size",
      finalUrl: "Final URL",
      imageAlt: (domain) => `${domain} latest capture`,
    },
    clearModal: {
      badge: "Admin only",
      title: "Clear Screenshot Images",
      description: "This removes all saved screenshot files and capture records from the screenshot service.",
      adminPassword: "Admin Password",
      passwordPlaceholder: "Type your password",
      clearing: "Clearing...",
      confirm: "Clear All Images",
    },
  },
  indonesian: {
    common: {
      close: "Tutup",
      cancel: "Batal",
      refresh: "Muat ulang",
      refreshing: "Memuat...",
      saving: "Menyimpan...",
      search: "Cari",
      status: "Status",
      reset: "Reset",
      noBrand: "Tanpa brand",
      notCaptured: "Belum diambil",
      success: "Berhasil",
      failed: "Gagal",
      running: "Berjalan",
      stopped: "Berhenti",
      idle: "Idle",
      loading: "Memuat...",
    },
    helpers: {
      byteFallback: "-",
      storageByteFallback: "0 B",
      notScheduled: "Belum dijadwalkan",
      runningNow: "Sedang berjalan",
      calculating: "Menghitung...",
      starting: "Memulai...",
      scanQueued: "Antrean scan",
      retryingErrorSites: "Mencoba ulang situs error",
      stopping: "Menghentikan",
      queued: "dalam antrean",
      preparingRetries: "Menyiapkan percobaan ulang",
      retries: (retriedCount, retryTotal) => `${retriedCount}/${retryTotal} percobaan ulang`,
      scanningSite: (domain) => `Memindai ${domain}`,
      scanningSites: (count) => `Memindai ${count} situs`,
      retryingSite: (domain) => `Mencoba ulang ${domain}`,
      retryingSites: (count) => `Mencoba ulang ${count} situs`,
      previewUnavailable: "Pratinjau tidak tersedia",
      loadingPreview: "Memuat pratinjau...",
      previewPending: "Pratinjau menunggu",
      previewFailedDetail: "Muat ulang untuk mencoba lagi.",
      previewPendingDetail: "Gambar akan segera muncul.",
      noScreenshotYet: "Belum ada screenshot",
      noScreenshotDetail: "Jalankan Capture Now untuk membuat pratinjau pertama.",
      fileFallback: "screenshot",
    },
    page: {
      badge: "Pratinjau Website",
      title: "Pengambil Screenshot",
      description: "Lihat pratinjau website Nawala yang ditugaskan melalui layanan screenshot terpisah.",
      autoScheduleOn: "Jadwal Otomatis: Aktif",
      autoSchedule: "Jadwal Otomatis",
      loadErrorFallback: "Gagal memuat Pengambil Screenshot",
      loadStorageError: "Gagal memuat penyimpanan gambar screenshot",
      refreshStatusError: "Gagal memuat ulang status scan screenshot",
      captureQueued: "Capture masuk antrean. Proses akan berjalan tanpa mengganggu scan saat ini.",
      captureError: "Gagal mengambil screenshot",
      removeConfirm: (domain) => `Hapus ${domain} dari Screenshot Taker?`,
      removeSuccess: "Website berhasil dihapus dari Screenshot Taker.",
      removeError: "Gagal menghapus website",
      clearImagesSuccess: (removedFileCount, removedBytes, failedFileCount) =>
        `Berhasil menghapus ${removedFileCount || 0} file screenshot (${removedBytes}).${
          failedFileCount ? ` ${failedFileCount} file tidak dapat dihapus.` : ""
        }`,
      clearImagesError: "Gagal menghapus gambar screenshot",
      scheduleUpdateError: "Gagal memperbarui jadwal screenshot",
      scheduleStarted: "Jadwal dimulai. Scan pertama masuk antrean sekarang.",
      scheduleStopped: "Jadwal dihentikan.",
      scheduleSaved: "Pengaturan jadwal berhasil disimpan.",
      noAssignedUrls: "Tidak ada URL situs yang ditugaskan untuk dibuka.",
      popupBlocked: "Beberapa tab diblokir browser. Izinkan pop-up untuk situs ini lalu coba lagi.",
      openedSites: (count) => `Membuka ${count} situs yang ditugaskan di tab baru.`,
      live: {
        autoSchedule: "Jadwal otomatis",
        running: "Berjalan",
        stopped: "Berhenti",
        scanStatus: "Status scan",
        progress: "Progres",
        nextScanIn: "Scan berikutnya dalam",
        nextAt: (value) => `Berikutnya: ${value}`,
        stopSchedule: "Hentikan Jadwal",
      },
      storage: {
        badge: "Penyimpanan Admin",
        title: "Penyimpanan Screenshot",
        description: "Pembersihan menyimpan hasil scan terjadwal saat ini dan sebelumnya ketika penyimpanan mencapai 10 GB.",
        totalUnavailable: "Total penyimpanan tidak tersedia",
        refreshToLoadTotals: "Muat ulang penyimpanan untuk memuat total",
        noCleanupYet: "Belum ada pembersihan",
        percentUsed: (value) => `${value}% terpakai`,
        usageAria: "Penggunaan penyimpanan screenshot",
        remaining: (value) => `${value} kosong`,
        fileCount: (count) => `${count} file`,
        protectedBatches: (count) => `${count} batch scan dilindungi`,
        lastCleanup: (value) => `Pembersihan terakhir: ${value}`,
        removedFiles: (count, bytes) => `Menghapus ${count} file (${bytes})`,
        refresh: "Muat Ulang Penyimpanan",
        checking: "Memeriksa...",
      },
      filters: {
        badge: "Filter",
        title: "Hasil Screenshot",
        summary: (shownCount, totalCount) => `Menampilkan ${shownCount} dari ${totalCount} situs yang ditugaskan.`,
        searchPlaceholder: "Cari brand, domain, URL...",
        scanned: (count) => `${count} dipindai`,
        success: (count) => `${count} berhasil`,
        failed: (count) => `${count} gagal`,
        clearImages: "Hapus Gambar",
      },
      table: {
        title: "Pratinjau Website yang Ditugaskan",
        description: "Pilih website dari tabel Money Site Checker menggunakan tombol Shot.",
        openAllSites: "Buka Semua Situs",
        assigned: (count) => `${count} ditugaskan`,
        loading: "Memuat website yang ditugaskan...",
        emptyFiltered: "Tidak ada hasil screenshot yang cocok dengan filter yang dipilih.",
        empty: "Belum ada website yang ditugaskan. Buka Money Site Checker dan klik Assign pada situs untuk menambahkannya di sini.",
        viewOriginal: "Lihat Asli",
        viewOutput: "Lihat Hasil",
        captureNow: "Capture Sekarang",
        queuing: "Masuk antrean...",
        scanning: "Memindai...",
        queued: "Antrean",
        remove: "Hapus",
        openTitle: (domain) => `Buka ${domain}`,
        openAria: (domain) => `Buka ${domain} di tab baru`,
        previewAlt: (domain) => `Screenshot ${domain}`,
        retryingOverlay: "Mencoba ulang...",
        scanningOverlay: "Memindai...",
        queuedNext: "Antrean berikutnya",
        retryAfterError: "Coba ulang setelah error",
        manualCapture: "Capture manual",
        scheduledScan: "Scan terjadwal",
        retryingThisSite: "Mencoba ulang situs ini",
        scanningThisSite: "Memindai situs ini",
        autoRetry: "Coba ulang otomatis",
        autoSchedule: "Jadwal otomatis",
      },
    },
    scanFilterOptions: {
      all: "Semua",
      success: "Berhasil",
      failed: "Gagal",
    },
    scheduleModal: {
      telegramEnabled: "Alert gambar Telegram aktif",
      telegramNeedsToken: "Tambahkan token bot untuk mengaktifkan Telegram",
      telegramDisabled: "Alert gambar Telegram nonaktif",
      scheduled: "Terjadwal",
      stopped: "Berhenti",
      title: "Jadwal Capture Otomatis",
      description: "Ambil gambar situs yang ditugaskan, tunggu jeda, lalu jalankan lagi.",
      delayMinutes: "Jeda Menit",
      parallelCaptures: "Capture Paralel",
      parallelHelp: "Gunakan hingga 100. Setiap situs dibuka di konteks browser terisolasi masing-masing.",
      sendToTelegram: "Kirim screenshot terjadwal ke Telegram",
      sendToTelegramHelp: "Hanya capture jadwal otomatis yang mengirim gambar. Capture Now manual tetap diam.",
      chatId: "ID Grup / Chat",
      botToken: "Token Bot",
      savedTokenPlaceholder: "Tersimpan. Biarkan kosong untuk memakai token saat ini",
      tokenPlaceholder: "123456:ABC...",
      sentFailed: (sentCount, failedCount) => `Terkirim ${sentCount || 0}, gagal ${failedCount || 0}`,
      lastTelegramIssue: (message) => `Masalah Telegram terakhir: ${message}`,
      status: "Status",
      progress: "Progres",
      nextScan: "Scan berikutnya",
      saveSettings: "Simpan Pengaturan",
      stopSchedule: "Hentikan Jadwal",
      startSchedule: "Mulai Jadwal",
      lastIssue: (message) => `Masalah terakhir: ${message}`,
    },
    outputModal: {
      openSite: "Buka Situs",
      openOriginal: "Buka Asli",
      downloadOriginal: "Unduh Asli",
      loadingTitle: "Memuat gambar asli...",
      noImageTitle: "Belum ada gambar hasil",
      loadingDescription: "Hasil tangkapan asli akan segera muncul.",
      noImageDescription:
        "Jalankan Capture Now dan screenshot terbaru akan tampil di sini setelah selesai.",
      captured: "Diambil",
      originalSize: "Ukuran asli",
      finalUrl: "URL akhir",
      imageAlt: (domain) => `Hasil tangkapan terbaru ${domain}`,
    },
    clearModal: {
      badge: "Khusus admin",
      title: "Hapus Gambar Screenshot",
      description: "Ini akan menghapus semua file screenshot dan data hasil tangkapan yang tersimpan dari layanan screenshot.",
      adminPassword: "Kata Sandi Admin",
      passwordPlaceholder: "Ketik kata sandi Anda",
      clearing: "Menghapus...",
      confirm: "Hapus Semua Gambar",
    },
  },
};

export function normalizeScreenshotTakerLanguage(value) {
  return value === "indonesian" ? "indonesian" : "english";
}

export function getScreenshotTakerUiCopy(language) {
  return SCREENSHOT_TAKER_UI_COPY[normalizeScreenshotTakerLanguage(language)];
}

export function getScreenshotTakerLocale(language) {
  return normalizeScreenshotTakerLanguage(language) === "indonesian" ? "id-ID" : "en-US";
}
