import { DATABASE_BACKUPS_UI_COPY } from "./databaseBackupsUiCopy";

export const MANAGEMENT_UI_COPY = {
  english: {
    common: {
      cancel: "Cancel",
      close: "Close",
      delete: "Delete",
      deleting: "Deleting...",
      loading: "Loading",
      next: "Next",
      noDescription: "No description",
      open: "Open",
      previous: "Previous",
      protected: "Protected",
      reset: "Reset",
      saving: "Saving...",
      search: "Search",
      standard: "Standard",
      working: "Working...",
    },
    privilegeCatalog: {
      moduleLabels: {
        admin: "Admin",
        "article-pool": "Content Pool",
        "audit-logs": "Activity Logs",
        auth: "Auth",
        brands: "Brands",
        content: "Content",
        "cuttly-link-checker": "Cutt.ly Link Checker",
        "database-backups": "Database Backups",
        development: "Development",
        domains: "Domains",
        "expired-domains": "Expired Domains",
        general: "General",
        groups: "Groups",
        "lp-servers": "LP Servers",
        "money-sites": "Money Sites",
        "password-resets": "Password Resets",
        privileges: "Privileges",
        "rank-checker": "Rank Checker",
        reporting: "Reporting",
        "screenshot-taker": "Screenshot Taker",
        "short-link-checker": "Short Link Checker",
        "site-analytics": "Website Analytics",
        "wayback-checker": "Wayback Checker",
        "website-snapshots": "Website Snapshots",
        users: "Users",
      },
      actionLabels: {
        admin: "Admin",
        approve: "Approve",
        assign: "Assign",
        configure: "Configure",
        create: "Create",
        delete: "Delete",
        do: "Do",
        ddos: "DDoS",
        export: "Export",
        generate: "Generate",
        import: "Import",
        manage: "Manage",
        other: "Other",
        progress: "Progress",
        read: "Read",
        send: "Send",
        stats: "Stats",
        track: "Track",
        update: "Update",
      },
      specialActionLabels: {
        adminReview: "Admin Review",
      },
      moreInfoAria: (name) => `More information about ${name}`,
      privilegeCount: (count) => `${count} privilege${count === 1 ? "" : "s"}`,
    },
    users: {
      page: {
        title: "User Management",
        description:
          "Create users, keep every account attached to a group, and manage access indirectly through group privileges.",
        createUser: "Create User",
        totalUsers: "Total users",
        loadingDescription: "Fetching users and groups...",
        loadErrorFallback: "Failed to load users",
        loadGroupsErrorFallback: "Failed to load groups",
        saveError: "Failed to save user",
        changeGroupError: "Failed to change user group",
        statusError: "Failed to update user status",
        deleteError: "Failed to delete user",
      },
      form: {
        titleCreate: "Create User",
        titleEdit: "Edit User",
        description:
          "Users must belong to a group. Group privileges define what they can access in the dashboard.",
        fullName: "Full name",
        email: "Email",
        password: "Password",
        group: "Group",
        selectGroup: "Select a group",
        saveCreate: "Create User",
        saveEdit: "Save User",
        saving: "Saving...",
        cancel: "Cancel",
      },
      changeGroupForm: {
        title: "Change Group",
        description: (name) => `Move ${name || "this user"} to a different group.`,
        group: "Group",
        selectGroup: "Select a group",
        submit: "Change Group",
        saving: "Saving...",
        cancel: "Cancel",
      },
      table: {
        title: "Users",
        description: "Update profile details, move users between groups, and toggle account status.",
        search: "Search",
        searchPlaceholder: "Search user, email, group, or status",
        headers: {
          user: "User",
          group: "Group",
          status: "Status",
          actions: "Actions",
        },
        badges: {
          noGroup: "No group",
          protectedGroup: "Protected Group",
          standardGroup: "Standard Group",
        },
        statusLabels: {
          active: "Active",
          inactive: "Inactive",
        },
        actions: {
          edit: "Edit",
          changeGroup: "Change Group",
          deactivate: "Deactivate",
          activate: "Activate",
          delete: "Delete",
        },
        empty: "No users found.",
        noMatches: "No matching users found.",
      },
      dialogs: {
        activateTitle: "Activate User",
        activateMessage: (name) => `Activate ${name}? This will restore account access.`,
        activateConfirm: "Activate",
        deactivateTitle: "Deactivate User",
        deactivateMessage: (name) =>
          `Deactivate ${name}? They will no longer be able to access the system.`,
        deactivateConfirm: "Deactivate",
        deleteTitle: "Delete User",
        deleteMessage: (name) => `Delete ${name}? This action cannot be undone.`,
        deleteConfirm: "Delete",
      },
      errors: {
        selfDeactivate: "You cannot deactivate your own account.",
        editPermission: "You do not have permission to edit users.",
        deletePermission: "You do not have permission to delete users.",
        protectedEdit: "Users in the System administrators group cannot be edited.",
        protectedMove: "Users in the System administrators group cannot be moved.",
        protectedStatus: "Users in the System administrators group cannot have their status changed.",
        protectedDelete: "Users in the System administrators group cannot be deleted.",
      },
    },
    groups: {
      page: {
        title: "Group Management",
        description:
          "Organize access by assigning privileges to groups. Users inherit permissions from the group they belong to.",
        createGroup: "Create Group",
        totalGroups: "Total groups",
        loadingDescription: "Fetching groups...",
        loadErrorFallback: "Failed to load groups",
        loadPrivilegesErrorFallback: "Failed to load privileges",
        saveError: "Failed to save group",
        deleteError: "Failed to delete group",
      },
      form: {
        titleCreate: "Create Group",
        titleEdit: "Edit Group",
        description:
          "Privileges are assigned to groups only. Every user inherits access from their assigned group.",
        name: "Name",
        descriptionLabel: "Description",
        privileges: "Privileges",
        nameRequired: "Enter a group name before saving.",
        nameExists: "Group name already exists.",
        privilegeRequired: "Select at least one privilege before saving the group.",
        adminHint:
          "Admin access includes every privilege. Other privilege selections are locked while Admin is enabled.",
        rankCheckerAdminHint:
          "Rank Checker Admin Privs includes every Rank Checker privilege. Other Rank Checker selections are locked while it is enabled.",
        reportingDependencyHint:
          "Advanced Reporting privileges require Check Progress of Reporting, so that base privilege is locked while those options are enabled.",
        unavailablePrivileges: "Privilege definitions are not available for this account.",
        saveCreate: "Create Group",
        saveEdit: "Save Group",
        saving: "Saving...",
        cancel: "Cancel",
        includedWithRankCheckerAdmin: (name) => `${name} (included with Rank Checker Admin Privs)`,
        rankCheckerDependency: (name) =>
          `${name} (required when any Rank Checker feature is enabled)`,
        reportingDependency: (name) =>
          `${name} (required when advanced Reporting privileges are enabled)`,
      },
      table: {
        title: "Groups",
        description:
          "Manage group descriptions and open each group to review assigned privileges in a focused popup.",
        search: "Search",
        searchPlaceholder: "Search group, description, or type",
        noDescription: "No description",
        headers: {
          group: "Group",
          protection: "Protection",
          actions: "Actions",
        },
        actions: {
          privileges: "Privileges",
          edit: "Edit",
          delete: "Delete",
        },
        badges: {
          protected: "Protected",
          standard: "Standard",
        },
        empty: "No groups found.",
        noMatches: "No matching groups found.",
      },
      deleteForm: {
        title: "Delete Group",
        description: (name) =>
          `Choose the group that should receive users currently assigned to ${name} before deletion.`,
        transferTo: "Transfer users to",
        selectGroup: "Select a group",
        submit: "Transfer and Delete",
        deleting: "Deleting...",
        cancel: "Cancel",
        noAvailableGroups:
          "You need at least one other group available before this group can be deleted.",
        close: "Close",
      },
      privilegesModal: {
        titleFallback: "Group Details",
        descriptionFallback: "Review the privileges assigned to this group.",
        protected: "Protected",
        standard: "Standard",
        empty: "No privileges are assigned to this group.",
        close: "Close",
      },
      errors: {
        editPermission: "You do not have permission to edit groups.",
        deletePermission: "You do not have permission to delete groups.",
        protectedEdit: "System administrators group cannot be edited.",
      },
    },
    privileges: {
      page: {
        title: "Privilege Management",
        description:
          "Review the current hard-coded permission catalog by module, purpose, and access scope.",
        totalPrivileges: "Total privileges",
        loadingDescription: "Fetching privileges...",
        loadErrorFallback: "Failed to load privileges",
      },
      table: {
        title: "Permission Matrix",
        description: "Browse the current hard-coded privilege catalog by module and access type.",
        search: "Search",
        searchPlaceholder: "Search module, action, key, or description",
        empty: "No matching privileges found.",
      },
    },
    activityLogs: {
      page: {
        title: "Activity Logs",
        description: "Track logins, page visits, and important system actions in one readable timeline.",
        totalMatchingRecords: "Total matching records",
        loadErrorFallback: "Failed to load activity logs",
      },
      filters: {
        title: "Filters",
        description:
          "Search by user, route, or summary and narrow the view by module, category, and date.",
        search: "Search",
        searchPlaceholder: "User, summary, route, or target",
        module: "Module",
        allModules: "All modules",
        category: "Category",
        allCategories: "All categories",
        date: "Date",
        reset: "Reset",
      },
      summary: {
        loadedRecords: "Loaded Records",
        uniqueActors: "Unique Actors",
        averageRequestTime: "Average Request Time",
      },
      table: {
        title: "Recent Activity",
        description:
          "Use the long table view to scan records quickly, then open a popup for full details.",
        loading: "Loading activity logs...",
        empty: "No activity records found for the selected filters.",
        headers: {
          time: "Time",
          user: "User",
          module: "Module",
          action: "Action",
          summary: "Summary",
          target: "Target",
          duration: "Duration",
          details: "Details",
        },
        open: "Open",
        openAria: (summary) => `Open details for ${summary}`,
      },
      pagination: {
        pageLabel: (page, totalPages) => `Page ${page} of ${totalPages}`,
        previous: "Previous",
        next: "Next",
      },
      detail: {
        title: "Log Details",
        description: "See who did what, where it happened, and how long it took.",
        close: "Close",
        unknownUser: "Unknown user",
        user: "User",
        email: "Email",
        target: "Target",
        targetType: "Target Type",
        http: "HTTP",
        requestTime: "Request Time",
        route: "Route",
        ipAddress: "IP Address",
        details: "Details",
        detailsEmpty: "No additional description was stored for this event.",
        extraContext: "Extra Context",
        noExtraContext: "No extra context",
        userAgent: "User Agent",
      },
      values: {
        modules: {
          auth: "Auth",
          "article-pool": "Content Pool",
          brands: "Brands",
          content: "Content",
          "database-backups": "Database Backups",
          dashboard: "Dashboard",
          development: "Development",
          groups: "Groups",
          "lp-servers": "LP Servers",
          "money-sites": "Money Sites",
          navigation: "Navigation",
          "password-resets": "Password Resets",
          reporting: "Reporting",
          "site-analytics": "Website Analytics",
          "website-snapshots": "Website Snapshots",
          users: "Users",
        },
        categories: {
          access: "Access",
          ai: "AI",
          auth: "Auth",
          data: "Data",
          email: "Email",
          navigation: "Navigation",
          profile: "Profile",
          settings: "Settings",
          "smtp-profiles": "SMTP Profiles",
        },
        actions: {
          "auth.login": "Login",
          "database-backup.delete": "Delete Database Backup",
          "database-backup.download": "Download Database Backup",
          "database-backup.export": "Create Database Backup",
          "database-backup.restore.execute": "Restore Database Backup",
          "database-backup.restore.prepare": "Prepare Database Restore",
          "database-backup.restore.request-code": "Request Restore Verification Code",
          "database-backup.telegram.send": "Send Database Backup To Telegram",
          "database-backup.telegram.test": "Test Database Restore Bot",
          "database-backup.telegram.update": "Update Database Restore Bot",
          "group.create": "Create Group",
          "group.delete": "Delete Group",
          "group.update": "Update Group",
          "page.visit": "Page Visit",
          "site-analytics.url.block": "Block Tracked URL",
          "site-analytics.url.unblock": "Unblock Tracked URL",
          "site-analytics.url.clear-stats": "Clear Tracked URL Stats",
          "site-analytics.url.delete": "Delete Tracked URL",
          "website-snapshot.search": "Search Website Snapshots",
          "website-snapshot.download": "Download Website Snapshot",
          "website-snapshot.history.delete": "Delete Website Snapshot History",
          "user.change-group": "Change User Group",
          "user.change-status": "Change User Status",
          "user.create": "Create User",
          "user.delete": "Delete User",
          "user.update": "Update User",
        },
        tokens: {
          analytics: "Analytics",
          backup: "Backup",
          block: "Block",
          code: "Code",
          clear: "Clear",
          database: "Database",
          download: "Download",
          execute: "Execute",
          request: "Request",
          restore: "Restore",
          stats: "Stats",
          snapshot: "Snapshot",
          snapshots: "Snapshots",
          telegram: "Telegram",
          tracked: "Tracked",
          unblock: "Unblock",
          url: "URL",
          verification: "Verification",
          website: "Website",
        },
      },
    },
    ...DATABASE_BACKUPS_UI_COPY.english,
    siteAnalytics: {
      page: {
        title: "Website Analytics",
        description:
          "Track visits and click activity from plain HTML and AMP pages by adding a lightweight collector snippet to the page header.",
        refresh: "Refresh",
        refreshing: "Refreshing...",
        loadingDescription: "Loading tracked URLs, visit counts, click details, and device summaries...",
        loadErrorFallback: "Failed to load website analytics",
        totalUrls: "Tracked URLs",
        totalPageviews: "Page Views",
        totalUniqueDevices: "Unique Devices",
        totalBotEvents: "Bot / Unknown Requests",
        topVisitsTitle: "Top Visits",
        topVisitsDescription: "See which tracked pages are receiving the most views right now.",
        topVisitsEmpty: "No visit data is available yet.",
      },
      install: {
        title: "Install Tracker",
        description:
          "Use the HTML snippet on normal pages. Use the AMP block on AMP pages. Both options send page-level traffic back to this system.",
        htmlTitle: "HTML / Plain Sites",
        ampTitle: "AMP Pages",
        htmlDescription:
          "Add this once in the page head or before the closing body tag. It loads asynchronously, detects the page URL, and tracks page views plus clicks.",
        ampDescription:
          "Add this AMP block to track visible page views and link-click events on AMP pages without custom JavaScript.",
        optionalOverride: "Optional override:",
        optionalOverrideValue:
          "Add data-main-url=\"https://example.com/page\" if you want to force a custom main URL instead of the current page path.",
        openHtml: "Open HTML Snippet",
        openAmp: "Open AMP Snippet",
        copyHtml: "Copy HTML Snippet",
        copyAmp: "Copy AMP Snippet",
        copiedHtml: "HTML tracking snippet copied.",
        copiedAmp: "AMP tracking snippet copied.",
        copyFailed: "Failed to copy tracking snippet",
    
      },
      filters: {
        search: "Search",
        searchPlaceholder: "Search URL, host, or page title",
        traffic: "Traffic",
        allTraffic: "All traffic",
        human: "Human",
        bot: "Bot",  
        unknown: "Unknown",
      },
      table: {
        title: "Tracked URLs",
        description:
          "Each row represents a page URL discovered by the tracker. Open a row to inspect devices, clicks, referrers, and recent requests.",
        empty: "No website analytics data has been collected yet.",
        headers: {
          url: "Main URL",
          title: "Title",
          pageviews: "Views",
          uniqueDevices: "Devices",
          clicks: "Clicks",
          bots: "Bot / Unknown",
          lastSeen: "Last Seen",
          status: "Status",
          actions: "Actions",
        },
        open: "Open Analytics",
        blocked: "Blocked",
        active: "Active",
        clearStats: "Clear Stats",
        deleteUrl: "Delete URL",
        block: "Block",
        unblock: "Unblock",
      },
      detail: {
        title: "URL Details",
        description:
          "Review traffic, detected bots, referrers, top clicked links, and recent events for this tracked URL.",
        pageTitle: "Analytics Detail",
        pageDescription:
          "Use the tracked URL dropdown to switch between pages and review graphs, device journeys, and recent activity.",
        close: "Close",
        backToList: "Back To URLs",
        selectUrl: "Tracked URL",
        openUrl: "Open URL",
        refresh: "Refresh Detail",
        loadingDescription: "Loading detailed analytics for this tracked URL...",
        loadErrorFallback: "Failed to load tracked URL details",
        fullView: "Full Analytics View",
        firstSeen: "First Seen",
        lastSeen: "Last Seen",
        statusBlocked: "Blocked From Tracking",
        statusActive: "Tracking Active",
        actions: {
          clearStats: "Clear Stats",
          clearing: "Clearing...",
          deleteUrl: "Delete URL",
          deleting: "Deleting...",
          block: "Block URL",
          blocking: "Blocking...",
          unblock: "Unblock URL",
          unblocking: "Unblocking...",
        },
        confirmations: {
          clearStats:
            "Clear all saved analytics stats for this tracked URL? New visits can still be collected afterward.",
          deleteUrl:
            "Delete this tracked URL from analytics now? This removes saved stats and any block rule for it.",
          blockUrl:
            "Block this tracked URL from future analytics collection? Existing stats will stay until you clear or delete them.",
          unblockUrl:
            "Allow this tracked URL to collect analytics again?",
        },
        actionSuccess: {
          clearStats: "Tracked URL stats cleared.",
          deleteUrl: "Tracked URL deleted from analytics.",
          blockUrl: "Tracked URL blocked from future tracking.",
          unblockUrl: "Tracked URL tracking restored.",
        },
        summary: {
          pageviews: "Page Views",
          uniqueViews: "Unique Views",
          clicks: "Clicks",
          uniqueDevices: "Unique Devices",
        },
        topVisitsTitle: "Top Visits On This Site",
        topVisitsDescription:
          "These are the most visited tracked pages on the same site as the selected URL.",
        topVisitsEmpty: "No top-visit data is available for this site yet.",
        trafficMixTitle: "Traffic Mix",
        sourceMixTitle: "Source Mix",
        engagementTitle: "Engagement Comparison",
        ratioTitle: "Key Ratios",
        ratios: {
          clickRate: "Click Rate",
          returnRate: "Returning Views",
          cleanTraffic: "Human Traffic",
        },
        sourcesTitle: "Collection Sources",
        referrersTitle: "Top Referrers",
        referrersEmpty: "No referrer data recorded yet.",
        clicksTitle: "Top Clicked Links",
        clicksEmpty: "No link-click data recorded yet.",
        deviceJourneysTitle: "Device Journeys",
        deviceJourneysDescription:
          "See which internal pages each tracked device moved through after reaching this URL.",
        deviceJourneysEmpty: "No device journey data is available for this URL yet.",
        topDevicePagesTitle: "Most Visited Internal Pages",
        topDevicePagesDescription:
          "These are the site pages most often visited by devices that reached this URL.",
        topDevicePagesEmpty: "No internal page visits have been recorded for these devices yet.",
        mostVisitedPage: "Most Visited Page",
        lastReferrer: "Last Referrer",
        visitedPagesTitle: "Visited Pages On This Site",
        currentUrl: "Current URL",
        deviceType: "Device Type",
        deviceProfileUnknown: "Unknown device profile",
        deviceTypes: {
          desktop: "Desktop / Laptop",
          mobile: "Mobile",
          tablet: "Tablet",
          tv: "TV",
          bot: "Bot",
          unknown: "Unknown",
        },
        deviceStats: {
          selectedViews: "Views On This URL",
          selectedClicks: "Clicks On This URL",
          siteViews: "Total Site Views",
          uniquePages: "Unique Pages",
          devices: "Devices",
        },
        recentTitle: "Recent Events",
        recentEmpty: "No recent events recorded for this URL.",
        recentLimitNotice: "Only the latest records are shown here.",
        mostClickedLinkTitle: "Most Clicked Link",
        mostClickedLinkDescription:
          "This is the link receiving the highest number of clicks for the selected tracked URL.",
        lastClicked: "Last clicked",
        pagination: {
          previous: "Previous",
          next: "Next",
          pageLabel: (page, totalPages) => `Page ${page} of ${totalPages}`,
        },
        headers: {
          time: "Time",
          type: "Type",
          traffic: "Traffic",
          device: "Device",
          click: "Click",
          referrer: "Referrer",
          source: "Source",
        },
        viewEvent: "Page View",
        clickEvent: "Click",
        unknownTitle: "Untitled Page",
        direct: "Direct / none",
        internalClick: "Internal click",
        uniqueBadge: "Unique view",
      },
      sources: {
        script: "HTML Script",
        amp: "AMP",
        pixel: "Pixel",
      },
    },
    websiteSnapshots: {
      page: {
        eyebrow: "Wayback Archive",
        title: "Website Snapshots",
        description:
          "Search historical versions of a public website, open saved dates, and download a best-effort ZIP with archived HTML, assets, scripts, images, and documents.",
        snapshotsFound: "Snapshots found",
      },
      search: {
        title: "Find Old Website Versions",
        description:
          "Enter a page URL just like Wayback. The system searches the exact URL and loads the full available capture range for the selected dates.",
        url: "Website URL",
        urlPlaceholder: "https://example.com or example.com",
        scope: "Search scope",
        fromDate: "From date",
        toDate: "To date",
        limit: "Maximum results",
        includeAssets: "Include discovered files in ZIP",
        reset: "Reset",
        submit: "Search Snapshots",
        searching: "Searching...",
      },
      scopes: {
        exact: "Exact page",
        prefix: "Page path and children",
        domain: "Whole domain",
      },
      stats: {
        selectedCaptures: "Selected captures",
        selectedCapturesDescription: "Captures available for the page selected in the viewer.",
        pageCount: "Archived pages",
        pageCountDescription: "Unique archived page URLs loaded by the current search.",
        newestYear: "Newest year",
        newestDescription: "Most recent archived snapshot in this result set.",
        oldestYear: "Oldest year",
        oldestDescription: "Earliest archived snapshot loaded for this search.",
        zipMode: "ZIP mode",
        assetsOn: "HTML + files",
        assetsOff: "HTML only",
        zipDescription: "Downloads include a manifest listing downloaded and skipped files.",
      },
      viewer: {
        title: "Snapshot Viewer",
        description:
          "Choose one archived page URL, then review its captures, timeline, live preview, and download options in one focused view.",
        pageSelect: "Archived page",
        noPages: "No pages loaded",
        empty: "Search a website to load archived pages into this viewer.",
        selectedPage: "Selected page",
        selectedPageDescription:
          "All timeline, preview, and table data below belongs to this selected archived URL.",
        newestCapture: "Newest capture",
        oldestCapture: "Oldest capture",
      },
      timeline: {
        title: "Snapshot Timeline",
        description: "A quick comparison of how many loaded captures appear in each year.",
        empty: "Search a website to see the historical timeline.",
        savedBetween: (count, oldest, newest) =>
          `Saved ${count} time${count === 1 ? "" : "s"} between ${oldest} and ${newest}.`,
        yearTitle: (year, count) => `${year}: ${count} saved capture${count === 1 ? "" : "s"}`,
      },
      history: {
        title: "Database History",
        description:
          "Recent snapshot searches and downloads are stored in MongoDB so the team can audit what was checked.",
        refresh: "Refresh History",
        loading: "Loading...",
        empty: "No snapshot history has been saved yet.",
        search: "Search",
        download: "Download",
        useSearch: "Use Search",
        delete: "Delete",
        deleting: "Deleting...",
        deleteConfirm: "Delete this saved snapshot history record?",
        deleteSuccess: "Snapshot history record deleted.",
        deleteFailed: "Failed to delete snapshot history record",
        searchMeta: (snapshots, pages) =>
          `${snapshots} capture${snapshots === 1 ? "" : "s"} across ${pages} page${pages === 1 ? "" : "s"}`,
        downloadMeta: (timestamp, assets) =>
          `${timestamp} · ${assets} asset${assets === 1 ? "" : "s"} downloaded`,
      },
      results: {
        title: "Available Snapshots",
        description:
          "Open a snapshot to preview it in Wayback, or download a ZIP to keep an offline copy.",
        sourceTitle: "Source",
        sourceDescription:
          "Results come from the public Internet Archive Wayback index. Some websites, dates, or assets may be unavailable if they were never archived or are restricted.",
        loading: "Loading website snapshots...",
        empty: "No snapshots loaded yet. Search a website to begin.",
        headers: {
          date: "Capture Date",
          url: "Archived URL",
          type: "Type",
          size: "Size",
          actions: "Actions",
        },
        open: "Open",
        preview: "Preview",
        previewing: "Previewing",
        download: "Download ZIP",
        downloading: "Downloading...",
      },
      preview: {
        title: "Live Web Preview",
        description:
          "Select any capture from the table to view that archived page directly inside the dashboard before downloading.",
        empty: "Search a website, then choose a captured date to preview it here.",
        currentlyPreviewing: "Captured at",
        timestamp: "Wayback timestamp",
        archiveSize: "Archive size",
        type: "Type",
        originalUrl: "Original URL",
        captureStrip: "Available capture times",
        loading: "Loading preview",
        loadingDescription: "Wayback is opening this archived page inside the dashboard.",
        openFull: "Open Full Wayback",
        downloadSelected: "Download This Capture",
        loadAll: "Load All",
        loadingAll: "Loading All",
        retry: "Retry",
        setViewed: "Set Viewed",
        redoViewed: "Redo View",
        viewed: "Viewed",
        loaded: "Loaded",
        loadingState: "Loading",
        failed: "Failed",
        pending: "Pending",
        cacheSummary: (loaded, total, viewed) =>
          `${loaded}/${total} previews loaded - ${viewed} viewed`,
        previewHint:
          "If a website blocks iframe preview or Wayback is slow, use Open Full Wayback. Download still uses the selected capture.",
      },
      status: {
        checkArchive: "Check Archive",
        checkingArchive: "Checking...",
        online: (ms) => `Wayback connection is online. Response time: ${ms} ms.`,
        offline: "Wayback connection is offline from this server.",
        liveResult: "Snapshot data loaded live from Wayback and cached on this server for faster repeat searches.",
        databaseResult: (count) =>
          `${count} saved snapshot${count === 1 ? "" : "s"} restored from database history.`,
        cacheResult: (cached, live) =>
          `Snapshot data used ${cached} cached request${cached === 1 ? "" : "s"} and ${live} live request${live === 1 ? "" : "s"}.`,
        idle:
          "Live processing uses the backend server to contact Wayback, then streams the finished ZIP back to your browser.",
      },
      process: {
        searching: "Searching Wayback snapshots live. Large domains may take a little longer.",
        preparingDownload:
          "Preparing ZIP live on the server. HTML is downloaded first, then discovered assets are added when available.",
      },
      messages: {
        searchSuccess: (count) => `${count} snapshot${count === 1 ? "" : "s"} loaded.`,
        historyLoadSuccess: (count) =>
          `${count} saved snapshot${count === 1 ? "" : "s"} loaded from database history.`,
        searchFailed: "Failed to search website snapshots",
        downloadSuccess: "Website snapshot ZIP download started.",
        downloadFailed: "Failed to download website snapshot ZIP",
        viewStateFailed: "Failed to save viewed state",
      },
    },
  },
  indonesian: {
    common: {
      cancel: "Batal",
      close: "Tutup",
      delete: "Hapus",
      deleting: "Menghapus...",
      loading: "Memuat",
      next: "Berikutnya",
      noDescription: "Tidak ada deskripsi",
      open: "Buka",
      previous: "Sebelumnya",
      protected: "Terlindungi",
      reset: "Reset",
      saving: "Menyimpan...",
      search: "Cari",
      standard: "Standar",
      working: "Memproses...",
    },
    privilegeCatalog: {
      moduleLabels: {
        admin: "Admin",
        "article-pool": "Kumpulan Konten",
        "audit-logs": "Log Aktivitas",
        auth: "Autentikasi",
        brands: "Brand",
        content: "Konten",
        "cuttly-link-checker": "Pengecek Link Cutt.ly",
        "database-backups": "Backup Database",
        development: "Pengembangan",
        domains: "Domain",
        "expired-domains": "Domain Kedaluwarsa",
        general: "Umum",
        groups: "Grup",
        "lp-servers": "Server LP",
        "money-sites": "Pengecek Nawala",
        "password-resets": "Reset Kata Sandi",
        privileges: "Hak Akses",
        "rank-checker": "Pengecek Peringkat",
        reporting: "Pelaporan",
        "screenshot-taker": "Pengambil Screenshot",
        "short-link-checker": "Pengecek Short Link",
        "site-analytics": "Analitik Website",
        "wayback-checker": "Pengecek Wayback",
        "website-snapshots": "Snapshot Website",
        users: "Pengguna",
      },
      actionLabels: {
        admin: "Admin",
        approve: "Setujui",
        assign: "Tugaskan",
        configure: "Atur",
        create: "Buat",
        delete: "Hapus",
        do: "Kerjakan",
        ddos: "DDoS",
        export: "Ekspor",
        generate: "Buat",
        import: "Impor",
        manage: "Kelola",
        other: "Lainnya",
        progress: "Progres",
        read: "Lihat",
        send: "Kirim",
        stats: "Statistik",
        track: "Lacak",
        update: "Ubah",
      },
      specialActionLabels: {
        adminReview: "Tinjauan Admin",
      },
      moreInfoAria: (name) => `Informasi lebih lanjut tentang ${name}`,
      privilegeCount: (count) => `${count} hak akses`,
    },
    users: {
      page: {
        title: "Manajemen Pengguna",
        description:
          "Buat pengguna, pastikan setiap akun terhubung ke grup, dan kelola akses secara tidak langsung melalui hak akses grup.",
        createUser: "Buat Pengguna",
        totalUsers: "Total pengguna",
        loadingDescription: "Mengambil data pengguna dan grup...",
        loadErrorFallback: "Gagal memuat pengguna",
        loadGroupsErrorFallback: "Gagal memuat grup",
        saveError: "Gagal menyimpan pengguna",
        changeGroupError: "Gagal mengubah grup pengguna",
        statusError: "Gagal memperbarui status pengguna",
        deleteError: "Gagal menghapus pengguna",
      },
      form: {
        titleCreate: "Buat Pengguna",
        titleEdit: "Edit Pengguna",
        description:
          "Pengguna harus berada di dalam grup. Hak akses grup menentukan apa yang bisa mereka akses di dasbor.",
        fullName: "Nama lengkap",
        email: "Email",
        password: "Kata sandi",
        group: "Grup",
        selectGroup: "Pilih grup",
        saveCreate: "Buat Pengguna",
        saveEdit: "Simpan Pengguna",
        saving: "Menyimpan...",
        cancel: "Batal",
      },
      changeGroupForm: {
        title: "Ubah Grup",
        description: (name) => `Pindahkan ${name || "pengguna ini"} ke grup lain.`,
        group: "Grup",
        selectGroup: "Pilih grup",
        submit: "Ubah Grup",
        saving: "Menyimpan...",
        cancel: "Batal",
      },
      table: {
        title: "Pengguna",
        description: "Perbarui detail profil, pindahkan pengguna antar grup, dan ubah status akun.",
        search: "Cari",
        searchPlaceholder: "Cari pengguna, email, grup, atau status",
        headers: {
          user: "Pengguna",
          group: "Grup",
          status: "Status",
          actions: "Aksi",
        },
        badges: {
          noGroup: "Tanpa grup",
          protectedGroup: "Grup Terlindungi",
          standardGroup: "Grup Standar",
        },
        statusLabels: {
          active: "Aktif",
          inactive: "Tidak aktif",
        },
        actions: {
          edit: "Edit",
          changeGroup: "Ubah Grup",
          deactivate: "Nonaktifkan",
          activate: "Aktifkan",
          delete: "Hapus",
        },
        empty: "Belum ada pengguna.",
        noMatches: "Tidak ada pengguna yang cocok.",
      },
      dialogs: {
        activateTitle: "Aktifkan Pengguna",
        activateMessage: (name) => `Aktifkan ${name}? Ini akan memulihkan akses akun.`,
        activateConfirm: "Aktifkan",
        deactivateTitle: "Nonaktifkan Pengguna",
        deactivateMessage: (name) =>
          `Nonaktifkan ${name}? Mereka tidak akan bisa lagi mengakses sistem.`,
        deactivateConfirm: "Nonaktifkan",
        deleteTitle: "Hapus Pengguna",
        deleteMessage: (name) => `Hapus ${name}? Tindakan ini tidak dapat dibatalkan.`,
        deleteConfirm: "Hapus",
      },
      errors: {
        selfDeactivate: "Anda tidak dapat menonaktifkan akun Anda sendiri.",
        editPermission: "Anda tidak memiliki izin untuk mengedit pengguna.",
        deletePermission: "Anda tidak memiliki izin untuk menghapus pengguna.",
        protectedEdit: "Pengguna di grup System administrators tidak dapat diedit.",
        protectedMove: "Pengguna di grup System administrators tidak dapat dipindahkan.",
        protectedStatus: "Status pengguna di grup System administrators tidak dapat diubah.",
        protectedDelete: "Pengguna di grup System administrators tidak dapat dihapus.",
      },
    },
    groups: {
      page: {
        title: "Manajemen Grup",
        description:
          "Atur akses dengan memberikan hak akses ke grup. Pengguna mewarisi izin dari grup tempat mereka berada.",
        createGroup: "Buat Grup",
        totalGroups: "Total grup",
        loadingDescription: "Mengambil data grup...",
        loadErrorFallback: "Gagal memuat grup",
        loadPrivilegesErrorFallback: "Gagal memuat hak akses",
        saveError: "Gagal menyimpan grup",
        deleteError: "Gagal menghapus grup",
      },
      form: {
        titleCreate: "Buat Grup",
        titleEdit: "Edit Grup",
        description:
          "Hak akses hanya diberikan ke grup. Setiap pengguna mewarisi akses dari grup yang ditugaskan.",
        name: "Nama",
        descriptionLabel: "Deskripsi",
        privileges: "Hak Akses",
        nameRequired: "Masukkan nama grup sebelum menyimpan.",
        nameExists: "Nama grup sudah ada.",
        privilegeRequired: "Pilih setidaknya satu hak akses sebelum menyimpan grup.",
        adminHint:
          "Akses Admin mencakup semua hak akses. Pilihan hak akses lain dikunci selama Admin aktif.",
        rankCheckerAdminHint:
          "Rank Checker Admin Privs mencakup semua hak akses Rank Checker. Pilihan Rank Checker lain dikunci selama hak akses ini aktif.",
        reportingDependencyHint:
          "Hak akses Reporting lanjutan memerlukan Check Progress of Reporting, sehingga hak akses dasar itu dikunci selama opsi tersebut aktif.",
        unavailablePrivileges: "Definisi hak akses tidak tersedia untuk akun ini.",
        saveCreate: "Buat Grup",
        saveEdit: "Simpan Grup",
        saving: "Menyimpan...",
        cancel: "Batal",
        includedWithRankCheckerAdmin: (name) => `${name} (sudah termasuk dalam Rank Checker Admin Privs)`,
        rankCheckerDependency: (name) =>
          `${name} (wajib saat fitur Rank Checker apa pun diaktifkan)`,
        reportingDependency: (name) =>
          `${name} (wajib saat hak akses Reporting lanjutan diaktifkan)`,
      },
      table: {
        title: "Grup",
        description:
          "Kelola deskripsi grup dan buka setiap grup untuk meninjau hak akses yang ditetapkan dalam popup terfokus.",
        search: "Cari",
        searchPlaceholder: "Cari grup, deskripsi, atau tipe",
        noDescription: "Tidak ada deskripsi",
        headers: {
          group: "Grup",
          protection: "Perlindungan",
          actions: "Aksi",
        },
        actions: {
          privileges: "Hak Akses",
          edit: "Edit",
          delete: "Hapus",
        },
        badges: {
          protected: "Terlindungi",
          standard: "Standar",
        },
        empty: "Belum ada grup.",
        noMatches: "Tidak ada grup yang cocok.",
      },
      deleteForm: {
        title: "Hapus Grup",
        description: (name) =>
          `Pilih grup yang akan menerima pengguna yang saat ini ditugaskan ke ${name} sebelum penghapusan.`,
        transferTo: "Pindahkan pengguna ke",
        selectGroup: "Pilih grup",
        submit: "Pindahkan dan Hapus",
        deleting: "Menghapus...",
        cancel: "Batal",
        noAvailableGroups:
          "Anda memerlukan setidaknya satu grup lain yang tersedia sebelum grup ini dapat dihapus.",
        close: "Tutup",
      },
      privilegesModal: {
        titleFallback: "Detail Grup",
        descriptionFallback: "Tinjau hak akses yang diberikan ke grup ini.",
        protected: "Terlindungi",
        standard: "Standar",
        empty: "Tidak ada hak akses yang diberikan ke grup ini.",
        close: "Tutup",
      },
      errors: {
        editPermission: "Anda tidak memiliki izin untuk mengedit grup.",
        deletePermission: "Anda tidak memiliki izin untuk menghapus grup.",
        protectedEdit: "Grup System administrators tidak dapat diedit.",
      },
    },
    privileges: {
      page: {
        title: "Manajemen Hak Akses",
        description:
          "Tinjau katalog izin bawaan saat ini berdasarkan modul, tujuan, dan cakupan akses.",
        totalPrivileges: "Total hak akses",
        loadingDescription: "Mengambil data hak akses...",
        loadErrorFallback: "Gagal memuat hak akses",
      },
      table: {
        title: "Matriks Izin",
        description: "Telusuri katalog hak akses bawaan saat ini berdasarkan modul dan jenis akses.",
        search: "Cari",
        searchPlaceholder: "Cari modul, aksi, key, atau deskripsi",
        empty: "Tidak ada hak akses yang cocok.",
      },
    },
    activityLogs: {
      page: {
        title: "Log Aktivitas",
        description:
          "Pantau login, kunjungan halaman, dan tindakan sistem penting dalam satu linimasa yang mudah dibaca.",
        totalMatchingRecords: "Total data yang cocok",
        loadErrorFallback: "Gagal memuat log aktivitas",
      },
      filters: {
        title: "Filter",
        description:
          "Cari berdasarkan pengguna, rute, atau ringkasan lalu persempit tampilan berdasarkan modul, kategori, dan tanggal.",
        search: "Cari",
        searchPlaceholder: "Pengguna, ringkasan, rute, atau target",
        module: "Modul",
        allModules: "Semua modul",
        category: "Kategori",
        allCategories: "Semua kategori",
        date: "Tanggal",
        reset: "Reset",
      },
      summary: {
        loadedRecords: "Data Dimuat",
        uniqueActors: "Aktor Unik",
        averageRequestTime: "Rata-rata Waktu Permintaan",
      },
      table: {
        title: "Aktivitas Terbaru",
        description:
          "Gunakan tampilan tabel panjang untuk memindai data dengan cepat, lalu buka popup untuk detail lengkap.",
        loading: "Memuat log aktivitas...",
        empty: "Tidak ada data aktivitas untuk filter yang dipilih.",
        headers: {
          time: "Waktu",
          user: "Pengguna",
          module: "Modul",
          action: "Aksi",
          summary: "Ringkasan",
          target: "Target",
          duration: "Durasi",
          details: "Detail",
        },
        open: "Buka",
        openAria: (summary) => `Buka detail untuk ${summary}`,
      },
      pagination: {
        pageLabel: (page, totalPages) => `Halaman ${page} dari ${totalPages}`,
        previous: "Sebelumnya",
        next: "Berikutnya",
      },
      detail: {
        title: "Detail Log",
        description: "Lihat siapa melakukan apa, di mana itu terjadi, dan berapa lama prosesnya.",
        close: "Tutup",
        unknownUser: "Pengguna tidak diketahui",
        user: "Pengguna",
        email: "Email",
        target: "Target",
        targetType: "Tipe Target",
        http: "HTTP",
        requestTime: "Waktu Permintaan",
        route: "Rute",
        ipAddress: "Alamat IP",
        details: "Detail",
        detailsEmpty: "Tidak ada deskripsi tambahan yang disimpan untuk kejadian ini.",
        extraContext: "Konteks Tambahan",
        noExtraContext: "Tidak ada konteks tambahan",
        userAgent: "User Agent",
      },
      values: {
        modules: {
          auth: "Autentikasi",
          "article-pool": "Kumpulan Konten",
          brands: "Brand",
          content: "Konten",
          "database-backups": "Backup Database",
          dashboard: "Dasbor",
          development: "Pengembangan",
          groups: "Grup",
          "lp-servers": "Server LP",
          "money-sites": "Pengecek Nawala",
          navigation: "Navigasi",
          "password-resets": "Reset Kata Sandi",
          reporting: "Pelaporan",
          "site-analytics": "Analitik Website",
          "website-snapshots": "Snapshot Website",
          users: "Pengguna",
        },
        categories: {
          access: "Akses",
          ai: "AI",
          auth: "Autentikasi",
          data: "Data",
          email: "Email",
          navigation: "Navigasi",
          profile: "Profil",
          settings: "Pengaturan",
          "smtp-profiles": "Profil SMTP",
        },
        actions: {
          "auth.login": "Login",
          "database-backup.delete": "Hapus Backup Database",
          "database-backup.download": "Unduh Backup Database",
          "database-backup.export": "Buat Backup Database",
          "database-backup.restore.execute": "Restore Backup Database",
          "database-backup.restore.prepare": "Siapkan Restore Database",
          "database-backup.restore.request-code": "Minta Kode Verifikasi Restore",
          "database-backup.telegram.send": "Kirim Backup Database Ke Telegram",
          "database-backup.telegram.test": "Tes Bot Restore Database",
          "database-backup.telegram.update": "Ubah Bot Restore Database",
          "group.create": "Buat Grup",
          "group.delete": "Hapus Grup",
          "group.update": "Ubah Grup",
          "page.visit": "Kunjungan Halaman",
          "site-analytics.url.block": "Blokir URL Terlacak",
          "site-analytics.url.unblock": "Buka Blokir URL Terlacak",
          "site-analytics.url.clear-stats": "Hapus Statistik URL Terlacak",
          "site-analytics.url.delete": "Hapus URL Terlacak",
          "website-snapshot.search": "Cari Snapshot Website",
          "website-snapshot.download": "Unduh Snapshot Website",
          "website-snapshot.history.delete": "Hapus Riwayat Snapshot Website",
          "user.change-group": "Ubah Grup Pengguna",
          "user.change-status": "Ubah Status Pengguna",
          "user.create": "Buat Pengguna",
          "user.delete": "Hapus Pengguna",
          "user.update": "Ubah Pengguna",
        },
        tokens: {
          access: "Akses",
          add: "Tambah",
          admin: "Admin",
          ai: "AI",
          article: "Artikel",
          analytics: "Analitik",
          auth: "Autentikasi",
          backup: "Backup",
          block: "Blokir",
          blocked: "Terblokir",
          bulk: "Massal",
          code: "Kode",
          change: "Ubah",
          checked: "Dicek",
          claim: "Klaim",
          clear: "Hapus",
          cleanup: "Pembersihan",
          content: "Konten",
          create: "Buat",
          data: "Data",
          database: "Database",
          delete: "Hapus",
          download: "Unduh",
          domain: "Domain",
          draft: "Draf",
          email: "Email",
          execute: "Eksekusi",
          generate: "Buat",
          group: "Grup",
          import: "Impor",
          login: "Login",
          lp: "LP",
          money: "Uang",
          navigation: "Navigasi",
          page: "Halaman",
          password: "Kata Sandi",
          personal: "Pribadi",
          profile: "Profil",
          progress: "Progres",
          request: "Minta",
          report: "Laporan",
          reporting: "Pelaporan",
          reset: "Reset",
          restore: "Restore",
          save: "Simpan",
          send: "Kirim",
          server: "Server",
          settings: "Pengaturan",
          site: "Situs",
          snapshot: "Snapshot",
          snapshots: "Snapshot",
          smtp: "SMTP",
          status: "Status",
          submission: "Pengiriman",
          telegram: "Telegram",
          template: "Template",
          test: "Tes",
          unchecked: "Belum Dicek",
          unblock: "Buka Blokir",
          unlock: "Buka Kunci",
          url: "URL",
          update: "Ubah",
          user: "Pengguna",
          verification: "Verifikasi",
          visit: "Kunjungan",
          view: "Lihat",
          website: "Website",
          workflow: "Alur Kerja",
        },
      },
    },
    ...DATABASE_BACKUPS_UI_COPY.indonesian,
    siteAnalytics: {
      page: {
        title: "Analitik Website",
        description:
          "Pantau kunjungan dan aktivitas klik dari halaman HTML biasa dan AMP dengan menambahkan snippet kolektor ringan ke header halaman.",
        refresh: "Muat Ulang",
        refreshing: "Memuat...",
        loadingDescription: "Memuat URL yang dilacak, jumlah kunjungan, detail klik, dan ringkasan perangkat...",
        loadErrorFallback: "Gagal memuat analitik website",
        totalUrls: "URL Terlacak",
        totalPageviews: "Tampilan Halaman",
        totalUniqueDevices: "Perangkat Unik",
        totalBotEvents: "Permintaan Bot / Unknown",
        topVisitsTitle: "Kunjungan Teratas",
        topVisitsDescription: "Lihat halaman terlacak mana yang saat ini menerima view paling banyak.",
        topVisitsEmpty: "Belum ada data kunjungan.",
      },
      install: {
        title: "Pasang Tracker",
        description:
          "Gunakan snippet HTML untuk halaman biasa. Gunakan blok AMP untuk halaman AMP. Keduanya akan mengirim trafik level halaman kembali ke sistem ini.",
        htmlTitle: "HTML / Situs Biasa",
        ampTitle: "Halaman AMP",
        htmlDescription:
          "Tambahkan sekali di head halaman atau sebelum penutup body. Script ini dimuat async, mendeteksi URL halaman, dan melacak page view serta klik.",
        ampDescription:
          "Tambahkan blok AMP ini untuk melacak page view yang terlihat dan event klik link pada halaman AMP tanpa JavaScript kustom.",
        optionalOverride: "Override opsional:",
        optionalOverrideValue:
          "Tambahkan data-main-url=\"https://example.com/page\" jika Anda ingin memaksa URL utama kustom, bukan path halaman saat ini.",
        openHtml: "Buka Snippet HTML",
        openAmp: "Buka Snippet AMP",
        copyHtml: "Salin Snippet HTML",
        copyAmp: "Salin Snippet AMP",
        copiedHtml: "Snippet tracking HTML berhasil disalin.",
        copiedAmp: "Snippet tracking AMP berhasil disalin.",
        copyFailed: "Gagal menyalin snippet tracking",
        seoSafe:
          "Aman untuk SEO: tracker dimuat async, tidak mengubah link, dan tidak mengubah konten halaman yang terlihat.",
        deviceLogic:
          "Perangkat unik diidentifikasi dengan local storage atau cookie pada halaman biasa, dan client ID AMP pada halaman AMP jika tersedia.",
        ampLimit:
          "Klik link AMP tetap dapat dilacak per halaman, tetapi beberapa detail per-link dapat bergantung pada dukungan variabel AMP di halaman tersebut.",
        modalTitleHtml: "Snippet Tracking HTML",
        modalTitleAmp: "Snippet Tracking AMP",
        modalDescriptionHtml:
          "Tambahkan satu script ini ke header halaman atau tepat sebelum penutup body untuk mengumpulkan page view dan klik.",
        modalDescriptionAmp:
          "Gunakan blok aman untuk AMP ini di dalam halaman agar trafik AMP dapat dilacak tanpa JavaScript kustom.",
        popupHint:
          "Tombol install yang ringkas membuat halaman lebih rapi. Buka snippet hanya saat Anda membutuhkannya.",
      },
      filters: {
        search: "Cari",
        searchPlaceholder: "Cari URL, host, atau judul halaman",
        traffic: "Trafik",
        allTraffic: "Semua trafik",
        human: "Manusia",
        bot: "Bot",
        unknown: "Unknown",
      },
      table: {
        title: "URL Terlacak",
        description:
          "Setiap baris mewakili URL halaman yang ditemukan oleh tracker. Buka satu baris untuk melihat perangkat, klik, referrer, dan request terbaru.",
        empty: "Belum ada data analitik website yang terkumpul.",
        headers: {
          url: "URL Utama",
          title: "Judul",
          pageviews: "View",
          uniqueDevices: "Perangkat",
          clicks: "Klik",
          bots: "Bot / Unknown",
          lastSeen: "Terakhir Terlihat",
          status: "Status",
          actions: "Aksi",
        },
        open: "Buka Analitik",
        blocked: "Diblokir",
        active: "Aktif",
        clearStats: "Hapus Statistik",
        deleteUrl: "Hapus URL",
        block: "Blokir",
        unblock: "Buka Blokir",
      },
      detail: {
        title: "Detail URL",
        description:
          "Tinjau trafik, bot yang terdeteksi, referrer, link yang paling sering diklik, dan event terbaru untuk URL terlacak ini.",
        pageTitle: "Detail Analitik",
        pageDescription:
          "Gunakan dropdown URL terlacak untuk berpindah antar halaman dan melihat grafik, perjalanan perangkat, serta aktivitas terbaru.",
        close: "Tutup",
        backToList: "Kembali Ke URL",
        selectUrl: "URL Terlacak",
        openUrl: "Buka URL",
        refresh: "Muat Ulang Detail",
        loadingDescription: "Memuat analitik detail untuk URL terlacak ini...",
        loadErrorFallback: "Gagal memuat detail URL terlacak",
        fullView: "View Analytics Penuh",
        firstSeen: "Pertama Terlihat",
        lastSeen: "Terakhir Terlihat",
        statusBlocked: "Pelacakan Diblokir",
        statusActive: "Pelacakan Aktif",
        actions: {
          clearStats: "Hapus Statistik",
          clearing: "Menghapus...",
          deleteUrl: "Hapus URL",
          deleting: "Menghapus URL...",
          block: "Blokir URL",
          blocking: "Memblokir...",
          unblock: "Buka Blokir URL",
          unblocking: "Membuka blokir...",
        },
        confirmations: {
          clearStats:
            "Hapus semua statistik analitik yang tersimpan untuk URL ini? Kunjungan baru masih bisa dikumpulkan setelahnya.",
          deleteUrl:
            "Hapus URL terlacak ini dari analitik sekarang? Ini akan menghapus statistik tersimpan dan aturan blokirnya.",
          blockUrl:
            "Blokir URL terlacak ini dari pengumpulan analitik berikutnya? Statistik yang ada tetap tersimpan sampai Anda menghapusnya.",
          unblockUrl:
            "Izinkan URL terlacak ini mengumpulkan analitik lagi?",
        },
        actionSuccess: {
          clearStats: "Statistik URL terlacak berhasil dihapus.",
          deleteUrl: "URL terlacak berhasil dihapus dari analitik.",
          blockUrl: "URL terlacak berhasil diblokir dari pelacakan berikutnya.",
          unblockUrl: "Pelacakan URL terlacak berhasil dipulihkan.",
        },
        summary: {
          pageviews: "Tampilan Halaman",
          uniqueViews: "View Unik",
          clicks: "Klik",
          uniqueDevices: "Perangkat Unik",
        },
        topVisitsTitle: "Kunjungan Teratas Di Situs Ini",
        topVisitsDescription:
          "Ini adalah halaman terlacak yang paling sering dikunjungi pada situs yang sama dengan URL terpilih.",
        topVisitsEmpty: "Belum ada data kunjungan teratas untuk situs ini.",
        trafficMixTitle: "Perbandingan Trafik",
        sourceMixTitle: "Perbandingan Sumber",
        engagementTitle: "Perbandingan Engagement",
        ratioTitle: "Rasio Utama",
        ratios: {
          clickRate: "Rasio Klik",
          returnRate: "View Kembali",
          cleanTraffic: "Trafik Manusia",
        },
        sourcesTitle: "Sumber Koleksi",
        referrersTitle: "Referrer Teratas",
        referrersEmpty: "Belum ada data referrer yang tersimpan.",
        clicksTitle: "Link Paling Sering Diklik",
        clicksEmpty: "Belum ada data klik link yang tersimpan.",
        deviceJourneysTitle: "Perjalanan Perangkat",
        deviceJourneysDescription:
          "Lihat halaman internal mana saja yang dikunjungi setiap perangkat terlacak setelah mencapai URL ini.",
        deviceJourneysEmpty: "Belum ada data perjalanan perangkat untuk URL ini.",
        topDevicePagesTitle: "Halaman Internal Paling Sering Dikunjungi",
        topDevicePagesDescription:
          "Ini adalah halaman situs yang paling sering dikunjungi oleh perangkat yang mencapai URL ini.",
        topDevicePagesEmpty: "Belum ada kunjungan halaman internal yang tercatat untuk perangkat ini.",
        mostVisitedPage: "Halaman Paling Sering Dikunjungi",
        lastReferrer: "Referrer Terakhir",
        visitedPagesTitle: "Halaman Yang Dikunjungi Di Situs Ini",
        currentUrl: "URL Saat Ini",
        deviceType: "Tipe Perangkat",
        deviceProfileUnknown: "Profil perangkat tidak diketahui",
        deviceTypes: {
          desktop: "Desktop / Laptop",
          mobile: "Mobile",
          tablet: "Tablet",
          tv: "TV",
          bot: "Bot",
          unknown: "Unknown",
        },
        deviceStats: {
          selectedViews: "View Pada URL Ini",
          selectedClicks: "Klik Pada URL Ini",
          siteViews: "Total View Situs",
          uniquePages: "Halaman Unik",
          devices: "Perangkat",
        },
        recentTitle: "Event Terbaru",
        recentEmpty: "Belum ada event terbaru untuk URL ini.",
        recentLimitNotice: "Hanya data terbaru yang ditampilkan di sini.",
        mostClickedLinkTitle: "Link Paling Sering Diklik",
        mostClickedLinkDescription:
          "Ini adalah link dengan jumlah klik tertinggi untuk URL terlacak yang sedang dipilih.",
        lastClicked: "Klik terakhir",
        pagination: {
          previous: "Sebelumnya",
          next: "Berikutnya",
          pageLabel: (page, totalPages) => `Halaman ${page} dari ${totalPages}`,
        },
        headers: {
          time: "Waktu",
          type: "Tipe",
          traffic: "Trafik",
          device: "Perangkat",
          click: "Klik",
          referrer: "Referrer",
          source: "Sumber",
        },
        viewEvent: "Page View",
        clickEvent: "Klik",
        unknownTitle: "Halaman Tanpa Judul",
        direct: "Direct / none",
        internalClick: "Klik internal",
        uniqueBadge: "View unik",
      },
      sources: {
        script: "Script HTML",
        amp: "AMP",
        pixel: "Pixel",
      },
    },
    websiteSnapshots: {
      page: {
        eyebrow: "Arsip Wayback",
        title: "Snapshot Website",
        description:
          "Cari versi historis website publik, buka tanggal yang tersimpan, dan unduh ZIP best-effort berisi HTML arsip, asset, script, gambar, dan dokumen.",
        snapshotsFound: "Snapshot ditemukan",
      },
      search: {
        title: "Cari Versi Website Lama",
        description:
          "Masukkan URL halaman seperti Wayback. Sistem mencari URL exact dan memuat seluruh capture yang tersedia untuk rentang tanggal terpilih.",
        url: "URL Website",
        urlPlaceholder: "https://example.com atau example.com",
        scope: "Cakupan pencarian",
        fromDate: "Dari tanggal",
        toDate: "Sampai tanggal",
        limit: "Maksimum hasil",
        includeAssets: "Sertakan file yang ditemukan dalam ZIP",
        reset: "Reset",
        submit: "Cari Snapshot",
        searching: "Mencari...",
      },
      scopes: {
        exact: "Halaman exact",
        prefix: "Path halaman dan turunannya",
        domain: "Seluruh domain",
      },
      stats: {
        selectedCaptures: "Capture terpilih",
        selectedCapturesDescription: "Capture tersedia untuk halaman yang dipilih di viewer.",
        pageCount: "Halaman arsip",
        pageCountDescription: "URL halaman arsip unik yang dimuat oleh pencarian saat ini.",
        newestYear: "Tahun terbaru",
        newestDescription: "Snapshot arsip terbaru pada hasil ini.",
        oldestYear: "Tahun terlama",
        oldestDescription: "Snapshot arsip paling lama yang dimuat untuk pencarian ini.",
        zipMode: "Mode ZIP",
        assetsOn: "HTML + file",
        assetsOff: "Hanya HTML",
        zipDescription: "Unduhan menyertakan manifest berisi file yang berhasil dan gagal diambil.",
      },
      viewer: {
        title: "Viewer Snapshot",
        description:
          "Pilih satu URL halaman arsip, lalu lihat capture, timeline, preview live, dan opsi unduh dalam satu tampilan fokus.",
        pageSelect: "Halaman arsip",
        noPages: "Belum ada halaman",
        empty: "Cari website untuk memuat halaman arsip ke viewer ini.",
        selectedPage: "Halaman terpilih",
        selectedPageDescription:
          "Semua data timeline, preview, dan tabel di bawah ini milik URL arsip yang dipilih.",
        newestCapture: "Capture terbaru",
        oldestCapture: "Capture terlama",
      },
      timeline: {
        title: "Timeline Snapshot",
        description: "Perbandingan cepat jumlah capture yang dimuat pada setiap tahun.",
        empty: "Cari website untuk melihat timeline historis.",
        savedBetween: (count, oldest, newest) =>
          `Tersimpan ${count} kali antara ${oldest} dan ${newest}.`,
        yearTitle: (year, count) => `${year}: ${count} capture tersimpan`,
      },
      history: {
        title: "Riwayat Database",
        description:
          "Pencarian dan unduhan snapshot terbaru disimpan di MongoDB agar tim dapat mengaudit apa yang dicek.",
        refresh: "Muat Ulang Riwayat",
        loading: "Memuat...",
        empty: "Belum ada riwayat snapshot yang tersimpan.",
        search: "Pencarian",
        download: "Unduhan",
        useSearch: "Gunakan Pencarian",
        delete: "Hapus",
        deleting: "Menghapus...",
        deleteConfirm: "Hapus data riwayat snapshot ini?",
        deleteSuccess: "Riwayat snapshot berhasil dihapus.",
        deleteFailed: "Gagal menghapus riwayat snapshot",
        searchMeta: (snapshots, pages) => `${snapshots} capture di ${pages} halaman`,
        downloadMeta: (timestamp, assets) => `${timestamp} · ${assets} asset diunduh`,
      },
      results: {
        title: "Snapshot Tersedia",
        description:
          "Buka snapshot untuk pratinjau di Wayback, atau unduh ZIP untuk menyimpan salinan offline.",
        sourceTitle: "Sumber",
        sourceDescription:
          "Hasil berasal dari indeks publik Internet Archive Wayback. Beberapa website, tanggal, atau asset bisa tidak tersedia jika tidak pernah diarsipkan atau dibatasi.",
        loading: "Memuat snapshot website...",
        empty: "Belum ada snapshot yang dimuat. Cari website untuk mulai.",
        headers: {
          date: "Tanggal Capture",
          url: "URL Arsip",
          type: "Tipe",
          size: "Ukuran",
          actions: "Aksi",
        },
        open: "Buka",
        preview: "Preview",
        previewing: "Sedang Dipreview",
        download: "Unduh ZIP",
        downloading: "Mengunduh...",
      },
      preview: {
        title: "Preview Web Live",
        description:
          "Pilih capture dari tabel untuk melihat halaman arsip langsung di dalam dashboard sebelum mengunduh.",
        empty: "Cari website, lalu pilih tanggal capture untuk menampilkan preview di sini.",
        currentlyPreviewing: "Dicapture pada",
        timestamp: "Timestamp Wayback",
        archiveSize: "Ukuran arsip",
        type: "Tipe",
        originalUrl: "URL Asli",
        captureStrip: "Waktu capture tersedia",
        loading: "Memuat preview",
        loadingDescription: "Wayback sedang membuka halaman arsip ini di dalam dashboard.",
        openFull: "Buka Wayback Penuh",
        downloadSelected: "Unduh Capture Ini",
        loadAll: "Muat Semua",
        loadingAll: "Memuat Semua",
        retry: "Coba Lagi",
        setViewed: "Set Sudah Dilihat",
        redoViewed: "Ulangi Lihat",
        viewed: "Sudah Dilihat",
        loaded: "Dimuat",
        loadingState: "Memuat",
        failed: "Gagal",
        pending: "Menunggu",
        cacheSummary: (loaded, total, viewed) =>
          `${loaded}/${total} preview dimuat - ${viewed} sudah dilihat`,
        previewHint:
          "Jika website memblokir preview iframe atau Wayback lambat, gunakan Buka Wayback Penuh. Unduhan tetap memakai capture yang dipilih.",
      },
      status: {
        checkArchive: "Cek Arsip",
        checkingArchive: "Mengecek...",
        online: (ms) => `Koneksi Wayback online. Waktu respons: ${ms} ms.`,
        offline: "Koneksi Wayback offline dari server ini.",
        liveResult: "Data snapshot dimuat live dari Wayback dan dicache di server ini agar pencarian ulang lebih cepat.",
        databaseResult: (count) => `${count} snapshot tersimpan dimuat dari riwayat database.`,
        cacheResult: (cached, live) =>
          `Data snapshot memakai ${cached} request cache dan ${live} request live.`,
        idle:
          "Proses live memakai server backend untuk menghubungi Wayback, lalu mengirim ZIP selesai kembali ke browser Anda.",
      },
      process: {
        searching: "Mencari snapshot Wayback secara live. Domain besar bisa membutuhkan waktu lebih lama.",
        preparingDownload:
          "Menyiapkan ZIP secara live di server. HTML diunduh dulu, lalu asset yang ditemukan ditambahkan jika tersedia.",
      },
      messages: {
        searchSuccess: (count) => `${count} snapshot dimuat.`,
        historyLoadSuccess: (count) => `${count} snapshot tersimpan dimuat dari riwayat database.`,
        searchFailed: "Gagal mencari snapshot website",
        downloadSuccess: "Unduhan ZIP snapshot website dimulai.",
        downloadFailed: "Gagal mengunduh ZIP snapshot website",
        viewStateFailed: "Gagal menyimpan status sudah dilihat",
      },
    },
  },
};
