export const NAV_ITEMS = [
  {
    label: "Dashboard",
    path: "/dashboard",
    icon: "dashboard",
    description: "Overview and access summary",
  },
  {
    label: "Brands",
    path: "/brands",
    icon: "brands",
    description: "Manage tracked brand records",
  },
  {
    label: "Money Site Checker",
    path: "/money-sites",
    icon: "link",
    description: "Manage money sites",
    requiredAnyPrivileges: [
      "VIEW_MONEY_SITES",
      "CREATE_MONEY_SITES",
      "EDIT_MONEY_SITES",
      "DELETE_MONEY_SITES",
    ],
  },
  {
    label: "Expired Domains",
    path: "/expired-domains",
    icon: "history",
    description: "Upload and manage expired domain lists",
    requiredAnyPrivileges: ["VIEW_EXPIRED_DOMAINS", "IMPORT_EXPIRED_DOMAINS"],
  },
  {
    label: "Screenshot Taker",
    path: "/screenshot-taker",
    icon: "camera",
    description: "Capture previews of assigned websites",
    requiredAnyPrivileges: [
      "VIEW_SCREENSHOT_TAKER",
      "MANAGE_SCREENSHOT_TAKER",
      "CAPTURE_SCREENSHOT_TAKER",
      "SCHEDULE_SCREENSHOT_TAKER",
    ],
  },
  {
    label: "Short Link Checker",
    path: "/short-link-checker",
    icon: "link",
    description: "Check short links and alert on HTTP errors",
    requiredAnyPrivileges: [
      "VIEW_SHORT_LINK_CHECKER",
      "MANAGE_SHORT_LINK_CHECKER",
      "CHECK_SHORT_LINKS",
      "MANAGE_SHORT_LINK_TELEGRAM",
      "SCHEDULE_SHORT_LINK_CHECKER",
    ],
  },
  {
    label: "Cutt.ly Link Checker",
    path: "/cuttly-link-checker",
    icon: "link",
    description: "Check Cutt.ly blocked-domain status with API alerts",
    requiredAnyPrivileges: [
      "VIEW_CUTTLY_LINK_CHECKER",
      "MANAGE_CUTTLY_LINK_CHECKER",
      "CHECK_CUTTLY_LINKS",
      "SCHEDULE_CUTTLY_LINK_CHECKER",
      "MANAGE_CUTTLY_API_SETTINGS",
      "MANAGE_CUTTLY_LINK_TELEGRAM",
    ],
  },
  {
    label: "LP Servers",
    path: "/lp-servers",
    icon: "server",
    description: "Manage landing page server hosting details",
    requiredAnyPrivileges: [
      "VIEW_LP_SERVERS_DETAILS",
      "CREATE_LP_SERVERS_DETAILS",
      "EDIT_LP_SERVERS_DETAILS",
      "DELETE_LP_SERVERS_DETAILS",
      "IMPORT_LP_SERVERS_DETAILS",
      "EXPORT_LP_SERVERS_DETAILS",
    ],
  },
  {
    label: "Development",
    path: "/development",
    icon: "tasks",
    description: "Manage development workflows",
    requiredAnyPrivileges: [
      "CREATE_DOMAINS",
      "EDIT_DOMAINS",
      "DELETE_DOMAINS",
      "ASSIGN_DEVELOPMENT",
      "DO_DEVELOPMENT",
      "VIEW_DEVELOPMENT_PROGRESS",
      "ADD_TEMPLATES",
      "ADD_CONTENT",
      "EDIT_CONTENT",
    ],
  },
  {
    label: "Content Pool",
    path: "/article-pool",
    icon: "tasks",
    description: "Create and manage brand content",
    requiredAnyPrivileges: [
      "READ_ARTICLE_POOL",
      "CREATE_ARTICLE_POOL",
      "EDIT_ARTICLE_POOL",
      "DELETE_ARTICLE_POOL",
      "IMPORT_ARTICLE_POOL",
      "EXPORT_ARTICLE_POOL",
    ],
  },
  {
    label: "Reporting Tasks",
    path: "/reporting-tasks",
    icon: "tasks",
    description: "Track and manage reporting work items assigned to staff",
    requiredAnyPrivileges: [
      "READ_REPORTING_TASKS",
      "ADD_REPORTING_TASKS",
      "RECEIVE_REPORTING_TASKS",
      "DO_DDOS_REPORTING_TASKS",
      "TRACK_REPORTING_TASKS",
    ],
  },
  {
    label: "Reporting",
    path: "/reporting",
    icon: "reporting",
    description: "View reports and performance snapshots",
    requiredAnyPrivileges: [
      "ADD_REPORTING_URLS",
      "VIEW_REPORTING_PROGRESS",
      "DO_REPORTING",
      "GENERATE_REPORTING_AI_EMAIL",
      "SEND_REPORTING_EMAIL",
      "VIEW_REPORTING_ADMIN_REVIEW",
      "EDIT_REPORTING_WORKFLOWS",
      "EDIT_REPORTING_TASKS",
      "DELETE_REPORTING_TASKS",
      "MANAGE_REPORTING_SMTP_PROFILES",
    ],
  },
  {
    label: "Tasks",
    path: "/tasks",
    icon: "tasks",
    description: "Track operational work items",
    requiredPrivilege: "ADMIN_ACCESS",
  },
  {
    label: "Users",
    path: "/users",
    icon: "users",
    description: "Maintain user accounts and assignments",
    requiredAnyPrivileges: ["CREATE_USERS", "EDIT_USERS", "DELETE_USERS"],
  },
  {
    label: "Groups",
    path: "/groups",
    icon: "groups",
    description: "Organize teams and access groups",
    requiredAnyPrivileges: ["CREATE_GROUPS", "EDIT_GROUPS", "DELETE_GROUPS"],
  },
  {
    label: "Privileges",
    path: "/privileges",
    icon: "shield",
    description: "Review role permissions",
    requiredPrivilege: "ADMIN_ACCESS",
  },
  {
    label: "Database Backups",
    path: "/database-backups",
    icon: "server",
    description: "Create, download, and restore full MongoDB backups",
    requiredAnyPrivileges: [
      "VIEW_DATABASE_BACKUPS",
      "EXPORT_DATABASE_BACKUPS",
      "MANAGE_DATABASE_BACKUPS",
      "RESTORE_DATABASE_BACKUPS",
      "SEND_DATABASE_BACKUPS_TELEGRAM",
    ],
  },
  {
    label: "Website Analytics",
    path: "/site-analytics",
    icon: "chart",
    description: "Track visits and clicks from external HTML and AMP pages",
    requiredAnyPrivileges: ["VIEW_SITE_ANALYTICS", "MANAGE_SITE_ANALYTICS"],
  },
  {
    label: "Website Snapshots",
    path: "/website-snapshots",
    icon: "history",
    description: "Search old website versions and download archived ZIP snapshots",
    requiredAnyPrivileges: [
      "VIEW_WEBSITE_SNAPSHOTS",
      "DOWNLOAD_WEBSITE_SNAPSHOTS",
      "MANAGE_WEBSITE_SNAPSHOTS",
    ],
  },
  {
    label: "Activity Logs",
    path: "/activity-logs",
    icon: "history",
    description: "Review login, navigation, and action history",
    requiredAnyPrivileges: ["VIEW_SYSTEM_AUDIT_LOGS", "VIEW_OWN_AUDIT_LOGS"],
  },
  {
    label: "Rank Checker",
    path: "/rank-checker",
    icon: "network",
    description: "Run SEO rank checks and manage service automation",
    requiredAnyPrivileges: [
      "SHOW_RANK_CHECKER",
      "RANK_CHECKER_ADMIN_PRIVS",
      "RANK_CHECKER_MANUAL_CHECKER",
      "RANK_CHECKER_BULK_CHECKER",
      "RANK_CHECKER_ADD_DOMAINS",
      "RANK_CHECKER_LOGS",
    ],
  },
  {
    label: "SEO Tools",
    path: "/seo-tools",
    icon: "tools",
    description: "Access SEO utility workflows",
    requiredPrivilege: "ADMIN_ACCESS",
  },
  {
    label: "Mail Server",
    path: "/mail-server",
    icon: "mail",
    description: "Monitor mail configuration",
    requiredPrivilege: "ADMIN_ACCESS",
  },
];
