const DEVELOPMENT_UI_COPY = {
  english: {
    common: {
      close: "Close",
      cancel: "Cancel",
      save: "Save",
      saving: "Saving...",
      delete: "Delete",
      search: "Search",
      date: "Date",
      brand: "Brand",
      developer: "Developer",
      domain: "Domain",
      content: "Content",
      title: "Title",
      description: "Description",
      note: "Note",
      retry: "Retry",
      remove: "Remove",
      filter: "Filter",
      details: "Details",
      progress: "Progress",
      status: "Status",
      hosting: "Hosting",
      gsc: "GSC",
      info: "Info",
      notAvailable: "-",
      open: "Open",
      name: "Name",
      created: "Created",
      addedBy: "Added By",
      addedOn: "Added On",
      assignedBy: "Assigned By",
      assignedOn: "Assigned On",
      lastUpdated: "Last Updated",
      loading: "Loading",
      total: "Total",
      words: (count) => `${count} words`,
      noDescriptionAdded: "No description added.",
      yes: "Yes",
      no: "No",
      loadingContent: "Loading content...",
    },
    statuses: {
      development: {
        new: "New",
        "in-progress": "In Progress",
        completed: "Completed",
      },
      hosting: {
        "not-hosted": "Not Hosted",
        hosted: "Hosted",
      },
      gsc: {
        "not-done": "Not Done",
        done: "Done",
      },
      content: {
        ready: "Content Ready",
        pending: "Content Pending",
      },
    },
    pageBadges: {
      landingPage: { label: "LP", title: "Landing Page" },
      termsAndConditionsPage: { label: "TC", title: "Terms & Conditions Page" },
      aboutPage: { label: "AB", title: "About Page" },
      contactPage: { label: "CP", title: "Contact Page" },
    },
    page: {
      title: "Development",
      description:
        "Assign brand domains, inspect content, and track progress through development, hosting, and GSC.",
      addDomain: "Add Domain",
      info: "Info",
      totalDevelopmentDomains: "Total development domains",
      searchPlaceholder: "Brand, domain, developer",
      loadError: "Failed to load development data",
      loadingTitle: "Loading",
      loadingDescription: "Fetching development data...",
      addDomainError: "Failed to add domain",
      addInfoError: "Failed to add info",
      deleteInfoError: "Failed to delete info",
      updateTaskError: "Failed to update development task",
      saveContentError: "Failed to save content",
      updateContentPoolError: "Failed to update content pool item",
      releaseContentEditorError: "Failed to release content editor",
      noContentPoolSelected: "No Content Pool item was selected for this development domain.",
      openContentPoolError: "Failed to open Content Pool editor",
      noContentSelected: "No content was selected for this development domain.",
      assignDomainError: "Failed to assign domain",
      updateDomainError: "Failed to update domain",
      deleteDomainError: "Failed to delete domain",
      overallProgressAria: (progress) => `Open overall progress summary (${progress}%)`,
      templatesOnlyTitle: "Templates",
      templatesOnlyDescription:
        "Open the templates library to review or add development template links.",
      openTemplates: "Open Templates",
      editContentPool: "Edit Content Pool",
    },
    addDomainForm: {
      title: "Add Domain",
      description:
        "Create a development-ready domain record with content and blogger resources.",
      brand: "Brand",
      selectBrand: "Select brand",
      content: "Content",
      selectContent: "Select Content",
      changeContent: "Change Content",
      remove: "Remove",
      selectBrandFirst: "Select a brand first to load related content.",
      readPermissionRequired: "Content Pool read permission is required.",
      chooseContentHelp: "Choose content to attach it to this domain.",
      selectedContent: "Selected Content",
      domain: "Domain",
      landingPage: "Landing Page",
      termsAndConditionsPage: "Terms & Conditions Page",
      aboutPage: "About Page",
      contactPage: "Contact Page",
      domainPlaceholder: "https://example.com",
      landingPagePlaceholder: "https://example.com/landing",
      termsPlaceholder: "https://example.com/terms",
      aboutPlaceholder: "https://example.com/about",
      contactPlaceholder: "https://example.com/contact",
      selectBrandBeforeChoosing: "Select a brand before choosing content.",
      contentPoolPermissionRequired:
        "Content Pool read permission is required to select content.",
      loadBrandContentError: "Failed to load brand content.",
      selectBrandError: "Select a brand.",
      domainRequired: "Domain is required.",
      landingRequired: "Landing Page is required.",
      saveError: "Failed to add development domain",
      submit: "Add Domain",
      articlePicker: {
        title: "Select Content",
        filteredForBrand: (brandName) => `Content filtered for ${brandName}.`,
        selectBrandFirst: "Select a brand before choosing content.",
        contentTitles: "Content Titles",
        found: (count) => `${count} found`,
        loading: "Loading content...",
        noContentFound: "No content found for this brand.",
        selectTitleToPreview: "Select a title to preview the full content.",
        useContent: "Use Content",
        cancel: "Cancel",
      },
    },
    assignForm: {
      title: "Assign Developer",
      developer: "Developer",
      selectDeveloper: "Select developer",
      selectDeveloperError: "Select a developer.",
      saveError: "Failed to assign developer",
      assigning: "Assigning...",
      assign: "Assign",
      cancel: "Cancel",
    },
    assignTable: {
      title: "Assign Table",
      description:
        "Assign ready domains to developers and inspect the content before dispatch.",
      headers: {
        date: "Date",
        brand: "Brand",
        domain: "Domain",
        content: "Content",
        contentBy: "Content By",
        assignedTo: "Assigned To",
        edit: "Edit",
        progress: "Progress",
      },
      availablePages: "Available pages",
      previewSelectedContent: "Preview selected content",
      noContentSelected: "No content selected",
      contentBeingAddedBy: (name) => `Content is being added by ${name}`,
      contentWasAddedBy: (name) => `Content was added by ${name}`,
      contentNotAddedYet: "Content has not been added yet",
      assigning: "Assigning...",
      assign: "Assign",
      editDomain: "Domain",
      contentPool: "Content Pool",
      contentBeingEditedBy: (name) => `Content is being edited by ${name || "another user"}`,
      editSelectedContentPool: "Edit selected Content Pool item",
      selectContentInAddDomain: "Select content in Add Domain first",
      empty: "No data available in table",
      assignedDeveloper: (name, count) => `${name} - ${count}`,
    },
    doTable: {
      title: "Development Tasks",
      description:
        "Track developer work, hosting status, and GSC completion in one place.",
      headers: {
        date: "Date",
        developer: "Developer",
        brand: "Brand",
        domain: "Domain",
        status: "Status",
        hosting: "Hosting",
        gsc: "GSC",
        content: "Content",
      },
      previewContent: "Preview content",
      empty: "No data available in table",
      mobileLabels: {
        developer: "Developer",
        domain: "Domain",
        status: "Status",
        hosting: "Hosting",
        gsc: "GSC",
        content: "Content",
      },
    },
    contentModal: {
      previewTitle: "Content Preview",
      editTitle: "Add Content",
      close: "Close",
      pages: "Pages",
      clickToCopy: (label) => `Click to copy ${String(label || "").toLowerCase()}`,
      copied: (label) => `${label} copied.`,
      copyTextError: (label) => `Failed to copy ${String(label || "").toLowerCase()}.`,
      title: "Title",
      description: "Description",
      article: "Article",
      articlePlaceholder: "Write the article content here",
      note: "Note",
      notePlaceholder: "Add note here",
      resources: "Resources",
      logo: "Logo",
      banner: "Banner",
      favicon: "Favicon",
      button: "Button",
      resourcePlaceholder: "Paste image link here",
      noResourceImages: "No resource images available.",
      copyImageSuccess: "Image address copied.",
      copyImageError: "Failed to copy image address.",
      saveError: "Failed to save content",
      saveContent: "Save Content",
      cancel: "Cancel",
    },
    templatesModal: {
      title: "Info",
      description:
        "Review available development info items and maintain notes for the team.",
      close: "Close",
      name: "Name",
      notes: "Notes",
      addInfo: "Add Info",
      infoRegistry: "Info Registry",
      headers: {
        name: "Name",
        addedBy: "Added By",
        created: "Created",
        note: "Note",
        action: "Action",
      },
      viewNote: "View note",
      noNoteAdded: "No note added",
      delete: "Delete",
      empty: "No info entries available.",
      saveError: "Failed to add info",
    },
    editDomainForm: {
      title: "Edit Domain",
      description: "Update the brand and core page URLs only.",
      brand: "Brand",
      selectBrand: "Select brand",
      domain: "Domain",
      landingPage: "Landing Page",
      termsAndConditionsPage: "Terms & Conditions Page",
      aboutPage: "About Page",
      contactPage: "Contact Page",
      domainPlaceholder: "https://example.com",
      domainRequired: "Domain is required.",
      landingRequired: "Landing Page is required.",
      saveChanges: "Save Changes",
      deleteDomain: "Delete Domain",
      cancel: "Cancel",
      updateError: "Failed to update domain",
      deleteError: "Failed to delete domain",
      deleteTitle: "Delete Domain",
      deleteMessage: (domain) => `Delete ${domain || "this domain"}? This action cannot be undone.`,
    },
    overallProgress: {
      title: "Overall Progress",
      description: "Review individual progress with a date filter.",
      close: "Close",
      filter: "Filter",
      brand: "Brand",
      allBrands: "All brands",
      developer: "Developer",
      allDevelopers: "All developers",
      total: "Total",
      totalDomains: (count) => `${count} domains`,
      completed: "Completed",
      hosted: "Hosted",
      gscDone: "GSC Done",
      headers: {
        date: "Date",
        brand: "Brand",
        domain: "Domain",
        developer: "Developer",
        progress: "Progress",
        status: "Status",
        hosting: "Hosting",
        gsc: "GSC",
        details: "Details",
      },
      openDetailsAria: (domain) => `Open details for ${domain || "this domain"}`,
      empty: "No data available in table",
    },
    domainDetails: {
      eyebrow: "Domain Details",
      closeDetails: "Close details",
      contentReady: "Content Ready",
      contentPending: "Content Pending",
      ownership: "Ownership",
      addedBy: "Added By",
      addedOn: "Added On",
      assignedBy: "Assigned By",
      assignedOn: "Assigned On",
      developer: "Developer",
      notAssigned: "Not assigned",
      lastUpdated: "Last Updated",
      contentSection: "Content",
      contentAddedBy: "Content Added By",
      notAddedYet: "Not added yet",
      contentAddedOn: "Content Added On",
      editingBy: "Editing By",
      noActiveEditor: "No active editor",
      editingStarted: "Editing Started",
      title: "Title",
      note: "Note",
      buildSetup: "Build Setup",
      info: "Info",
      noInfoSelected: "No info selected",
      infoNotes: "Info Notes",
      progress: "Progress",
      logos: "Logos",
      buttonsGifs: "Buttons / GIFs",
      links: "Links",
      landingPage: "Landing Page",
      aboutPage: "About Page",
      contactPage: "Contact Page",
      termsPage: "Terms Page",
      heroImage: "Hero Image",
      favicon: "Favicon",
      activityTimeline: "Activity Timeline",
      noActivityHistory: "No activity history is available for this domain yet.",
      timeline: {
        domainAdded: "Domain added",
        developmentAssigned: "Development assigned",
        contentEditingStarted: "Content editing started",
        contentLockOpened: "Content lock opened",
        contentSaved: "Content saved",
        contentUpdatedDetail: "Title, description, article, and assets updated",
        latestRecordUpdate: "Latest record update",
        noDeveloperAssigned: "No developer assigned",
        statusDetail: (developmentStatus, hostingStatus, gscStatus) =>
          `Status: ${developmentStatus}, Hosting: ${hostingStatus}, GSC: ${gscStatus}`,
      },
    },
    progressForm: {
      title: "Update Progress",
      template: "Template",
      noInfoSelected: "No info selected",
      progress: "Progress",
      development: "Development",
      hosting: "Hosting",
      gsc: "GSC",
      saveProgress: "Save Progress",
      cancel: "Cancel",
      updateError: "Failed to update development progress",
    },
    progressCircle: {
      complete: "OK",
    },
  },
  indonesian: {
    common: {
      close: "Tutup",
      cancel: "Batal",
      save: "Simpan",
      saving: "Menyimpan...",
      delete: "Hapus",
      search: "Cari",
      date: "Tanggal",
      brand: "Brand",
      developer: "Developer",
      domain: "Domain",
      content: "Konten",
      title: "Judul",
      description: "Deskripsi",
      note: "Catatan",
      retry: "Coba Lagi",
      remove: "Hapus",
      filter: "Filter",
      details: "Detail",
      progress: "Progres",
      status: "Status",
      hosting: "Hosting",
      gsc: "GSC",
      info: "Info",
      notAvailable: "-",
      open: "Buka",
      name: "Nama",
      created: "Dibuat",
      addedBy: "Ditambahkan Oleh",
      addedOn: "Ditambahkan Pada",
      assignedBy: "Ditugaskan Oleh",
      assignedOn: "Ditugaskan Pada",
      lastUpdated: "Terakhir Diperbarui",
      loading: "Memuat",
      total: "Total",
      words: (count) => `${count} kata`,
      noDescriptionAdded: "Belum ada deskripsi.",
      yes: "Ya",
      no: "Tidak",
      loadingContent: "Memuat konten...",
    },
    statuses: {
      development: {
        new: "Baru",
        "in-progress": "Sedang Dikerjakan",
        completed: "Selesai",
      },
      hosting: {
        "not-hosted": "Belum Hosting",
        hosted: "Sudah Hosting",
      },
      gsc: {
        "not-done": "Belum Selesai",
        done: "Selesai",
      },
      content: {
        ready: "Konten Siap",
        pending: "Konten Belum Lengkap",
      },
    },
    pageBadges: {
      landingPage: { label: "LP", title: "Landing Page" },
      termsAndConditionsPage: { label: "TC", title: "Halaman Syarat & Ketentuan" },
      aboutPage: { label: "AB", title: "Halaman Tentang" },
      contactPage: { label: "CP", title: "Halaman Kontak" },
    },
    page: {
      title: "Pengembangan",
      description:
        "Tugaskan domain brand, periksa konten, dan pantau progres pengembangan, hosting, serta GSC.",
      addDomain: "Tambah Domain",
      info: "Info",
      totalDevelopmentDomains: "Total domain pengembangan",
      searchPlaceholder: "Brand, domain, developer",
      loadError: "Gagal memuat data pengembangan",
      loadingTitle: "Memuat",
      loadingDescription: "Mengambil data pengembangan...",
      addDomainError: "Gagal menambahkan domain",
      addInfoError: "Gagal menambahkan info",
      deleteInfoError: "Gagal menghapus info",
      updateTaskError: "Gagal memperbarui tugas pengembangan",
      saveContentError: "Gagal menyimpan konten",
      updateContentPoolError: "Gagal memperbarui item content pool",
      releaseContentEditorError: "Gagal melepas editor konten",
      noContentPoolSelected: "Tidak ada item Content Pool yang dipilih untuk domain pengembangan ini.",
      openContentPoolError: "Gagal membuka editor Content Pool",
      noContentSelected: "Belum ada konten yang dipilih untuk domain pengembangan ini.",
      assignDomainError: "Gagal menugaskan domain",
      updateDomainError: "Gagal memperbarui domain",
      deleteDomainError: "Gagal menghapus domain",
      overallProgressAria: (progress) => `Buka ringkasan progres keseluruhan (${progress}%)`,
      templatesOnlyTitle: "Template",
      templatesOnlyDescription:
        "Buka pustaka template untuk meninjau atau menambahkan tautan template pengembangan.",
      openTemplates: "Buka Template",
      editContentPool: "Edit Content Pool",
    },
    addDomainForm: {
      title: "Tambah Domain",
      description:
        "Buat data domain siap pengembangan dengan konten dan resource Blogger.",
      brand: "Brand",
      selectBrand: "Pilih brand",
      content: "Konten",
      selectContent: "Pilih Konten",
      changeContent: "Ubah Konten",
      remove: "Hapus",
      selectBrandFirst: "Pilih brand terlebih dahulu untuk memuat konten terkait.",
      readPermissionRequired: "Izin baca Content Pool diperlukan.",
      chooseContentHelp: "Pilih konten untuk dilampirkan ke domain ini.",
      selectedContent: "Konten Terpilih",
      domain: "Domain",
      landingPage: "Landing Page",
      termsAndConditionsPage: "Halaman Syarat & Ketentuan",
      aboutPage: "Halaman Tentang",
      contactPage: "Halaman Kontak",
      domainPlaceholder: "https://example.com",
      landingPagePlaceholder: "https://example.com/landing",
      termsPlaceholder: "https://example.com/terms",
      aboutPlaceholder: "https://example.com/about",
      contactPlaceholder: "https://example.com/contact",
      selectBrandBeforeChoosing: "Pilih brand sebelum memilih konten.",
      contentPoolPermissionRequired:
        "Izin baca Content Pool diperlukan untuk memilih konten.",
      loadBrandContentError: "Gagal memuat konten brand.",
      selectBrandError: "Pilih brand.",
      domainRequired: "Domain wajib diisi.",
      landingRequired: "Landing Page wajib diisi.",
      saveError: "Gagal menambahkan domain pengembangan",
      submit: "Tambah Domain",
      articlePicker: {
        title: "Pilih Konten",
        filteredForBrand: (brandName) => `Konten difilter untuk ${brandName}.`,
        selectBrandFirst: "Pilih brand sebelum memilih konten.",
        contentTitles: "Judul Konten",
        found: (count) => `${count} ditemukan`,
        loading: "Memuat konten...",
        noContentFound: "Tidak ada konten untuk brand ini.",
        selectTitleToPreview: "Pilih judul untuk melihat pratinjau konten lengkap.",
        useContent: "Gunakan Konten",
        cancel: "Batal",
      },
    },
    assignForm: {
      title: "Tugaskan Developer",
      developer: "Developer",
      selectDeveloper: "Pilih developer",
      selectDeveloperError: "Pilih developer.",
      saveError: "Gagal menugaskan developer",
      assigning: "Menugaskan...",
      assign: "Tugaskan",
      cancel: "Batal",
    },
    assignTable: {
      title: "Tabel Penugasan",
      description:
        "Tugaskan domain yang siap ke developer dan periksa kontennya sebelum diteruskan.",
      headers: {
        date: "Tanggal",
        brand: "Brand",
        domain: "Domain",
        content: "Konten",
        contentBy: "Konten Oleh",
        assignedTo: "Ditugaskan Ke",
        edit: "Edit",
        progress: "Progres",
      },
      availablePages: "Halaman tersedia",
      previewSelectedContent: "Pratinjau konten terpilih",
      noContentSelected: "Belum ada konten dipilih",
      contentBeingAddedBy: (name) => `Konten sedang ditambahkan oleh ${name}`,
      contentWasAddedBy: (name) => `Konten ditambahkan oleh ${name}`,
      contentNotAddedYet: "Konten belum ditambahkan",
      assigning: "Menugaskan...",
      assign: "Tugaskan",
      editDomain: "Domain",
      contentPool: "Content Pool",
      contentBeingEditedBy: (name) => `Konten sedang diedit oleh ${name || "pengguna lain"}`,
      editSelectedContentPool: "Edit item Content Pool yang dipilih",
      selectContentInAddDomain: "Pilih konten terlebih dahulu di Tambah Domain",
      empty: "Tidak ada data di tabel",
      assignedDeveloper: (name, count) => `${name} - ${count}`,
    },
    doTable: {
      title: "Tugas Pengembangan",
      description:
        "Pantau pekerjaan developer, status hosting, dan penyelesaian GSC di satu tempat.",
      headers: {
        date: "Tanggal",
        developer: "Developer",
        brand: "Brand",
        domain: "Domain",
        status: "Status",
        hosting: "Hosting",
        gsc: "GSC",
        content: "Konten",
      },
      previewContent: "Pratinjau konten",
      empty: "Tidak ada data di tabel",
      mobileLabels: {
        developer: "Developer",
        domain: "Domain",
        status: "Status",
        hosting: "Hosting",
        gsc: "GSC",
        content: "Konten",
      },
    },
    contentModal: {
      previewTitle: "Pratinjau Konten",
      editTitle: "Tambah Konten",
      close: "Tutup",
      pages: "Halaman",
      clickToCopy: (label) => `Klik untuk menyalin ${String(label || "").toLowerCase()}`,
      copied: (label) => `${label} disalin.`,
      copyTextError: (label) => `Gagal menyalin ${String(label || "").toLowerCase()}.`,
      title: "Judul",
      description: "Deskripsi",
      article: "Artikel",
      articlePlaceholder: "Tulis isi artikel di sini",
      note: "Catatan",
      notePlaceholder: "Tambahkan catatan di sini",
      resources: "Resource",
      logo: "Logo",
      banner: "Banner",
      favicon: "Favicon",
      button: "Tombol",
      resourcePlaceholder: "Tempel tautan gambar di sini",
      noResourceImages: "Tidak ada gambar resource tersedia.",
      copyImageSuccess: "Alamat gambar disalin.",
      copyImageError: "Gagal menyalin alamat gambar.",
      saveError: "Gagal menyimpan konten",
      saveContent: "Simpan Konten",
      cancel: "Batal",
    },
    templatesModal: {
      title: "Info",
      description:
        "Tinjau item info pengembangan yang tersedia dan kelola catatan untuk tim.",
      close: "Tutup",
      name: "Nama",
      notes: "Catatan",
      addInfo: "Tambah Info",
      infoRegistry: "Daftar Info",
      headers: {
        name: "Nama",
        addedBy: "Ditambahkan Oleh",
        created: "Dibuat",
        note: "Catatan",
        action: "Aksi",
      },
      viewNote: "Lihat catatan",
      noNoteAdded: "Belum ada catatan",
      delete: "Hapus",
      empty: "Tidak ada data info tersedia.",
      saveError: "Gagal menambahkan info",
    },
    editDomainForm: {
      title: "Edit Domain",
      description: "Perbarui brand dan URL halaman utama saja.",
      brand: "Brand",
      selectBrand: "Pilih brand",
      domain: "Domain",
      landingPage: "Landing Page",
      termsAndConditionsPage: "Halaman Syarat & Ketentuan",
      aboutPage: "Halaman Tentang",
      contactPage: "Halaman Kontak",
      domainPlaceholder: "https://example.com",
      domainRequired: "Domain wajib diisi.",
      landingRequired: "Landing Page wajib diisi.",
      saveChanges: "Simpan Perubahan",
      deleteDomain: "Hapus Domain",
      cancel: "Batal",
      updateError: "Gagal memperbarui domain",
      deleteError: "Gagal menghapus domain",
      deleteTitle: "Hapus Domain",
      deleteMessage: (domain) => `Hapus ${domain || "domain ini"}? Tindakan ini tidak dapat dibatalkan.`,
    },
    overallProgress: {
      title: "Progres Keseluruhan",
      description: "Tinjau progres masing-masing dengan filter tanggal.",
      close: "Tutup",
      filter: "Filter",
      brand: "Brand",
      allBrands: "Semua brand",
      developer: "Developer",
      allDevelopers: "Semua developer",
      total: "Total",
      totalDomains: (count) => `${count} domain`,
      completed: "Selesai",
      hosted: "Hosted",
      gscDone: "GSC Selesai",
      headers: {
        date: "Tanggal",
        brand: "Brand",
        domain: "Domain",
        developer: "Developer",
        progress: "Progres",
        status: "Status",
        hosting: "Hosting",
        gsc: "GSC",
        details: "Detail",
      },
      openDetailsAria: (domain) => `Buka detail untuk ${domain || "domain ini"}`,
      empty: "Tidak ada data di tabel",
    },
    domainDetails: {
      eyebrow: "Detail Domain",
      closeDetails: "Tutup detail",
      contentReady: "Konten Siap",
      contentPending: "Konten Belum Lengkap",
      ownership: "Kepemilikan",
      addedBy: "Ditambahkan Oleh",
      addedOn: "Ditambahkan Pada",
      assignedBy: "Ditugaskan Oleh",
      assignedOn: "Ditugaskan Pada",
      developer: "Developer",
      notAssigned: "Belum ditugaskan",
      lastUpdated: "Terakhir Diperbarui",
      contentSection: "Konten",
      contentAddedBy: "Konten Ditambahkan Oleh",
      notAddedYet: "Belum ditambahkan",
      contentAddedOn: "Konten Ditambahkan Pada",
      editingBy: "Diedit Oleh",
      noActiveEditor: "Tidak ada editor aktif",
      editingStarted: "Mulai Diedit",
      title: "Judul",
      note: "Catatan",
      buildSetup: "Pengaturan Build",
      info: "Info",
      noInfoSelected: "Belum ada info dipilih",
      infoNotes: "Catatan Info",
      progress: "Progres",
      logos: "Logo",
      buttonsGifs: "Tombol / GIF",
      links: "Tautan",
      landingPage: "Landing Page",
      aboutPage: "Halaman Tentang",
      contactPage: "Halaman Kontak",
      termsPage: "Halaman Syarat",
      heroImage: "Hero Image",
      favicon: "Favicon",
      activityTimeline: "Timeline Aktivitas",
      noActivityHistory: "Belum ada riwayat aktivitas untuk domain ini.",
      timeline: {
        domainAdded: "Domain ditambahkan",
        developmentAssigned: "Pengembangan ditugaskan",
        contentEditingStarted: "Pengeditan konten dimulai",
        contentLockOpened: "Kunci konten dibuka",
        contentSaved: "Konten disimpan",
        contentUpdatedDetail: "Judul, deskripsi, artikel, dan aset diperbarui",
        latestRecordUpdate: "Pembaruan data terakhir",
        noDeveloperAssigned: "Belum ada developer ditugaskan",
        statusDetail: (developmentStatus, hostingStatus, gscStatus) =>
          `Status: ${developmentStatus}, Hosting: ${hostingStatus}, GSC: ${gscStatus}`,
      },
    },
    progressForm: {
      title: "Perbarui Progres",
      template: "Template",
      noInfoSelected: "Belum ada info dipilih",
      progress: "Progres",
      development: "Pengembangan",
      hosting: "Hosting",
      gsc: "GSC",
      saveProgress: "Simpan Progres",
      cancel: "Batal",
      updateError: "Gagal memperbarui progres pengembangan",
    },
    progressCircle: {
      complete: "OK",
    },
  },
};

function humanizeStatus(value) {
  if (!value) {
    return "-";
  }

  return String(value)
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export function normalizeDevelopmentLanguage(value) {
  return value === "indonesian" ? "indonesian" : "english";
}

export function getDevelopmentUiCopy(language) {
  return DEVELOPMENT_UI_COPY[normalizeDevelopmentLanguage(language)];
}

export function getDevelopmentLocale(language) {
  return normalizeDevelopmentLanguage(language) === "indonesian" ? "id-ID" : "en-US";
}

export function getDevelopmentStatusLabel(value, language) {
  const copy = getDevelopmentUiCopy(language);
  return copy.statuses.development?.[value] || humanizeStatus(value);
}

export function getHostingStatusLabel(value, language) {
  const copy = getDevelopmentUiCopy(language);
  return copy.statuses.hosting?.[value] || humanizeStatus(value);
}

export function getGscStatusLabel(value, language) {
  const copy = getDevelopmentUiCopy(language);
  return copy.statuses.gsc?.[value] || humanizeStatus(value);
}
