const SHORT_LINK_CHECKER_UI_COPY = {
  english: {
    common: {
      close: "Close",
      cancel: "Cancel",
      edit: "Edit",
      remove: "Remove",
      refresh: "Refresh",
      refreshing: "Refreshing...",
      save: "Save",
      saving: "Saving...",
      reset: "Reset",
      search: "Search",
      status: "Status",
      active: "Active",
      inactive: "Inactive",
      scanMode: "Scan Mode",
      noBrand: "No Brand",
      noDomain: "No domain",
      noMatchedCode: "No matched code",
      verification: "Verification",
      detectedOnFinalPage: "Detected on final page",
      passwordRequired: "Password Required",
      currentPassword: "Current Password",
      currentPasswordPlaceholder: "Enter your password",
      rows: "Rows",
      previous: "Previous",
      next: "Next",
      unknown: "Unknown",
      statuses: {
        success: "Success",
        error: "Error",
        cloudflare: "Cloudflare",
        securityVerification: "Security verification",
        notChecked: "Not checked",
        sent: "Sent",
        silent: "Silent",
      },
    },
    filters: {
      all: "All",
      success: "Success",
      error: "Error",
      cloudflare: "Cloudflare",
      securityVerification: "Security verification",
      notChecked: "Not checked",
      allLinks: "All links",
      active: "Active",
      inactive: "Inactive",
      captureAndStatus: "Capture + status",
      statusOnly: "Status code only",
    },
    alerts: {
      unavailable: "Unavailable",
    },
    page: {
      badge: "Short Link Monitor",
      title: "Short Link Checker",
      description:
        "Check short links, capture final pages, and send Telegram alerts for selected status codes.",
      autoScheduleOn: "Auto Schedule: On",
      autoSchedule: "Auto Schedule",
      telegram: "Telegram",
      importLinks: "Import Links",
      addShortLink: "Add Short Link",
      checkAll: "Check All",
      checking: "Checking...",
      clearImages: "Clear Images",
      clearing: "Clearing...",
      deleteAllLinks: "Delete All Links",
      deleting: "Deleting...",
      loadErrorFallback: "Failed to load Short Link Checker",
      permissionManage: "You do not have permission to manage short links.",
      permissionImport: "You do not have permission to import short links.",
      importRequiresRows: "Paste at least one short link to import.",
      updateSuccess: "Short link updated.",
      createSuccess: "Short link added.",
      saveError: "Failed to save short link",
      importSuccess: (createdCount, skippedCount) =>
        `Imported ${createdCount || 0} links. ${skippedCount || 0} skipped.`,
      importReviewNotice: (createdCount, skippedCount) =>
        `Imported ${createdCount || 0} links. ${skippedCount || 0} skipped. Review details below.`,
      importError: "Failed to import short links",
      deleteConfirm: (shortUrl) => `Remove ${shortUrl} from Short Link Checker?`,
      deleteSuccess: "Short link removed.",
      deleteError: "Failed to remove short link",
      destructiveLockSchedule: "Stop auto schedule before clearing images or deleting all links.",
      destructiveLockRunning: "Wait until the current short-link check finishes.",
      destructivePasswordRequired: "Enter your current password to continue.",
      clearImagesSuccess: (count) => `Cleared ${count || 0} images.`,
      clearImagesError: "Failed to clear short-link images",
      deleteAllSuccess: (links, checks, files) =>
        `Deleted ${links || 0} short links, ${checks || 0} checks, and ${files || 0} images.`,
      deleteAllError: "Failed to delete all short links",
      stopScheduleBeforeCheckAll: "Stop auto schedule before using Check All.",
      waitForCurrentCheck: "Wait until the current short-link check stops.",
      checkCloudflareNotice: "Short link checked. Cloudflare verification detected.",
      checkSecurityNotice: "Short link checked. Security verification detected.",
      checkErrorNotice: "Short link checked with errors.",
      checkSuccessNotice: "Short link checked.",
      checkError: "Failed to check short link",
      checkAllSuccess: (totalCount, errorCount) =>
        `Checked ${totalCount || 0} short links. ${errorCount || 0} errors found.`,
      checkAllError: "Failed to check all short links",
      telegramSaveSuccess: "Telegram alert settings saved.",
      telegramSaveError: "Failed to save Telegram settings",
      scheduleSaveSuccess: "Short link schedule settings saved.",
      scheduleSaveError: "Failed to save schedule settings",
      scheduleStarted: "Short link schedule started.",
      scheduleStopping: "Short link schedule is stopping. Active checks are closing now.",
      scheduleStopped: "Short link schedule stopped.",
      scheduleUpdateError: "Failed to update schedule",
      nextAt: (value) => `Next at: ${value}`,
      noNextRun: "No next run",
      live: {
        autoSchedule: "Auto schedule",
        running: "Running",
        stopped: "Stopped",
        checkStatus: "Check status",
        progress: "Progress",
        nextCheckIn: "Next check in",
        scanningNow: "Scanning now",
        activeCount: (count) => `${count} active`,
        starting: "Starting",
        idle: "Idle",
        current: (label) => `Current: ${label}`,
        last: (shortUrl, exactStatusCode, finalStatusCode) =>
          `Last: ${shortUrl || "-"} (${exactStatusCode || "-"}/${finalStatusCode || "-"})`,
        stopSchedule: "Stop Schedule",
      },
      table: {
        title: "Short Link Table",
        description: "Status is taken from the exact short link request and the final Playwright destination.",
        total: (count) => `${count} total`,
        loading: "Loading short links...",
        headers: {
          shortLink: "Short Link",
          moneySite: "Money Site",
          shortStatus: "Short Status",
          finalStatus: "Final Status",
          lastCheck: "Last Check",
          telegram: "Telegram",
          actions: "Actions",
        },
        statusOnlyCheck: "Status-only check",
        image: "Image",
        check: "Check",
        edit: "Edit",
        remove: "Remove",
        scanning: "Scanning...",
        checking: "Checking...",
        pagination: (page, totalPages) => `Page ${page} of ${totalPages}`,
        matchingLinks: (count) => `${count} matching links`,
        emptyFiltered: "No short links match the selected filters.",
        empty: "No short links yet.",
      },
      destructive: {
        clearTitle: "Clear Short-Link Images",
        deleteTitle: "Delete All Short Links",
        clearDescription: "This removes all saved short-link check images from server storage.",
        deleteDescription: (count) =>
          `This removes all ${count} short links, their check history, and saved images.`,
        clearButton: "Clear Images",
        deleteButton: "Delete All Links",
        warning:
          "The auto schedule must stay stopped. This action cannot be undone after your password is verified.",
        close: "Close",
        cancel: "Cancel",
        working: "Working...",
      },
    },
    helpers: {
      preparingNextLink: "Preparing next link...",
      noActiveLinkRightNow: "No active link right now.",
      notScheduled: "Not scheduled",
      runningNow: "Running now",
      calculating: "Calculating...",
      starting: "Starting...",
      autoChecking: "Auto checking",
      checking: "Checking",
      completed: "Completed",
      failed: "Failed",
      stopped: "Stopped",
      idle: "Idle",
      queued: "queued",
      zeroQueued: "0 queued",
      stoppedSuffix: (completedCount, totalCount, stoppedCount) =>
        `${completedCount}/${totalCount}, ${stoppedCount} stopped`,
      runningShort: "Running",
      scanModeFileFallback: "short-link",
    },
    filterPanel: {
      badge: "Filters",
      title: "Short Links",
      summary: (shownCount, totalCount) => `Showing ${shownCount} of ${totalCount} matching short links.`,
      searchPlaceholder: "Search link, money site, final URL...",
      stats: {
        active: (count) => `${count} active`,
        checked: (count) => `${count} checked`,
        success: (count) => `${count} success`,
        errors: (count) => `${count} errors`,
        cloudflare: (count) => `${count} cloudflare`,
        verification: (count) => `${count} verification`,
      },
    },
    captureModal: {
      openShortLink: "Open Short Link",
      openFinal: "Open Final",
      openImage: "Open Image",
      download: "Download",
      loadingTitle: "Loading capture...",
      loadingDescription: "The latest image will appear shortly.",
      emptyTitle: "No capture image available",
      emptyDescription: "Run a check and the capture will appear here.",
      shortLinkStatus: "Short-link status",
      finalStatus: "Final status",
      verificationDetected: "Verification detected",
      checkedAt: "Checked",
      telegramCodes: "Telegram codes",
      imageAlt: (value) => `${value || "Short link"} capture`,
    },
    entryModal: {
      editBadge: "Edit",
      addBadge: "Add",
      editTitle: "Edit Short Link",
      addTitle: "Add Short Link",
      description: "Map the short link to a money site when a matching domain is available.",
      nameLabel: "Name",
      namePlaceholder: "Campaign or source name",
      shortLinkLabel: "Short Link",
      assignMoneySite: "Assign Money Site",
      noMoneySite: "No money site",
      moneySiteDomain: "Money Site Domain",
      moneySiteDomainPlaceholder: "example.com",
      note: "Note",
      notePlaceholder: "Optional note",
      activeTitle: "Active for Check All and Auto Schedule",
      activeDescription: "Inactive short links stay saved but will not run in batches.",
      save: "Save Short Link",
      add: "Add Short Link",
      saving: "Saving...",
    },
    importModal: {
      badge: "CSV Import",
      title: "Import Short Links",
      description: "Upload a CSV, review the parsed rows, edit anything needed, then import.",
      columnsTitle: "CSV columns",
      columnsHelp: "Headers are optional. You can edit every parsed row before saving.",
      downloadTemplate: "Download CSV Template",
      fileLabel: "CSV File",
      textLabel: "CSV Text",
      textPlaceholder: "shortUrl,moneySiteDomain,title,note,active",
      noFileSelected: "No file selected",
      rowsReady: (count) => `${count} rows ready`,
      duplicateMatches: (count) => `${count} rows have duplicate exact-domain money-site matches.`,
      resultTitle: "Import result",
      resultSummary: (createdCount, skippedCount) =>
        `${createdCount || 0} imported, ${skippedCount || 0} skipped`,
      rowLabel: (rowNumber) => `Row ${rowNumber}`,
      skipped: "Skipped",
      noShortUrl: "No short URL",
      domain: "Domain",
      name: "Name",
      headers: {
        shortUrl: "Short URL",
        moneySiteDomain: "Money Site Domain",
        moneySiteMatch: "Money Site Match",
        name: "Name",
        note: "Note",
        active: "Active",
      },
      selectOne: (count) => `Select one (${count} exact matches)`,
      useMatchedMoneySite: "Use matched money site",
      noExactMatch: "No exact match",
      duplicateHelp: (count) => `Same domain exists ${count} times. Pick the exact money site/image.`,
      campaignPlaceholder: "Campaign",
      optionalPlaceholder: "Optional",
      remove: "Remove",
      empty: "Upload or paste CSV rows to preview them here.",
      importing: "Importing...",
      importRows: "Import Edited Rows",
    },
    scheduleModal: {
      stopping: "Stopping",
      scheduled: "Scheduled",
      stopped: "Stopped",
      title: "Auto Check Schedule",
      description: "Check active short links, wait the delay, then run again.",
      delayMinutes: "Delay Minutes",
      parallelChecks: "Parallel Checks",
      status: "Status",
      progress: "Progress",
      nextCheck: "Next check",
      lastIssue: "Last issue",
      saveSettings: "Save Settings",
      stopSchedule: "Stop Schedule",
      startSchedule: "Start Schedule",
      startScheduleTitle: "Wait until the current check stops.",
    },
    telegramModal: {
      badge: "Telegram",
      title: "Error Alerts",
      description: "Choose which error codes and verification captures should send Telegram messages.",
      enableAlerts: "Enable Telegram error alerts",
      enableAlertsHelp: "Successful checks never send Telegram messages.",
      sendCloudflareCaptures: "Send Cloudflare verification captures",
      sendCloudflareCapturesHelp:
        "Sends the captured verification image when Cloudflare is detected.",
      sendSecurityCaptures: "Send security verification captures",
      sendSecurityCapturesHelp:
        "Sends the captured image when a bot or security verification page is detected.",
      chatId: "Chat or Group ID",
      botToken: "Bot Token",
      savedTokenPlaceholder: "Saved token kept if blank",
      tokenPlaceholder: "123456:ABC...",
      statusCodeTitle: "Send alerts for these status codes",
      statusCodeSummary: (count) =>
        `${count} selected. Verification toggles run first, then these codes can send a status alert.`,
      common: "Common",
      all: "All",
      addCustomStatusCode: "Add custom status code",
      customStatusCodePlaceholder: "Example: 301",
      shortName: "Short name",
      shortNamePlaceholder: "Redirect",
      addCode: "Add Code",
      remove: "Remove",
      sent: (count) => `${count} sent`,
      failed: (count) => `${count} failed`,
      lastSent: (value) => `Last sent: ${value}`,
      save: "Save Telegram",
      validation: {
        codeRequired: "Enter a status code first.",
        nameRequired: "Add a short name for this status code.",
        invalidCode: "Status code must be between 0 and 599.",
      },
    },
  },
  indonesian: {
    common: {
      close: "Tutup",
      cancel: "Batal",
      edit: "Edit",
      remove: "Hapus",
      refresh: "Muat ulang",
      refreshing: "Memuat...",
      save: "Simpan",
      saving: "Menyimpan...",
      reset: "Reset",
      search: "Cari",
      status: "Status",
      active: "Aktif",
      inactive: "Tidak aktif",
      scanMode: "Mode Pengecekan",
      noBrand: "Tanpa brand",
      noDomain: "Tanpa domain",
      noMatchedCode: "Tidak ada kode yang cocok",
      verification: "Verifikasi",
      detectedOnFinalPage: "Terdeteksi di halaman akhir",
      passwordRequired: "Kata Sandi Diperlukan",
      currentPassword: "Kata Sandi Saat Ini",
      currentPasswordPlaceholder: "Masukkan kata sandi Anda",
      rows: "Baris",
      previous: "Sebelumnya",
      next: "Berikutnya",
      unknown: "Tidak diketahui",
      statuses: {
        success: "Berhasil",
        error: "Error",
        cloudflare: "Cloudflare",
        securityVerification: "Verifikasi keamanan",
        notChecked: "Belum dicek",
        sent: "Terkirim",
        silent: "Diam",
      },
    },
    filters: {
      all: "Semua",
      success: "Berhasil",
      error: "Error",
      cloudflare: "Cloudflare",
      securityVerification: "Verifikasi keamanan",
      notChecked: "Belum dicek",
      allLinks: "Semua link",
      active: "Aktif",
      inactive: "Tidak aktif",
      captureAndStatus: "Capture + status",
      statusOnly: "Hanya kode status",
    },
    alerts: {
      unavailable: "Tidak tersedia",
    },
    page: {
      badge: "Monitor Short Link",
      title: "Pengecek Short Link",
      description:
        "Cek short link, ambil gambar halaman akhir, dan kirim alert Telegram untuk kode status yang dipilih.",
      autoScheduleOn: "Jadwal Otomatis: Aktif",
      autoSchedule: "Jadwal Otomatis",
      telegram: "Telegram",
      importLinks: "Impor Link",
      addShortLink: "Tambah Short Link",
      checkAll: "Cek Semua",
      checking: "Memeriksa...",
      clearImages: "Hapus Gambar",
      clearing: "Menghapus...",
      deleteAllLinks: "Hapus Semua Link",
      deleting: "Menghapus...",
      loadErrorFallback: "Gagal memuat Pengecek Short Link",
      permissionManage: "Anda tidak memiliki izin untuk mengelola short link.",
      permissionImport: "Anda tidak memiliki izin untuk mengimpor short link.",
      importRequiresRows: "Tempel setidaknya satu short link untuk diimpor.",
      updateSuccess: "Short link berhasil diperbarui.",
      createSuccess: "Short link berhasil ditambahkan.",
      saveError: "Gagal menyimpan short link",
      importSuccess: (createdCount, skippedCount) =>
        `Berhasil mengimpor ${createdCount || 0} link. ${skippedCount || 0} dilewati.`,
      importReviewNotice: (createdCount, skippedCount) =>
        `Berhasil mengimpor ${createdCount || 0} link. ${skippedCount || 0} dilewati. Tinjau detail di bawah.`,
      importError: "Gagal mengimpor short link",
      deleteConfirm: (shortUrl) => `Hapus ${shortUrl} dari Pengecek Short Link?`,
      deleteSuccess: "Short link berhasil dihapus.",
      deleteError: "Gagal menghapus short link",
      destructiveLockSchedule: "Hentikan jadwal otomatis sebelum menghapus gambar atau semua link.",
      destructiveLockRunning: "Tunggu sampai pengecekan short link saat ini selesai.",
      destructivePasswordRequired: "Masukkan kata sandi saat ini untuk melanjutkan.",
      clearImagesSuccess: (count) => `Berhasil menghapus ${count || 0} gambar.`,
      clearImagesError: "Gagal menghapus gambar short link",
      deleteAllSuccess: (links, checks, files) =>
        `Berhasil menghapus ${links || 0} short link, ${checks || 0} hasil cek, dan ${files || 0} gambar.`,
      deleteAllError: "Gagal menghapus semua short link",
      stopScheduleBeforeCheckAll: "Hentikan jadwal otomatis sebelum menggunakan Cek Semua.",
      waitForCurrentCheck: "Tunggu sampai pengecekan short link saat ini berhenti.",
      checkCloudflareNotice: "Short link dicek. Verifikasi Cloudflare terdeteksi.",
      checkSecurityNotice: "Short link dicek. Verifikasi keamanan terdeteksi.",
      checkErrorNotice: "Short link dicek dengan error.",
      checkSuccessNotice: "Short link berhasil dicek.",
      checkError: "Gagal mengecek short link",
      checkAllSuccess: (totalCount, errorCount) =>
        `Berhasil mengecek ${totalCount || 0} short link. Ditemukan ${errorCount || 0} error.`,
      checkAllError: "Gagal mengecek semua short link",
      telegramSaveSuccess: "Pengaturan alert Telegram berhasil disimpan.",
      telegramSaveError: "Gagal menyimpan pengaturan Telegram",
      scheduleSaveSuccess: "Pengaturan jadwal short link berhasil disimpan.",
      scheduleSaveError: "Gagal menyimpan pengaturan jadwal",
      scheduleStarted: "Jadwal short link dimulai.",
      scheduleStopping: "Jadwal short link sedang dihentikan. Pengecekan aktif sedang ditutup.",
      scheduleStopped: "Jadwal short link dihentikan.",
      scheduleUpdateError: "Gagal memperbarui jadwal",
      nextAt: (value) => `Berikutnya: ${value}`,
      noNextRun: "Belum ada jadwal berikutnya",
      live: {
        autoSchedule: "Jadwal otomatis",
        running: "Berjalan",
        stopped: "Berhenti",
        checkStatus: "Status pengecekan",
        progress: "Progres",
        nextCheckIn: "Pengecekan berikutnya dalam",
        scanningNow: "Sedang memeriksa",
        activeCount: (count) => `${count} aktif`,
        starting: "Memulai",
        idle: "Idle",
        current: (label) => `Saat ini: ${label}`,
        last: (shortUrl, exactStatusCode, finalStatusCode) =>
          `Terakhir: ${shortUrl || "-"} (${exactStatusCode || "-"}/${finalStatusCode || "-"})`,
        stopSchedule: "Hentikan Jadwal",
      },
      table: {
        title: "Tabel Short Link",
        description: "Status diambil dari permintaan short link yang tepat dan tujuan akhir Playwright.",
        total: (count) => `${count} total`,
        loading: "Memuat short link...",
        headers: {
          shortLink: "Short Link",
          moneySite: "Money Site",
          shortStatus: "Status Short",
          finalStatus: "Status Akhir",
          lastCheck: "Pengecekan Terakhir",
          telegram: "Telegram",
          actions: "Aksi",
        },
        statusOnlyCheck: "Cek hanya status",
        image: "Gambar",
        check: "Cek",
        edit: "Edit",
        remove: "Hapus",
        scanning: "Memeriksa...",
        checking: "Memeriksa...",
        pagination: (page, totalPages) => `Halaman ${page} dari ${totalPages}`,
        matchingLinks: (count) => `${count} link cocok`,
        emptyFiltered: "Tidak ada short link yang cocok dengan filter yang dipilih.",
        empty: "Belum ada short link.",
      },
      destructive: {
        clearTitle: "Hapus Gambar Short Link",
        deleteTitle: "Hapus Semua Short Link",
        clearDescription: "Ini akan menghapus semua gambar hasil cek short link yang tersimpan dari server.",
        deleteDescription: (count) =>
          `Ini akan menghapus semua ${count} short link, riwayat pengecekan, dan gambar yang tersimpan.`,
        clearButton: "Hapus Gambar",
        deleteButton: "Hapus Semua Link",
        warning:
          "Jadwal otomatis harus tetap berhenti. Tindakan ini tidak dapat dibatalkan setelah kata sandi Anda diverifikasi.",
        close: "Tutup",
        cancel: "Batal",
        working: "Memproses...",
      },
    },
    helpers: {
      preparingNextLink: "Menyiapkan link berikutnya...",
      noActiveLinkRightNow: "Tidak ada link aktif saat ini.",
      notScheduled: "Belum dijadwalkan",
      runningNow: "Sedang berjalan",
      calculating: "Menghitung...",
      starting: "Memulai...",
      autoChecking: "Cek otomatis",
      checking: "Memeriksa",
      completed: "Selesai",
      failed: "Gagal",
      stopped: "Berhenti",
      idle: "Idle",
      queued: "dalam antrean",
      zeroQueued: "0 antrean",
      stoppedSuffix: (completedCount, totalCount, stoppedCount) =>
        `${completedCount}/${totalCount}, ${stoppedCount} dihentikan`,
      runningShort: "Berjalan",
      scanModeFileFallback: "short-link",
    },
    filterPanel: {
      badge: "Filter",
      title: "Short Link",
      summary: (shownCount, totalCount) => `Menampilkan ${shownCount} dari ${totalCount} short link yang cocok.`,
      searchPlaceholder: "Cari link, money site, URL akhir...",
      stats: {
        active: (count) => `${count} aktif`,
        checked: (count) => `${count} dicek`,
        success: (count) => `${count} berhasil`,
        errors: (count) => `${count} error`,
        cloudflare: (count) => `${count} cloudflare`,
        verification: (count) => `${count} verifikasi`,
      },
    },
    captureModal: {
      openShortLink: "Buka Short Link",
      openFinal: "Buka Halaman Akhir",
      openImage: "Buka Gambar",
      download: "Unduh",
      loadingTitle: "Memuat hasil tangkapan...",
      loadingDescription: "Gambar terbaru akan segera muncul.",
      emptyTitle: "Belum ada gambar hasil tangkapan",
      emptyDescription: "Jalankan pengecekan dan hasil tangkapan akan tampil di sini.",
      shortLinkStatus: "Status short link",
      finalStatus: "Status akhir",
      verificationDetected: "Verifikasi terdeteksi",
      checkedAt: "Dicek",
      telegramCodes: "Kode Telegram",
      imageAlt: (value) => `Hasil tangkapan ${value || "short link"}`,
    },
    entryModal: {
      editBadge: "Edit",
      addBadge: "Tambah",
      editTitle: "Edit Short Link",
      addTitle: "Tambah Short Link",
      description: "Hubungkan short link ke money site jika domain yang cocok tersedia.",
      nameLabel: "Nama",
      namePlaceholder: "Nama kampanye atau sumber",
      shortLinkLabel: "Short Link",
      assignMoneySite: "Tugaskan Money Site",
      noMoneySite: "Tidak ada money site",
      moneySiteDomain: "Domain Money Site",
      moneySiteDomainPlaceholder: "example.com",
      note: "Catatan",
      notePlaceholder: "Catatan opsional",
      activeTitle: "Aktif untuk Cek Semua dan Jadwal Otomatis",
      activeDescription: "Short link yang tidak aktif tetap tersimpan tetapi tidak akan dijalankan dalam batch.",
      save: "Simpan Short Link",
      add: "Tambah Short Link",
      saving: "Menyimpan...",
    },
    importModal: {
      badge: "Impor CSV",
      title: "Impor Short Link",
      description: "Unggah CSV, tinjau baris yang diparsing, edit jika perlu, lalu impor.",
      columnsTitle: "Kolom CSV",
      columnsHelp: "Header opsional. Anda dapat mengedit setiap baris hasil parsing sebelum menyimpan.",
      downloadTemplate: "Unduh Template CSV",
      fileLabel: "File CSV",
      textLabel: "Teks CSV",
      textPlaceholder: "shortUrl,moneySiteDomain,title,note,active",
      noFileSelected: "Belum ada file dipilih",
      rowsReady: (count) => `${count} baris siap`,
      duplicateMatches: (count) => `${count} baris memiliki kecocokan money site domain yang sama lebih dari satu.`,
      resultTitle: "Hasil impor",
      resultSummary: (createdCount, skippedCount) =>
        `${createdCount || 0} diimpor, ${skippedCount || 0} dilewati`,
      rowLabel: (rowNumber) => `Baris ${rowNumber}`,
      skipped: "Dilewati",
      noShortUrl: "Tidak ada short URL",
      domain: "Domain",
      name: "Nama",
      headers: {
        shortUrl: "Short URL",
        moneySiteDomain: "Domain Money Site",
        moneySiteMatch: "Cocokkan Money Site",
        name: "Nama",
        note: "Catatan",
        active: "Aktif",
      },
      selectOne: (count) => `Pilih satu (${count} kecocokan persis)`,
      useMatchedMoneySite: "Gunakan money site yang cocok",
      noExactMatch: "Tidak ada kecocokan persis",
      duplicateHelp: (count) => `Domain yang sama ada ${count} kali. Pilih money site/gambar yang tepat.`,
      campaignPlaceholder: "Kampanye",
      optionalPlaceholder: "Opsional",
      remove: "Hapus",
      empty: "Unggah atau tempel baris CSV untuk melihat pratinjau di sini.",
      importing: "Mengimpor...",
      importRows: "Impor Baris yang Diedit",
    },
    scheduleModal: {
      stopping: "Menghentikan",
      scheduled: "Terjadwal",
      stopped: "Berhenti",
      title: "Jadwal Cek Otomatis",
      description: "Cek short link aktif, tunggu jeda, lalu jalankan lagi.",
      delayMinutes: "Jeda Menit",
      parallelChecks: "Cek Paralel",
      status: "Status",
      progress: "Progres",
      nextCheck: "Pengecekan berikutnya",
      lastIssue: "Masalah terakhir",
      saveSettings: "Simpan Pengaturan",
      stopSchedule: "Hentikan Jadwal",
      startSchedule: "Mulai Jadwal",
      startScheduleTitle: "Tunggu sampai pengecekan saat ini berhenti.",
    },
    telegramModal: {
      badge: "Telegram",
      title: "Alert Error",
      description: "Pilih kode error dan hasil tangkapan verifikasi mana yang harus mengirim pesan Telegram.",
      enableAlerts: "Aktifkan alert error Telegram",
      enableAlertsHelp: "Pengecekan yang berhasil tidak pernah mengirim pesan Telegram.",
      sendCloudflareCaptures: "Kirim hasil tangkapan verifikasi Cloudflare",
      sendCloudflareCapturesHelp:
        "Mengirim gambar verifikasi yang tertangkap ketika Cloudflare terdeteksi.",
      sendSecurityCaptures: "Kirim hasil tangkapan verifikasi keamanan",
      sendSecurityCapturesHelp:
        "Mengirim gambar hasil tangkapan ketika halaman bot atau verifikasi keamanan terdeteksi.",
      chatId: "ID Chat atau Grup",
      botToken: "Token Bot",
      savedTokenPlaceholder: "Token tersimpan akan tetap digunakan jika dikosongkan",
      tokenPlaceholder: "123456:ABC...",
      statusCodeTitle: "Kirim alert untuk kode status ini",
      statusCodeSummary: (count) =>
        `${count} dipilih. Toggle verifikasi berjalan lebih dulu, lalu kode-kode ini bisa mengirim alert status.`,
      common: "Umum",
      all: "Semua",
      addCustomStatusCode: "Tambah kode status khusus",
      customStatusCodePlaceholder: "Contoh: 301",
      shortName: "Nama singkat",
      shortNamePlaceholder: "Redirect",
      addCode: "Tambah Kode",
      remove: "Hapus",
      sent: (count) => `${count} terkirim`,
      failed: (count) => `${count} gagal`,
      lastSent: (value) => `Terakhir dikirim: ${value}`,
      save: "Simpan Telegram",
      validation: {
        codeRequired: "Masukkan kode status terlebih dahulu.",
        nameRequired: "Tambahkan nama singkat untuk kode status ini.",
        invalidCode: "Kode status harus antara 0 dan 599.",
      },
    },
  },
};

export function normalizeShortLinkCheckerLanguage(value) {
  return value === "indonesian" ? "indonesian" : "english";
}

export function getShortLinkCheckerUiCopy(language) {
  return SHORT_LINK_CHECKER_UI_COPY[normalizeShortLinkCheckerLanguage(language)];
}

export function getShortLinkCheckerLocale(language) {
  return normalizeShortLinkCheckerLanguage(language) === "indonesian" ? "id-ID" : "en-US";
}
