const REPORTING_UI_COPY = {
  english: {
    common: {
      close: "Close",
      cancel: "Cancel",
      save: "Save",
      saving: "Saving...",
      refresh: "Refresh",
      refreshing: "Refreshing...",
      delete: "Delete",
      deleting: "Deleting...",
      edit: "Edit",
      create: "Create",
      update: "Update",
      remove: "Remove",
      search: "Search",
      open: "Open",
      openLink: "Open Link",
      view: "View",
      noPreview: "No preview",
      loadingPreview: "Loading preview...",
      notAvailable: "Not available",
      unknownBrand: "Unknown brand",
      unknownUser: "Unknown user",
      unknownAuthor: "Unknown author",
      unknownReporter: "Unknown reporter",
      unknown: "Unknown",
      none: "None",
      noSubject: "No subject",
      noSmtpSource: "No SMTP source",
      noRecipients: "No recipients",
      noItems: "No items",
      noImage: "No image",
      bytesZero: "0 B",
      copied: "Copied.",
      ddos: "DDOS",
    },
    issueTypes: {
      cloaking: "Cloaking",
      brand_phishing: "Brand Phishing",
      death_phishing: "Death Phishing",
      stray_domain: "Stray Domain",
    },
    taskStatuses: {
      open: "Open",
      in_progress: "In Progress",
      reported: "Reported",
      submitted: "Submitted",
      resolved: "Checked",
    },
    reviewStatuses: {
      checked: "Checked",
      rejected: "Rejected",
      submitted: "Submitted",
    },
    emailStatuses: {
      draft: "Draft",
      sent: "Sent",
      failed: "Failed",
    },
    workflowTones: {
      blue: "Blue",
      amber: "Amber",
      red: "Red",
      slate: "Slate",
    },
    page: {
      title: "Reporting",
      reviewTitle: "Reporting Review",
      backToReporting: "Back To Reporting",
      loadErrorFallback: "Failed to load reporting workflows",
      saveSuccess: "Reporting workflow updated successfully.",
      saveError: "Failed to update reporting workflow",
      loadingWorkflows: "Loading reporting workflows...",
      workflowsTabLabel: "Reporting workflows",
      toolkitTitle: "Investigation Toolkit",
      toolkitDescription:
        "Use these tools to identify hosting providers, capture mobile content, and support phishing lookups.",
      toolkitLinks: [
        { label: "Phish.report (Quick Lookup)", href: "https://phish.report/" },
        { label: "Check-Host.net", href: "https://check-host.net/" },
        { label: "Google AMP Test", href: "https://search.google.com/test/amp" },
        { label: "AcidTool", href: "https://acidtool.com/" },
        { label: "WHOIS Search", href: "https://whois.domaintools.com/redclara.net" },
      ],
      section: {
        editWorkflow: "Edit Workflow",
        workflowFallback: "Workflow",
      },
      workflowEditor: {
        title: (title) => `Edit ${title}`,
        description: "Change the SOP content reporters see for this issue type.",
        sectionTitle: "Section title",
        guideTitle: "Guide title",
        colorTone: "Color tone",
        workflowLabel: "Workflow label",
        badge: "Badge",
        summary: "Summary",
        note: "Note",
        steps: "Steps",
        stepsPlaceholder: "One step per line",
        links: "Links",
        linksPlaceholder: "One link per line in this format: Label | https://example.com",
        saveWorkflow: "Save Workflow",
      },
    },
    workspace: {
      globalDate: (value) => `Global date: ${value}`,
      title: "Reporting Tasks",
      searchPlaceholder: "Search URL, notes, brand",
      totalTasks: (count) => `${count} task${count === 1 ? "" : "s"}`,
      newTask: "New Task",
      listTitle: "Tasks",
      loadingTasks: "Loading tasks...",
      tasksShown: (count) => `${count} task${count === 1 ? "" : "s"} shown`,
      loadingTaskList: "Loading reporting tasks...",
      needsReview: "Needs review",
      rank: (value) => `Rank #${value}`,
      duplicate: (sequence, total) => `Duplicate ${sequence}/${total}`,
      noTasksMatch: "No tasks match the current search and global date.",
      loadingTaskDetails: "Loading task details...",
      reviewLoadError: "This review view could not load the selected reporting task.",
      noTaskAvailable: "No reporting task is available for the current search and global date.",
      copyUrlTitle: "Click to copy URL",
      openUrlTitle: "Open URL in new window",
      copyDetails: "Copy Details",
      editTask: "Edit Task",
      deleteTask: "Delete Task",
      status: "Status",
      createdBy: "Created By",
      ddosRequired: "Required",
      ddosNotRequired: "Not required",
      taskNote: "Task Note",
      reviewOthersWork: "Review Others Work",
      openReviewView: "Open Review View",
      summaryLabels: {
        brand: "Brand",
        issue: "Issue",
        rank: "Rank",
        ddos: "DDOS",
      },
      reviewLaunch: {
        noSubmissions: "No Submissions",
        pending: (count) => `Pending ${count}`,
        needsCheck: (count) => `Needs Check ${count}`,
        allDone: "All Done",
      },
      composer: {
        reportUrlCopied: "Report URL copied.",
        reportUrlCopyError: "Failed to copy URL",
        taskDetailsCopied: "Task details copied.",
        taskDetailsCopyError: "Failed to copy task details",
      },
      taskForm: {
        createTitle: "Create Task",
        editTitle: "Edit Task",
        cardDescription:
          "Keep the task small and assignable. One URL, one issue, one clear reporting target.",
        modalCreateTitle: "Create Reporting Task",
        modalEditTitle: "Edit Reporting Task",
        modalDescription:
          "Save the task first, then open it from the list and upload evidence when you are ready.",
        brand: "Brand",
        selectBrand: "Select brand",
        issueType: "Issue Type",
        url: "URL",
        googleRank: "Google Rank",
        notes: "Notes",
        notesPlaceholder: "Context for the reporter or reviewer",
        ddosRequired: "DDOS required",
        ddosRequiredHelp: "Use this only when the task needs DDOS handling before review.",
        saveTask: "Save Task",
        createTask: "Create Task",
        duplicatePrompt: (url) =>
          `A reporting task already exists for ${url}. Do you want to create another one anyway?`,
        duplicateCancelled: "Task creation was cancelled because this URL already exists.",
        createSuccess: "Reporting task created.",
        updateSuccess: "Reporting task updated.",
        saveError: "Failed to save task",
        deleteConfirm: (url) => `Delete the reporting task for ${url}?`,
        deleteSuccess: "Reporting task deleted.",
        deleteError: "Failed to delete task",
      },
      evidenceDraft: {
        nothingToCopy: "Nothing to copy",
        clipboardUnavailable: "Clipboard is not available",
        failedToReadFile: (name) => `Failed to read ${name}`,
        unsupportedImageFormat: "Unsupported image format",
        openStorageError: "Failed to open evidence draft storage",
        readDraftError: "Failed to read evidence draft",
        saveDraftError: "Failed to save evidence draft",
        deleteDraftError: "Failed to delete evidence draft",
        clearExpiredDraftsError: "Failed to clear expired evidence drafts",
        maxImagesError: (count) => `You can upload up to ${count} images`,
        totalSizeError: "Total image upload size must stay under 10 MB",
        notImageFile: (name) => `${name} is not an image file`,
        maxFileSizeError: (name) => `${name || "Image"} is too large. Max size is 5 MB`,
      },
      evidenceActions: {
        addImagesError: "Failed to add images",
        imagesAdded: (count) => `${count} image${count === 1 ? "" : "s"} added.`,
        pastedImagesAdded: (count) =>
          `${count} pasted image${count === 1 ? "" : "s"} added.`,
        preparingImages: "Preparing images...",
        uploadingEvidence: "Uploading evidence...",
        uploadComplete: "Upload complete",
        updateSuccess: "Evidence updated.",
        submitSuccess: "Evidence submitted for review.",
        saveError: "Failed to save evidence",
        deleteConfirm: "Delete your evidence submission?",
        deleteSuccess: "Evidence deleted.",
        deleteError: "Failed to delete evidence",
        rejectSuccess: "Evidence rejected.",
        rejectError: "Failed to reject evidence",
        markCheckedSuccess: "Submission marked as checked.",
        markCheckedError: "Failed to mark submission as checked",
        reverseCheckedSuccess: "Submission moved back to submitted.",
        reverseCheckedError: "Failed to reverse checked status",
        drivePreviewTitle: (brandName) => `${brandName || "Report"} Drive Evidence`,
      },
      emailActions: {
        aiDraftGenerated: "AI draft generated.",
        aiDraftError: "Failed to generate AI draft",
        draftSaved: "Draft saved.",
        draftSaveError: "Failed to save draft",
        emailSent: "Email sent successfully.",
        emailSendError: "Failed to send email",
      },
    },
    evidenceModal: {
      addTitle: "Add Evidence",
      editTitle: "Edit Evidence",
      description: "Upload images or add a Drive link for this reporting task.",
      googleDriveLink: "Google Drive Link",
      evidenceNotes: "Evidence Notes",
      notesPlaceholder: "Short note for the reviewer",
      ddosCompleted: "DDOS completed",
      ddosCompletedHelp: "Tick this only when DDOS work is already done for the submission.",
      images: "Images",
      imagesCount: (count, maxCount, bytes) => `${count}/${maxCount} images | ${bytes}`,
      helpText: (maxCount, maxBytes) =>
        `Paste screenshots with Ctrl + V. Drafts stay in this browser for up to 1 day until submit. Limit: ${maxCount} images, ${maxBytes} total.`,
      uploadPhaseFallback: "Uploading evidence...",
      dragDropTitle: "Drag and drop images here",
      dragDropHint: "or click to browse",
      loadingPreview: "Loading preview...",
      noPreview: "No preview",
      readyToUpload: "Ready to upload",
      fileName: "File Name",
      renamePlaceholder: "Rename image",
      nameChanged: "Name changed",
      noImages: "No images added yet.",
      updateEvidence: "Update Evidence",
      submitEvidence: "Submit Evidence",
    },
    evidencePanel: {
      title: "My Evidence",
      checked: "Checked",
      rejected: "Rejected",
      submitted: "Submitted",
      openAiEmail: "Open AI Email",
      openEmailComposer: "Open Email Composer",
      openEmail: "Open Email",
      editEvidence: "Edit Evidence",
      addEvidence: "Add Evidence",
      deleteEvidence: "Delete Evidence",
      images: "Images",
      storage: "Storage",
      deletedImages: "Deleted Images",
      updated: "Updated",
      reviewed: "Reviewed",
      completed: "Completed",
      notMarked: "Not marked",
      reviewerComment: "Reviewer Comment",
      updateAndSubmitAgain: "Please update and submit again",
      previewDrive: "Preview Drive",
      imageCount: (count) => `${count} image${count === 1 ? "" : "s"}`,
      deletedImageCount: (count) => `${count} image${count === 1 ? "" : "s"}`,
      emailCount: (count) => `${count} email${count === 1 ? "" : "s"}`,
      evidenceNotes: "Evidence Notes",
      deletedEvidenceHistory: "Deleted Evidence History",
      unnamedImage: "Unnamed image",
      deletedBy: (name, date, size) => `Deleted by ${name || "Admin"} on ${date} (${size})`,
      moreDeletedRecords: (count) => `+${count} more deleted image records`,
      noImagesUploaded: "No images uploaded yet.",
      noEvidenceAdded: "No evidence added yet.",
      emailActivityTitle: "Email Activity",
    },
    reviewPanel: {
      reviewAndEmail: "Review and Email",
      email: "Email",
      emailCount: (count) => `${count} email${count === 1 ? "" : "s"}`,
      submissions: "Submissions",
      pending: "Pending",
      checked: "Checked",
      rejected: "Rejected",
      imageCount: (count) => `${count} image${count === 1 ? "" : "s"}`,
      selectSubmission: "Select a submission to review.",
      noEvidenceSubmitted: "No evidence has been submitted for this task yet.",
    },
    reviewSwitcher: {
      summaryLabelFallback: "Current global date filter",
      reportsCount: (count) => `${count} report${count === 1 ? "" : "s"}`,
      currentReport: "Current Report",
      selectReport: "Select report",
      otherReports: "Other reports",
      viewing: "Viewing",
    },
    submissionCard: {
      selectedSubmission: "Selected submission",
      markUnchecked: "Mark Unchecked",
      updating: "Updating...",
      reject: "Reject",
      rejecting: "Rejecting...",
      markChecked: "Mark Checked",
      images: "Images",
      storage: "Storage",
      deletedImages: "Deleted Images",
      updated: "Updated",
      reviewed: "Reviewed",
      completed: "Completed",
      notMarked: "Not marked",
      reviewerComment: "Reviewer Comment",
      evidenceRejected: "Evidence rejected",
      driveLink: "Drive Link",
      previewDrive: "Preview Drive",
      imageCount: (count) => `${count} image${count === 1 ? "" : "s"}`,
      deletedImageCount: (count) => `${count} image${count === 1 ? "" : "s"}`,
      evidenceNotes: "Evidence Notes",
      deletedEvidenceHistory: "Deleted Evidence History",
      unnamedImage: "Unnamed image",
      deletedBy: (name, date, size) => `Deleted by ${name || "Admin"} on ${date} (${size})`,
      moreDeletedRecords: (count) => `+${count} more deleted image records`,
      openGallery: "Open Gallery",
      loadingPreview: "Loading preview...",
      previewUnavailable: "Preview unavailable",
      noImagesUploaded: "No images uploaded for this submission.",
      emailTitle: "Selected User Email",
    },
    rejectModal: {
      title: "Reject Evidence",
      description: (name) => `${name || "Reporter"} will see this comment and can re-upload.`,
      comment: "Rejection Comment",
      placeholder: "Tell the reporter what should be fixed or re-uploaded",
      submit: "Reject Evidence",
    },
    emailActivity: {
      title: "Email Activity",
      fullView: "Full View",
      chooseEmail: "Choose email",
      itemCount: (count) => `${count} item${count === 1 ? "" : "s"}`,
      openSelected: "Open selected",
      openEmail: "Open email",
      modalTitleFallback: "Email Activity",
      modalSingleDescription: "Full email details for this activity.",
      modalMultiDescription: (count) => `${count} emails available. Pick one from the list.`,
      myEmail: "My email",
      toLabel: "To:",
      showDetails: "Show Details",
      hideDetails: "Hide Details",
      from: "From",
      to: "To",
      cc: "CC",
      bcc: "BCC",
      author: "Author",
      sent: "Sent",
      additionalNotes: "Additional Notes",
      savedWithThisEmail: "Saved with this email",
      noEmailBody: "No email body available.",
      noPreviewAvailable: "No preview available.",
    },
    aiModal: {
      typeEmailAndPressSpace: "Type email and press space",
      addAnotherEmail: "Add another email",
      invalidEmail: (value) => `Invalid email address: ${value}`,
      removeRecipient: (value) => `Remove ${value}`,
      onlyImageFiles: "Only image files can be inserted inline.",
      inlineImageTooLarge: (name) =>
        `${name} is too large. Please use an image smaller than 10 MB.`,
      inlineImageInsertError: "Failed to insert inline image.",
      attachmentTooLarge: (name) =>
        `${name} is too large. Please use files smaller than 10 MB.`,
      addAttachmentError: "Failed to add attachment.",
      aiComposerTitle: "AI Email Composer",
      composerTitle: "Email Composer",
      aiComposerDescription:
        "Compose the mail like a mailbox: generate the draft, format the message, place inline images in the body, and attach files before sending.",
      composerDescription:
        "Compose the mail like a mailbox, format the message, place inline images in the body, and attach files before sending.",
      brand: "Brand",
      issueType: "Issue Type",
      url: "URL",
      rank: "Rank",
      sendWith: "Send With",
      noSharedProfile: "No shared SMTP profile available",
      sendWithHelp:
        "Only SMTP profiles relevant to this report are shown here. Brand-linked shared profiles stay limited to their matching brand.",
      fromEmail: "From Email",
      selectSmtpProfile: "Select an SMTP profile",
      noSmtpProfileSelected: "No SMTP profile selected",
      mailSource: (value) => `Mail Source: ${value}`,
      senderAppearsHere: "The selected SMTP profile sender will appear here.",
      emailSending: "Email Sending",
      sendPermissionDisabled: "Send permission not enabled",
      sendPermissionDescription:
        "You can still prepare and save the draft here, but sending mail is disabled for your account.",
      sendTo: "Send To",
      recipientHelp:
        "Press space, comma, tab, or enter to add each email address as a separate recipient.",
      emailSubject: "Email Subject",
      emailSubjectPlaceholder: "Urgent Abuse Report - Potential Phishing Content",
      ccPlaceholder: "Type CC email and press space",
      ccHelp: "CC recipients will receive a visible copy of this email.",
      bccPlaceholder: "Type BCC email and press space",
      bccHelp: "BCC recipients stay hidden from other recipients.",
      additionalNotesForAi: "Additional Notes For AI",
      additionalNotes: "Additional Notes",
      aiNotesPlaceholder:
        "Add host details, cloaking observations, recipients to mention, or anything else the AI should include.",
      notesPlaceholder: "Add any extra notes you want to keep with this manual email draft.",
      generating: "Generating...",
      generateContent: "Generate Content",
      aiDisabled:
        "AI generation is not enabled for your account. You can still compose the email manually.",
      addAttachment: "Add Attachment",
      insertInlineImage: "Insert Inline Image",
      emailBody: "Email Body",
      emailBodyPlaceholder:
        "Write the email body here. Images inserted here will appear inside the sent email.",
      emailBodyHelp:
        "Images inserted into the editor are embedded inside the email body. Files added through attachments are sent separately.",
      attachments: "Attachments",
      remove: "Remove",
      aiDraft: "AI Draft",
      applyToEditor: "Apply To Editor",
      generatedSubject: "Generated Subject",
      generateToSeeDraft: "Generate content to see the AI draft here.",
      aiDraftDisabled: "AI draft generation is disabled for your account.",
      emailPreview: "Email Preview",
      livePreview: "Live preview",
      waitingForContent: "Waiting for content",
      smtpProfile: "SMTP Profile",
      from: "From",
      to: "To",
      addRecipientEmails: "Add recipient emails",
      noCcRecipients: "No CC recipients",
      subject: "Subject",
      addSubjectLine: "Add a subject line",
      previewEmpty:
        "Start typing or apply the AI draft to see the final email layout here.",
      composerStatus: "Composer Status",
      draftReady: "Draft ready",
      bodyEmpty: "Body is empty",
      draftReadyDescription:
        "You can keep editing the rich body, inline images, and attachments before saving or sending.",
      bodyEmptyDescription:
        "Generate or type the body before saving or sending the email.",
      noSmtpSelectedYet: "No SMTP profile selected yet.",
      fromAddress: (value) => `From ${value}`,
      pickSmtpProfile: "Pick an SMTP profile to load the sender email.",
      sendingDisabled: "Sending is disabled for your account right now.",
      attachmentsReady: (count) => `${count} attachment${count === 1 ? "" : "s"} ready`,
      savingDraft: "Saving Draft...",
      updateDraft: "Update Draft",
      saveDraft: "Save Draft",
      sending: "Sending...",
      sendEmail: "Send Email",
    },
    drivePreview: {
      submittedTimeUnavailable: "Submitted time unavailable",
      folderDescription:
        "Browse the shared Drive folder in a responsive gallery view. Click any visible item inside the gallery to inspect it individually.",
      fileDescription:
        "Preview the submitted Drive file directly inside the reporting workspace as an individual item.",
      normalView: "Normal View",
      largeView: "Large View",
      openInDrive: "Open in Drive",
      copyLink: "Copy Link",
      previewType: "Preview type",
      driveFolder: "Drive folder",
      driveFile: "Drive file",
      folderHelp:
        "Folder links open as a gallery. Individual images or files can be opened from inside the embedded Drive view when the folder sharing allows it.",
      fileHelp:
        "This link opens as a direct file preview, which works well for individual screenshots and other single evidence files.",
      reporter: "Reporter",
      googleDriveLink: "Google Drive link",
      submissionNotes: "Submission notes",
      ddosStatus: "DDOS status",
      ddosCompleted: "DDOS completed",
      ddosNotCompleted: "DDOS not completed",
      galleryPreview: "Gallery preview",
      largeFilePreview: "Large file preview",
      exitLargeView: "Exit Large View",
      openLargeView: "Open Large View",
    },
    gallery: {
      close: "Close",
      zoomOut: "Zoom Out",
      zoomIn: "Zoom In",
      reset: "Reset",
      fullScreen: "Full Screen",
      exitFullScreen: "Exit Full Screen",
      previousImage: "Previous image",
      nextImage: "Next image",
      prev: "Prev",
      next: "Next",
      previewUnavailable: "Preview unavailable",
      imageFallback: "Image",
      of: (current, total) => `${current} of ${total}`,
    },
    settings: {
      statusGeminiNeeded: "Gemini key needed",
      statusGeminiNeededDetail:
        "Your own Gemini key must be saved before AI email generation can work.",
      statusAiReady: "AI ready",
      statusAiReadyDetail:
        "Your Gemini key is saved and AI email generation is available for your account.",
      loadSettingsError: "Failed to load reporting settings",
      loadStorageError: "Failed to load image storage summary",
      saveSuccess: "Reporting settings saved successfully.",
      saveError: "Failed to save reporting settings",
      cleanupDateRequired: "Choose a cleanup date before deleting images.",
      cleanupPasswordRequired: "Admin password is required for image cleanup.",
      cleanupConfirmationRequired: "Type DELETE to confirm reporting image cleanup.",
      cleanupConfirmPrompt: (date) =>
        `Download a zip backup and delete all reporting images on or before ${date}?`,
      cleanupSuccess: (deletedCount, deletedBytes, submissionCount) =>
        `Downloaded backup and deleted ${deletedCount || 0} image${
          Number(deletedCount || 0) === 1 ? "" : "s"
        } (${deletedBytes}) from ${submissionCount || 0} submission${
          Number(submissionCount || 0) === 1 ? "" : "s"
        }.`,
      cleanupError: "Failed to export and delete reporting images",
      trigger: "Reporting Settings",
      title: "Reporting Settings",
      descriptionAll:
        "Manage your AI settings and handle reporting evidence image cleanup from one place.",
      descriptionStorage:
        "Review reporting image storage and run global cleanup with backup export.",
      descriptionPersonal:
        "Save your own Gemini API key and choose the language used for reporting AI generation.",
      settingsTabs: "Settings tabs",
      personalSettings: "Personal Settings",
      reportingImageStorage: "Reporting Image Storage",
      loadingSettings: "Loading reporting settings...",
      reportingLanguage: "Reporting Language",
      indonesian: "Indonesian",
      english: "English",
      language: "Language",
      languageHelp: "AI-generated reporting emails will use this language.",
      geminiApiKey: "Gemini API Key",
      saved: "Saved",
      notSaved: "Not saved",
      yourGeminiKey: "Your Gemini Key",
      keepSavedGeminiKey: "Leave blank to keep your saved Gemini key",
      enterGeminiKey: "Enter your Gemini API key",
      geminiHelp:
        "Only your own saved Gemini key is used for AI email generation.",
      saveSettings: "Save Settings",
      loadingStorageSummary: "Loading image storage summary...",
      imageCount: (count) => `${count} images`,
      totalImages: "Total Images",
      totalStorage: "Total Storage",
      olderThanDays: (days) => `Older Than ${days || 5} Days`,
      olderStorage: "Older Storage",
      selectedDateImages: "Selected Date Images",
      selectedDateStorage: "Selected Date Storage",
      cleanupScope: "Cleanup Scope",
      cleanupScopeDescription:
        "Default cleanup shows images older than 5 days. You can choose any date, including recent dates, and the system will first export a zip backup before deleting the matching images.",
      deleteImagesOnOrBefore: "Delete Images On Or Before",
      olderThanDefault: (days, date, size) =>
        `Older-than-${days || 5}-days default: ${date}. Selected preview size: ${size}.`,
      adminPassword: "Admin Password",
      adminPasswordPlaceholder: "Enter admin password",
      adminPasswordHelp: "Required privilege verification before cleanup.",
      typeDeleteToConfirm: "Type DELETE To Confirm",
      deletePlaceholder: "DELETE",
      confirmHelp: "Second verification step to prevent accidental deletion.",
      affectedSubmissions: "Affected Submissions",
      oldestSelected: "Oldest Selected",
      newestSelected: "Newest Selected",
      refreshStorage: "Refresh Storage",
      preparingZipAndDeleting: "Preparing Zip & Deleting...",
      downloadZipAndDelete: "Download Zip & Delete Images",
    },
    mailProfiles: {
      untitled: "Untitled SMTP",
      loadError: "Failed to load reporting SMTP profiles",
      createSharedSuccess: "Shared SMTP profile created successfully.",
      createPersonalSuccess: "Your SMTP profile created successfully.",
      updateSharedSuccess: "Shared SMTP profile updated successfully.",
      updatePersonalSuccess: "Your SMTP profile updated successfully.",
      saveSharedError: "Failed to save reporting SMTP profile",
      savePersonalError: "Failed to save your SMTP profile",
      deleteSharedSuccess: "SMTP profile deleted successfully.",
      deletePersonalSuccess: "Your SMTP profile deleted successfully.",
      deleteSharedError: "Failed to delete reporting SMTP profile",
      deletePersonalError: "Failed to delete your SMTP profile",
      testSent: (recipients) => `Test email sent to ${recipients}.`,
      testError: "Failed to send SMTP test email",
      trigger: "SMTP Profiles",
      title: "Reporting SMTP Profiles",
      description:
        "Create your own SMTP profiles for reporting mail. Admins can also manage shared profiles for brands and team-wide identities.",
      myProfilesTab: "My SMTP Profiles",
      sharedProfilesTab: "Shared SMTP Profiles",
      personalNote:
        "New personal SMTP profiles start with `mail.200m.website`, port `587`, and `200M Team` already filled in so you can set up faster.",
      loading: "Loading SMTP profiles...",
      sharedProfiles: "Shared Profiles",
      myProfiles: "My Profiles",
      configured: (count) => `${count} configured`,
      newSharedProfile: "New Shared Profile",
      newMyProfile: "New My Profile",
      active: "Active",
      inactive: "Inactive",
      shared: "Shared",
      brandDefault: "Brand Default",
      globalDefault: "Global Default",
      personal: "Personal",
      noSharedProfiles: "No shared SMTP profiles created yet.",
      noPersonalProfiles: "No personal SMTP profiles created yet.",
      createSharedTitle: "Create Shared SMTP Profile",
      createPersonalTitle: "Create Your SMTP Profile",
      editSharedTitle: "Edit Shared SMTP Profile",
      editPersonalTitle: "Edit Your SMTP Profile",
      profileName: "Profile Name",
      sharedNamePlaceholder: "Google Abuse",
      personalNamePlaceholder: "My Mail.200M",
      brandLink: "Brand Link",
      noBrand: "No brand (shared custom name)",
      smtpUser: "SMTP User",
      personalUserPlaceholder: "accounts@200m.website",
      sharedUserPlaceholder: "accounts@example.com",
      smtpHost: "SMTP Host",
      smtpPort: "SMTP Port",
      hostPlaceholder: "mail.200m.website",
      portPlaceholder: "587",
      mailFrom: "Mail From",
      sharedFromPlaceholder: "Brand Protection <accounts@example.com>",
      personalFromPlaceholder: "200M Team",
      smtpPassword: "SMTP Password",
      keepSavedPassword: "Leave blank to keep the saved password",
      enterSmtpPassword: "Enter the SMTP password",
      useAsBrandDefault: "Use as brand default",
      useAsBrandDefaultHelp: "Automatically selected for reports of this brand.",
      useAsGlobalDefault: "Use as global default",
      useAsGlobalDefaultHelp:
        "Fallback default when a report has no brand-specific SMTP profile.",
      profileIsActive: "Profile is active",
      sharedActiveHelp: "Only active profiles are available to reporters.",
      personalActiveHelp:
        "Only active personal SMTP profiles will appear in your AI email composer.",
      testEmail: "Test Email",
      savedProfile: "Saved profile",
      saveFirst: "Save first",
      sendTestTo: "Send test to",
      testPlaceholder: "qa@example.com",
      sending: "Sending...",
      sendTestMail: "Send Test Mail",
      deleteProfile: "Delete Profile",
      createProfile: "Create Profile",
      saveChanges: "Save Changes",
    },
  },
  indonesian: {
    common: {
      close: "Tutup",
      cancel: "Batal",
      save: "Simpan",
      saving: "Menyimpan...",
      refresh: "Muat ulang",
      refreshing: "Memuat...",
      delete: "Hapus",
      deleting: "Menghapus...",
      edit: "Edit",
      create: "Buat",
      update: "Perbarui",
      remove: "Hapus",
      search: "Cari",
      open: "Buka",
      openLink: "Buka Link",
      view: "Lihat",
      noPreview: "Tidak ada pratinjau",
      loadingPreview: "Memuat pratinjau...",
      notAvailable: "Tidak tersedia",
      unknownBrand: "Brand tidak diketahui",
      unknownUser: "Pengguna tidak diketahui",
      unknownAuthor: "Penulis tidak diketahui",
      unknownReporter: "Pelapor tidak diketahui",
      unknown: "Tidak diketahui",
      none: "Tidak ada",
      noSubject: "Tanpa subjek",
      noSmtpSource: "Tanpa sumber SMTP",
      noRecipients: "Tidak ada penerima",
      noItems: "Tidak ada item",
      noImage: "Tidak ada gambar",
      bytesZero: "0 B",
      copied: "Berhasil disalin.",
      ddos: "DDOS",
    },
    issueTypes: {
      cloaking: "Cloaking",
      brand_phishing: "Phishing Brand",
      death_phishing: "Death Phishing",
      stray_domain: "Domain Liar",
    },
    taskStatuses: {
      open: "Open",
      in_progress: "Dalam Progres",
      reported: "Dilaporkan",
      submitted: "Dikirim",
      resolved: "Diperiksa",
    },
    reviewStatuses: {
      checked: "Diperiksa",
      rejected: "Ditolak",
      submitted: "Dikirim",
    },
    emailStatuses: {
      draft: "Draft",
      sent: "Terkirim",
      failed: "Gagal",
    },
    workflowTones: {
      blue: "Biru",
      amber: "Amber",
      red: "Merah",
      slate: "Abu-abu",
    },
    page: {
      title: "Pelaporan",
      reviewTitle: "Tinjauan Pelaporan",
      backToReporting: "Kembali Ke Pelaporan",
      loadErrorFallback: "Gagal memuat alur kerja pelaporan",
      saveSuccess: "Alur kerja pelaporan berhasil diperbarui.",
      saveError: "Gagal memperbarui alur kerja pelaporan",
      loadingWorkflows: "Memuat alur kerja pelaporan...",
      workflowsTabLabel: "Alur kerja pelaporan",
      toolkitTitle: "Toolkit Investigasi",
      toolkitDescription:
        "Gunakan alat-alat ini untuk mengidentifikasi penyedia hosting, menangkap konten seluler, dan membantu pencarian phishing.",
      toolkitLinks: [
        { label: "Phish.report (Pencarian Cepat)", href: "https://phish.report/" },
        { label: "Check-Host.net", href: "https://check-host.net/" },
        { label: "Tes AMP Google", href: "https://search.google.com/test/amp" },
        { label: "AcidTool", href: "https://acidtool.com/" },
        { label: "Pencarian WHOIS", href: "https://whois.domaintools.com/redclara.net" },
      ],
      section: {
        editWorkflow: "Edit Alur Kerja",
        workflowFallback: "Alur Kerja",
      },
      workflowEditor: {
        title: (title) => `Edit ${title}`,
        description: "Ubah konten SOP yang dilihat pelapor untuk jenis isu ini.",
        sectionTitle: "Judul bagian",
        guideTitle: "Judul panduan",
        colorTone: "Warna tema",
        workflowLabel: "Label alur kerja",
        badge: "Badge",
        summary: "Ringkasan",
        note: "Catatan",
        steps: "Langkah",
        stepsPlaceholder: "Satu langkah per baris",
        links: "Link",
        linksPlaceholder: "Satu link per baris dengan format: Label | https://example.com",
        saveWorkflow: "Simpan Alur Kerja",
      },
    },
    workspace: {
      globalDate: (value) => `Tanggal global: ${value}`,
      title: "Tugas Pelaporan",
      searchPlaceholder: "Cari URL, catatan, brand",
      totalTasks: (count) => `${count} tugas`,
      newTask: "Tugas Baru",
      listTitle: "Tugas",
      loadingTasks: "Memuat tugas...",
      tasksShown: (count) => `${count} tugas ditampilkan`,
      loadingTaskList: "Memuat tugas pelaporan...",
      needsReview: "Perlu ditinjau",
      rank: (value) => `Peringkat #${value}`,
      duplicate: (sequence, total) => `Duplikat ${sequence}/${total}`,
      noTasksMatch: "Tidak ada tugas yang cocok dengan pencarian dan tanggal global saat ini.",
      loadingTaskDetails: "Memuat detail tugas...",
      reviewLoadError: "Tampilan tinjauan ini tidak dapat memuat tugas pelaporan yang dipilih.",
      noTaskAvailable: "Tidak ada tugas pelaporan untuk pencarian dan tanggal global saat ini.",
      copyUrlTitle: "Klik untuk menyalin URL",
      openUrlTitle: "Buka URL di jendela baru",
      copyDetails: "Salin Detail",
      editTask: "Edit Tugas",
      deleteTask: "Hapus Tugas",
      status: "Status",
      createdBy: "Dibuat Oleh",
      ddosRequired: "Diperlukan",
      ddosNotRequired: "Tidak diperlukan",
      taskNote: "Catatan Tugas",
      reviewOthersWork: "Tinjau Pekerjaan Orang Lain",
      openReviewView: "Buka Tampilan Tinjauan",
      summaryLabels: {
        brand: "Brand",
        issue: "Isu",
        rank: "Peringkat",
        ddos: "DDOS",
      },
      reviewLaunch: {
        noSubmissions: "Belum Ada Kiriman",
        pending: (count) => `Tertunda ${count}`,
        needsCheck: (count) => `Perlu Dicek ${count}`,
        allDone: "Selesai Semua",
      },
      composer: {
        reportUrlCopied: "URL laporan berhasil disalin.",
        reportUrlCopyError: "Gagal menyalin URL",
        taskDetailsCopied: "Detail tugas berhasil disalin.",
        taskDetailsCopyError: "Gagal menyalin detail tugas",
      },
      taskForm: {
        createTitle: "Buat Tugas",
        editTitle: "Edit Tugas",
        cardDescription:
          "Buat tugas tetap ringkas dan mudah ditugaskan. Satu URL, satu isu, satu target pelaporan yang jelas.",
        modalCreateTitle: "Buat Tugas Pelaporan",
        modalEditTitle: "Edit Tugas Pelaporan",
        modalDescription:
          "Simpan tugas terlebih dahulu, lalu buka dari daftar dan unggah bukti saat Anda siap.",
        brand: "Brand",
        selectBrand: "Pilih brand",
        issueType: "Jenis Isu",
        url: "URL",
        googleRank: "Peringkat Google",
        notes: "Catatan",
        notesPlaceholder: "Konteks untuk pelapor atau peninjau",
        ddosRequired: "DDOS diperlukan",
        ddosRequiredHelp:
          "Gunakan ini hanya jika tugas memerlukan penanganan DDOS sebelum ditinjau.",
        saveTask: "Simpan Tugas",
        createTask: "Buat Tugas",
        duplicatePrompt: (url) =>
          `Tugas pelaporan untuk ${url} sudah ada. Apakah Anda ingin tetap membuat tugas lain?`,
        duplicateCancelled: "Pembuatan tugas dibatalkan karena URL ini sudah ada.",
        createSuccess: "Tugas pelaporan berhasil dibuat.",
        updateSuccess: "Tugas pelaporan berhasil diperbarui.",
        saveError: "Gagal menyimpan tugas",
        deleteConfirm: (url) => `Hapus tugas pelaporan untuk ${url}?`,
        deleteSuccess: "Tugas pelaporan berhasil dihapus.",
        deleteError: "Gagal menghapus tugas",
      },
      evidenceDraft: {
        nothingToCopy: "Tidak ada yang dapat disalin",
        clipboardUnavailable: "Clipboard tidak tersedia",
        failedToReadFile: (name) => `Gagal membaca ${name}`,
        unsupportedImageFormat: "Format gambar tidak didukung",
        openStorageError: "Gagal membuka penyimpanan draft bukti",
        readDraftError: "Gagal membaca draft bukti",
        saveDraftError: "Gagal menyimpan draft bukti",
        deleteDraftError: "Gagal menghapus draft bukti",
        clearExpiredDraftsError: "Gagal membersihkan draft bukti yang kedaluwarsa",
        maxImagesError: (count) => `Anda dapat mengunggah hingga ${count} gambar`,
        totalSizeError: "Total ukuran unggahan gambar harus di bawah 10 MB",
        notImageFile: (name) => `${name} bukan file gambar`,
        maxFileSizeError: (name) => `${name || "Gambar"} terlalu besar. Ukuran maksimum 5 MB`,
      },
      evidenceActions: {
        addImagesError: "Gagal menambahkan gambar",
        imagesAdded: (count) => `${count} gambar ditambahkan.`,
        pastedImagesAdded: (count) => `${count} gambar tempel ditambahkan.`,
        preparingImages: "Menyiapkan gambar...",
        uploadingEvidence: "Mengunggah bukti...",
        uploadComplete: "Unggahan selesai",
        updateSuccess: "Bukti berhasil diperbarui.",
        submitSuccess: "Bukti berhasil dikirim untuk ditinjau.",
        saveError: "Gagal menyimpan bukti",
        deleteConfirm: "Hapus kiriman bukti Anda?",
        deleteSuccess: "Bukti berhasil dihapus.",
        deleteError: "Gagal menghapus bukti",
        rejectSuccess: "Bukti berhasil ditolak.",
        rejectError: "Gagal menolak bukti",
        markCheckedSuccess: "Kiriman berhasil ditandai sudah diperiksa.",
        markCheckedError: "Gagal menandai kiriman sebagai sudah diperiksa",
        reverseCheckedSuccess: "Kiriman dipindahkan kembali ke status dikirim.",
        reverseCheckedError: "Gagal membatalkan status sudah diperiksa",
        drivePreviewTitle: (brandName) => `Bukti Drive ${brandName || "Laporan"}`,
      },
      emailActions: {
        aiDraftGenerated: "Draft AI berhasil dibuat.",
        aiDraftError: "Gagal membuat draft AI",
        draftSaved: "Draft berhasil disimpan.",
        draftSaveError: "Gagal menyimpan draft",
        emailSent: "Email berhasil dikirim.",
        emailSendError: "Gagal mengirim email",
      },
    },
    evidenceModal: {
      addTitle: "Tambah Bukti",
      editTitle: "Edit Bukti",
      description: "Unggah gambar atau tambahkan link Drive untuk tugas pelaporan ini.",
      googleDriveLink: "Link Google Drive",
      evidenceNotes: "Catatan Bukti",
      notesPlaceholder: "Catatan singkat untuk peninjau",
      ddosCompleted: "DDOS selesai",
      ddosCompletedHelp: "Centang hanya jika pekerjaan DDOS sudah selesai untuk kiriman ini.",
      images: "Gambar",
      imagesCount: (count, maxCount, bytes) => `${count}/${maxCount} gambar | ${bytes}`,
      helpText: (maxCount, maxBytes) =>
        `Tempel screenshot dengan Ctrl + V. Draft tersimpan di browser ini hingga 1 hari sampai dikirim. Batas: ${maxCount} gambar, total ${maxBytes}.`,
      uploadPhaseFallback: "Mengunggah bukti...",
      dragDropTitle: "Seret dan jatuhkan gambar di sini",
      dragDropHint: "atau klik untuk memilih",
      loadingPreview: "Memuat pratinjau...",
      noPreview: "Tidak ada pratinjau",
      readyToUpload: "Siap diunggah",
      fileName: "Nama File",
      renamePlaceholder: "Ubah nama gambar",
      nameChanged: "Nama diubah",
      noImages: "Belum ada gambar ditambahkan.",
      updateEvidence: "Perbarui Bukti",
      submitEvidence: "Kirim Bukti",
    },
    evidencePanel: {
      title: "Bukti Saya",
      checked: "Diperiksa",
      rejected: "Ditolak",
      submitted: "Dikirim",
      openAiEmail: "Buka Email AI",
      openEmailComposer: "Buka Penyusun Email",
      openEmail: "Buka Email",
      editEvidence: "Edit Bukti",
      addEvidence: "Tambah Bukti",
      deleteEvidence: "Hapus Bukti",
      images: "Gambar",
      storage: "Penyimpanan",
      deletedImages: "Gambar Dihapus",
      updated: "Diperbarui",
      reviewed: "Ditinjau",
      completed: "Selesai",
      notMarked: "Belum ditandai",
      reviewerComment: "Komentar Peninjau",
      updateAndSubmitAgain: "Silakan perbarui dan kirim lagi",
      previewDrive: "Pratinjau Drive",
      imageCount: (count) => `${count} gambar`,
      deletedImageCount: (count) => `${count} gambar`,
      emailCount: (count) => `${count} email`,
      evidenceNotes: "Catatan Bukti",
      deletedEvidenceHistory: "Riwayat Bukti Dihapus",
      unnamedImage: "Gambar tanpa nama",
      deletedBy: (name, date, size) =>
        `Dihapus oleh ${name || "Admin"} pada ${date} (${size})`,
      moreDeletedRecords: (count) => `+${count} data gambar terhapus lainnya`,
      noImagesUploaded: "Belum ada gambar diunggah.",
      noEvidenceAdded: "Belum ada bukti ditambahkan.",
      emailActivityTitle: "Aktivitas Email",
    },
    reviewPanel: {
      reviewAndEmail: "Tinjau dan Email",
      email: "Email",
      emailCount: (count) => `${count} email`,
      submissions: "Kiriman",
      pending: "Tertunda",
      checked: "Diperiksa",
      rejected: "Ditolak",
      imageCount: (count) => `${count} gambar`,
      selectSubmission: "Pilih kiriman untuk ditinjau.",
      noEvidenceSubmitted: "Belum ada bukti yang dikirim untuk tugas ini.",
    },
    reviewSwitcher: {
      summaryLabelFallback: "Filter tanggal global saat ini",
      reportsCount: (count) => `${count} laporan`,
      currentReport: "Laporan Saat Ini",
      selectReport: "Pilih laporan",
      otherReports: "Laporan lain",
      viewing: "Sedang dilihat",
    },
    submissionCard: {
      selectedSubmission: "Kiriman terpilih",
      markUnchecked: "Tandai Belum Diperiksa",
      updating: "Memperbarui...",
      reject: "Tolak",
      rejecting: "Menolak...",
      markChecked: "Tandai Sudah Diperiksa",
      images: "Gambar",
      storage: "Penyimpanan",
      deletedImages: "Gambar Dihapus",
      updated: "Diperbarui",
      reviewed: "Ditinjau",
      completed: "Selesai",
      notMarked: "Belum ditandai",
      reviewerComment: "Komentar Peninjau",
      evidenceRejected: "Bukti ditolak",
      driveLink: "Link Drive",
      previewDrive: "Pratinjau Drive",
      imageCount: (count) => `${count} gambar`,
      deletedImageCount: (count) => `${count} gambar`,
      evidenceNotes: "Catatan Bukti",
      deletedEvidenceHistory: "Riwayat Bukti Dihapus",
      unnamedImage: "Gambar tanpa nama",
      deletedBy: (name, date, size) =>
        `Dihapus oleh ${name || "Admin"} pada ${date} (${size})`,
      moreDeletedRecords: (count) => `+${count} data gambar terhapus lainnya`,
      openGallery: "Buka Galeri",
      loadingPreview: "Memuat pratinjau...",
      previewUnavailable: "Pratinjau tidak tersedia",
      noImagesUploaded: "Belum ada gambar yang diunggah untuk kiriman ini.",
      emailTitle: "Email Pengguna Terpilih",
    },
    rejectModal: {
      title: "Tolak Bukti",
      description: (name) => `${name || "Pelapor"} akan melihat komentar ini dan dapat mengunggah ulang.`,
      comment: "Komentar Penolakan",
      placeholder: "Beritahu pelapor apa yang harus diperbaiki atau diunggah ulang",
      submit: "Tolak Bukti",
    },
    emailActivity: {
      title: "Aktivitas Email",
      fullView: "Tampilan Penuh",
      chooseEmail: "Pilih email",
      itemCount: (count) => `${count} item`,
      openSelected: "Buka pilihan",
      openEmail: "Buka email",
      modalTitleFallback: "Aktivitas Email",
      modalSingleDescription: "Detail email lengkap untuk aktivitas ini.",
      modalMultiDescription: (count) => `${count} email tersedia. Pilih salah satu dari daftar.`,
      myEmail: "Email saya",
      toLabel: "Ke:",
      showDetails: "Tampilkan Detail",
      hideDetails: "Sembunyikan Detail",
      from: "Dari",
      to: "Ke",
      cc: "CC",
      bcc: "BCC",
      author: "Penulis",
      sent: "Terkirim",
      additionalNotes: "Catatan Tambahan",
      savedWithThisEmail: "Disimpan bersama email ini",
      noEmailBody: "Tidak ada isi email.",
      noPreviewAvailable: "Tidak ada pratinjau.",
    },
    aiModal: {
      typeEmailAndPressSpace: "Ketik email lalu tekan spasi",
      addAnotherEmail: "Tambah email lain",
      invalidEmail: (value) => `Alamat email tidak valid: ${value}`,
      removeRecipient: (value) => `Hapus ${value}`,
      onlyImageFiles: "Hanya file gambar yang dapat disisipkan secara inline.",
      inlineImageTooLarge: (name) =>
        `${name} terlalu besar. Gunakan gambar yang lebih kecil dari 10 MB.`,
      inlineImageInsertError: "Gagal menyisipkan gambar inline.",
      attachmentTooLarge: (name) =>
        `${name} terlalu besar. Gunakan file yang lebih kecil dari 10 MB.`,
      addAttachmentError: "Gagal menambahkan lampiran.",
      aiComposerTitle: "Penyusun Email AI",
      composerTitle: "Penyusun Email",
      aiComposerDescription:
        "Susun email seperti kotak masuk: buat draft, format pesan, tempatkan gambar inline di isi email, dan tambahkan lampiran sebelum mengirim.",
      composerDescription:
        "Susun email seperti kotak masuk, format pesan, tempatkan gambar inline di isi email, dan tambahkan lampiran sebelum mengirim.",
      brand: "Brand",
      issueType: "Jenis Isu",
      url: "URL",
      rank: "Peringkat",
      sendWith: "Kirim Dengan",
      noSharedProfile: "Tidak ada profil SMTP bersama yang tersedia",
      sendWithHelp:
        "Hanya profil SMTP yang relevan dengan laporan ini yang ditampilkan di sini. Profil bersama yang terkait brand tetap dibatasi ke brand yang sesuai.",
      fromEmail: "Email Pengirim",
      selectSmtpProfile: "Pilih profil SMTP",
      noSmtpProfileSelected: "Belum ada profil SMTP dipilih",
      mailSource: (value) => `Sumber Mail: ${value}`,
      senderAppearsHere: "Pengirim dari profil SMTP yang dipilih akan muncul di sini.",
      emailSending: "Pengiriman Email",
      sendPermissionDisabled: "Izin kirim belum diaktifkan",
      sendPermissionDescription:
        "Anda tetap bisa menyiapkan dan menyimpan draft di sini, tetapi pengiriman email dinonaktifkan untuk akun Anda.",
      sendTo: "Kirim Ke",
      recipientHelp:
        "Tekan spasi, koma, tab, atau enter untuk menambahkan setiap alamat email sebagai penerima terpisah.",
      emailSubject: "Subjek Email",
      emailSubjectPlaceholder: "Laporan Penyalahgunaan Mendesak - Potensi Konten Phishing",
      ccPlaceholder: "Ketik email CC lalu tekan spasi",
      ccHelp: "Penerima CC akan menerima salinan email yang terlihat.",
      bccPlaceholder: "Ketik email BCC lalu tekan spasi",
      bccHelp: "Penerima BCC tetap tersembunyi dari penerima lain.",
      additionalNotesForAi: "Catatan Tambahan Untuk AI",
      additionalNotes: "Catatan Tambahan",
      aiNotesPlaceholder:
        "Tambahkan detail host, pengamatan cloaking, penerima yang perlu disebut, atau hal lain yang perlu dimasukkan AI.",
      notesPlaceholder:
        "Tambahkan catatan tambahan yang ingin Anda simpan bersama draft email manual ini.",
      generating: "Membuat...",
      generateContent: "Buat Konten",
      aiDisabled:
        "Pembuatan AI tidak diaktifkan untuk akun Anda. Anda tetap bisa menyusun email secara manual.",
      addAttachment: "Tambah Lampiran",
      insertInlineImage: "Sisipkan Gambar Inline",
      emailBody: "Isi Email",
      emailBodyPlaceholder:
        "Tulis isi email di sini. Gambar yang disisipkan di sini akan muncul di dalam email yang dikirim.",
      emailBodyHelp:
        "Gambar yang disisipkan ke editor akan tertanam di dalam isi email. File yang ditambahkan melalui lampiran akan dikirim terpisah.",
      attachments: "Lampiran",
      remove: "Hapus",
      aiDraft: "Draft AI",
      applyToEditor: "Terapkan Ke Editor",
      generatedSubject: "Subjek Hasil AI",
      generateToSeeDraft: "Buat konten untuk melihat draft AI di sini.",
      aiDraftDisabled: "Pembuatan draft AI dinonaktifkan untuk akun Anda.",
      emailPreview: "Pratinjau Email",
      livePreview: "Pratinjau langsung",
      waitingForContent: "Menunggu konten",
      smtpProfile: "Profil SMTP",
      from: "Dari",
      to: "Ke",
      addRecipientEmails: "Tambahkan email penerima",
      noCcRecipients: "Tidak ada penerima CC",
      subject: "Subjek",
      addSubjectLine: "Tambahkan baris subjek",
      previewEmpty:
        "Mulai mengetik atau terapkan draft AI untuk melihat tata letak email akhir di sini.",
      composerStatus: "Status Penyusun",
      draftReady: "Draft siap",
      bodyEmpty: "Isi email kosong",
      draftReadyDescription:
        "Anda dapat terus mengedit isi rich text, gambar inline, dan lampiran sebelum menyimpan atau mengirim.",
      bodyEmptyDescription:
        "Buat atau ketik isi email sebelum menyimpan atau mengirim email.",
      noSmtpSelectedYet: "Belum ada profil SMTP dipilih.",
      fromAddress: (value) => `Dari ${value}`,
      pickSmtpProfile: "Pilih profil SMTP untuk memuat email pengirim.",
      sendingDisabled: "Pengiriman dinonaktifkan untuk akun Anda saat ini.",
      attachmentsReady: (count) => `${count} lampiran siap`,
      savingDraft: "Menyimpan Draft...",
      updateDraft: "Perbarui Draft",
      saveDraft: "Simpan Draft",
      sending: "Mengirim...",
      sendEmail: "Kirim Email",
    },
    drivePreview: {
      submittedTimeUnavailable: "Waktu kirim tidak tersedia",
      folderDescription:
        "Telusuri folder Drive bersama dalam tampilan galeri yang responsif. Klik item yang terlihat di dalam galeri untuk memeriksanya satu per satu.",
      fileDescription:
        "Pratinjau file Drive yang dikirim langsung di ruang kerja pelaporan sebagai item tunggal.",
      normalView: "Tampilan Normal",
      largeView: "Tampilan Besar",
      openInDrive: "Buka di Drive",
      copyLink: "Salin Link",
      previewType: "Jenis pratinjau",
      driveFolder: "Folder Drive",
      driveFile: "File Drive",
      folderHelp:
        "Link folder dibuka sebagai galeri. Gambar atau file individual dapat dibuka dari tampilan Drive yang disematkan jika izin berbagi folder mengizinkannya.",
      fileHelp:
        "Link ini dibuka sebagai pratinjau file langsung, yang cocok untuk screenshot individual dan file bukti tunggal lainnya.",
      reporter: "Pelapor",
      googleDriveLink: "Link Google Drive",
      submissionNotes: "Catatan kiriman",
      ddosStatus: "Status DDOS",
      ddosCompleted: "DDOS selesai",
      ddosNotCompleted: "DDOS belum selesai",
      galleryPreview: "Pratinjau galeri",
      largeFilePreview: "Pratinjau file besar",
      exitLargeView: "Keluar Tampilan Besar",
      openLargeView: "Buka Tampilan Besar",
    },
    gallery: {
      close: "Tutup",
      zoomOut: "Perkecil",
      zoomIn: "Perbesar",
      reset: "Reset",
      fullScreen: "Layar Penuh",
      exitFullScreen: "Keluar Layar Penuh",
      previousImage: "Gambar sebelumnya",
      nextImage: "Gambar berikutnya",
      prev: "Sebelumnya",
      next: "Berikutnya",
      previewUnavailable: "Pratinjau tidak tersedia",
      imageFallback: "Gambar",
      of: (current, total) => `${current} dari ${total}`,
    },
    settings: {
      statusGeminiNeeded: "Kunci Gemini diperlukan",
      statusGeminiNeededDetail:
        "Kunci Gemini milik Anda sendiri harus disimpan sebelum pembuatan email AI dapat bekerja.",
      statusAiReady: "AI siap",
      statusAiReadyDetail:
        "Kunci Gemini Anda sudah disimpan dan pembuatan email AI tersedia untuk akun Anda.",
      loadSettingsError: "Gagal memuat pengaturan pelaporan",
      loadStorageError: "Gagal memuat ringkasan penyimpanan gambar",
      saveSuccess: "Pengaturan pelaporan berhasil disimpan.",
      saveError: "Gagal menyimpan pengaturan pelaporan",
      cleanupDateRequired: "Pilih tanggal pembersihan sebelum menghapus gambar.",
      cleanupPasswordRequired: "Kata sandi admin diperlukan untuk pembersihan gambar.",
      cleanupConfirmationRequired: "Ketik DELETE untuk mengonfirmasi pembersihan gambar pelaporan.",
      cleanupConfirmPrompt: (date) =>
        `Unduh cadangan zip dan hapus semua gambar pelaporan pada atau sebelum ${date}?`,
      cleanupSuccess: (deletedCount, deletedBytes, submissionCount) =>
        `Cadangan berhasil diunduh dan ${deletedCount || 0} gambar (${deletedBytes}) dari ${
          submissionCount || 0
        } kiriman berhasil dihapus.`,
      cleanupError: "Gagal mengekspor dan menghapus gambar pelaporan",
      trigger: "Pengaturan Pelaporan",
      title: "Pengaturan Pelaporan",
      descriptionAll:
        "Kelola pengaturan AI Anda dan lakukan pembersihan gambar bukti pelaporan dari satu tempat.",
      descriptionStorage:
        "Tinjau penyimpanan gambar pelaporan dan jalankan pembersihan global dengan ekspor cadangan.",
      descriptionPersonal:
        "Simpan kunci Gemini API Anda sendiri dan pilih bahasa yang digunakan untuk pembuatan AI pelaporan.",
      settingsTabs: "Tab pengaturan",
      personalSettings: "Pengaturan Pribadi",
      reportingImageStorage: "Penyimpanan Gambar Pelaporan",
      loadingSettings: "Memuat pengaturan pelaporan...",
      reportingLanguage: "Bahasa Pelaporan",
      indonesian: "Indonesia",
      english: "Inggris",
      language: "Bahasa",
      languageHelp: "Email pelaporan yang dibuat AI akan menggunakan bahasa ini.",
      geminiApiKey: "Kunci API Gemini",
      saved: "Tersimpan",
      notSaved: "Belum tersimpan",
      yourGeminiKey: "Kunci Gemini Anda",
      keepSavedGeminiKey: "Biarkan kosong untuk memakai kunci Gemini yang tersimpan",
      enterGeminiKey: "Masukkan kunci API Gemini Anda",
      geminiHelp:
        "Hanya kunci Gemini milik Anda sendiri yang digunakan untuk pembuatan email AI.",
      saveSettings: "Simpan Pengaturan",
      loadingStorageSummary: "Memuat ringkasan penyimpanan gambar...",
      imageCount: (count) => `${count} gambar`,
      totalImages: "Total Gambar",
      totalStorage: "Total Penyimpanan",
      olderThanDays: (days) => `Lebih Lama Dari ${days || 5} Hari`,
      olderStorage: "Penyimpanan Lama",
      selectedDateImages: "Gambar Pada Tanggal Dipilih",
      selectedDateStorage: "Penyimpanan Pada Tanggal Dipilih",
      cleanupScope: "Cakupan Pembersihan",
      cleanupScopeDescription:
        "Pembersihan default menampilkan gambar yang lebih lama dari 5 hari. Anda dapat memilih tanggal apa pun, termasuk tanggal terbaru, dan sistem akan mengekspor cadangan zip sebelum menghapus gambar yang cocok.",
      deleteImagesOnOrBefore: "Hapus Gambar Pada Atau Sebelum",
      olderThanDefault: (days, date, size) =>
        `Default lebih-lama-dari-${days || 5}-hari: ${date}. Ukuran pratinjau terpilih: ${size}.`,
      adminPassword: "Kata Sandi Admin",
      adminPasswordPlaceholder: "Masukkan kata sandi admin",
      adminPasswordHelp: "Verifikasi hak akses diperlukan sebelum pembersihan.",
      typeDeleteToConfirm: "Ketik DELETE Untuk Konfirmasi",
      deletePlaceholder: "DELETE",
      confirmHelp: "Langkah verifikasi kedua untuk mencegah penghapusan tidak sengaja.",
      affectedSubmissions: "Kiriman Terdampak",
      oldestSelected: "Tertua Terpilih",
      newestSelected: "Terbaru Terpilih",
      refreshStorage: "Muat Ulang Penyimpanan",
      preparingZipAndDeleting: "Menyiapkan Zip & Menghapus...",
      downloadZipAndDelete: "Unduh Zip & Hapus Gambar",
    },
    mailProfiles: {
      untitled: "SMTP Tanpa Judul",
      loadError: "Gagal memuat profil SMTP pelaporan",
      createSharedSuccess: "Profil SMTP bersama berhasil dibuat.",
      createPersonalSuccess: "Profil SMTP Anda berhasil dibuat.",
      updateSharedSuccess: "Profil SMTP bersama berhasil diperbarui.",
      updatePersonalSuccess: "Profil SMTP Anda berhasil diperbarui.",
      saveSharedError: "Gagal menyimpan profil SMTP pelaporan",
      savePersonalError: "Gagal menyimpan profil SMTP Anda",
      deleteSharedSuccess: "Profil SMTP berhasil dihapus.",
      deletePersonalSuccess: "Profil SMTP Anda berhasil dihapus.",
      deleteSharedError: "Gagal menghapus profil SMTP pelaporan",
      deletePersonalError: "Gagal menghapus profil SMTP Anda",
      testSent: (recipients) => `Email uji berhasil dikirim ke ${recipients}.`,
      testError: "Gagal mengirim email uji SMTP",
      trigger: "Profil SMTP",
      title: "Profil SMTP Pelaporan",
      description:
        "Buat profil SMTP Anda sendiri untuk email pelaporan. Admin juga dapat mengelola profil bersama untuk brand dan identitas tim.",
      myProfilesTab: "Profil SMTP Saya",
      sharedProfilesTab: "Profil SMTP Bersama",
      personalNote:
        "Profil SMTP pribadi baru dimulai dengan `mail.200m.website`, port `587`, dan `200M Team` yang sudah terisi agar Anda dapat menyiapkan lebih cepat.",
      loading: "Memuat profil SMTP...",
      sharedProfiles: "Profil Bersama",
      myProfiles: "Profil Saya",
      configured: (count) => `${count} dikonfigurasi`,
      newSharedProfile: "Profil Bersama Baru",
      newMyProfile: "Profil Saya Baru",
      active: "Aktif",
      inactive: "Tidak aktif",
      shared: "Bersama",
      brandDefault: "Default Brand",
      globalDefault: "Default Global",
      personal: "Pribadi",
      noSharedProfiles: "Belum ada profil SMTP bersama dibuat.",
      noPersonalProfiles: "Belum ada profil SMTP pribadi dibuat.",
      createSharedTitle: "Buat Profil SMTP Bersama",
      createPersonalTitle: "Buat Profil SMTP Anda",
      editSharedTitle: "Edit Profil SMTP Bersama",
      editPersonalTitle: "Edit Profil SMTP Anda",
      profileName: "Nama Profil",
      sharedNamePlaceholder: "Google Abuse",
      personalNamePlaceholder: "My Mail.200M",
      brandLink: "Tautan Brand",
      noBrand: "Tanpa brand (nama bersama kustom)",
      smtpUser: "Pengguna SMTP",
      personalUserPlaceholder: "accounts@200m.website",
      sharedUserPlaceholder: "accounts@example.com",
      smtpHost: "Host SMTP",
      smtpPort: "Port SMTP",
      hostPlaceholder: "mail.200m.website",
      portPlaceholder: "587",
      mailFrom: "Mail From",
      sharedFromPlaceholder: "Brand Protection <accounts@example.com>",
      personalFromPlaceholder: "200M Team",
      smtpPassword: "Kata Sandi SMTP",
      keepSavedPassword: "Biarkan kosong untuk mempertahankan kata sandi tersimpan",
      enterSmtpPassword: "Masukkan kata sandi SMTP",
      useAsBrandDefault: "Gunakan sebagai default brand",
      useAsBrandDefaultHelp: "Dipilih otomatis untuk laporan brand ini.",
      useAsGlobalDefault: "Gunakan sebagai default global",
      useAsGlobalDefaultHelp:
        "Default cadangan ketika laporan tidak memiliki profil SMTP khusus brand.",
      profileIsActive: "Profil aktif",
      sharedActiveHelp: "Hanya profil aktif yang tersedia untuk pelapor.",
      personalActiveHelp:
        "Hanya profil SMTP pribadi aktif yang akan muncul di penyusun email AI Anda.",
      testEmail: "Email Uji",
      savedProfile: "Profil tersimpan",
      saveFirst: "Simpan dulu",
      sendTestTo: "Kirim uji ke",
      testPlaceholder: "qa@example.com",
      sending: "Mengirim...",
      sendTestMail: "Kirim Email Uji",
      deleteProfile: "Hapus Profil",
      createProfile: "Buat Profil",
      saveChanges: "Simpan Perubahan",
    },
  },
};

export function normalizeReportingLanguage(value) {
  return value === "indonesian" ? "indonesian" : "english";
}

export function getReportingUiCopy(language) {
  return REPORTING_UI_COPY[normalizeReportingLanguage(language)];
}

export function getReportingLocale(language) {
  return normalizeReportingLanguage(language) === "indonesian" ? "id-ID" : "en-US";
}

export function getReportingIssueLabel(issueType, language) {
  const copy = getReportingUiCopy(language);
  return copy.issueTypes?.[issueType] || issueType || copy.common.unknown;
}

export function getReportingTaskStatusLabel(status, language) {
  const copy = getReportingUiCopy(language);
  return copy.taskStatuses?.[status] || status || copy.taskStatuses.open;
}

export function getReportingReviewStatusLabel(status, language) {
  const copy = getReportingUiCopy(language);
  return copy.reviewStatuses?.[status] || copy.reviewStatuses.submitted;
}

export function getReportingEmailStatusLabel(status, language) {
  const copy = getReportingUiCopy(language);
  return copy.emailStatuses?.[status] || copy.emailStatuses.draft;
}

export function getReportingToneLabel(tone, language) {
  const copy = getReportingUiCopy(language);
  return copy.workflowTones?.[tone] || tone || copy.workflowTones.blue;
}
