const LP_SERVERS_UI_COPY = {
  english: {
    common: {
      close: "Close",
      cancel: "Cancel",
      save: "Save",
      saving: "Saving...",
      delete: "Delete",
      working: "Working...",
      edit: "Edit",
      create: "Create",
      search: "Search",
      loading: "Loading...",
      copied: (label) => `${label} copied successfully.`,
      copyEmpty: (label) => `${label} is empty.`,
      copyFailed: (label) => `Failed to copy ${String(label || "").toLowerCase()}.`,
      fetchPasswordError: "Failed to fetch password.",
      passwordNotReceived: "Password not received from server.",
      passwordMask: "........",
      openResourceImage: "Open resource image",
      notAvailable: "-",
    },
    page: {
      title: "LP Servers",
      description:
        "Manage landing page hosting credentials, server IPs, and import or export access-controlled records.",
      importCsv: "Import CSV",
      exportCsv: "Export CSV",
      exporting: "Exporting...",
      createServer: "Create Server",
      matchingServers: "Matching servers",
      loadError: "Failed to load LP servers",
      updateSuccess: "LP Server updated successfully.",
      createSuccess: "LP Server created successfully.",
      saveError: "Failed to save LP server",
      deleteSuccess: "LP Server deleted successfully.",
      deleteError: "Failed to delete LP server",
      exportError: "Failed to export LP servers CSV",
      editPermissionError: "You do not have permission to edit.",
      deletePermissionError: "You do not have permission to delete.",
      deleteTitle: "Delete LP Server",
      deleteConfirm: (url) => `Delete ${url}? This action cannot be undone.`,
      loadingTitle: "Loading",
      loadingDescription: "Fetching servers...",
    },
    form: {
      titleCreate: "Create Server",
      titleEdit: "Edit Server",
      requiredError: "Brand, URL, Username, and Password are required.",
      brand: "Brand",
      selectBrand: "Select Brand",
      brandFixedHelp: "Brand is fixed for existing LP server records.",
      brandHelp: "Choose the brand that owns this LP server record.",
      url: "URL",
      urlPlaceholder: "https://example.com",
      urlHelp: "Paste the full landing page URL. `https://` is added automatically if missing.",
      serverIp: "Server IP",
      serverIpPlaceholder: "203.0.113.10",
      serverIpHelp: "Optional. Leave this blank if the server IP is not available yet.",
      username: "Username",
      usernamePlaceholder: "server-admin",
      usernameHelp: "Enter the username used to access the server, panel, or hosting account.",
      password: "Password",
      passwordPlaceholder: "Current password",
      passwordLoading: "Loading...",
      passwordHelp: "Store the current password used for this server or hosting login.",
      showPassword: "Show password",
      hidePassword: "Hide password",
      note: "Note",
      notePlaceholder: "Optional internal note",
      noteHelp: "Optional internal note for reminders, access details, or hosting context.",
      save: "Save",
      cancel: "Cancel",
    },
    table: {
      copyHint: "Click the URL, Server IP, Username, or Password values to copy them.",
      searchPlaceholder: "Brand, URL, Server IP, Username",
      headers: {
        brand: "Brand",
        url: "URL",
        serverIp: "Server IP",
        username: "Username",
        password: "Password",
        note: "Note",
        actions: "Actions",
      },
      openUrlTitle: "Open URL in new tab",
      copyUrlTitle: "Click to copy URL",
      copyServerIpTitle: "Click to copy server IP",
      copyUsernameTitle: "Click to copy username",
      copyPasswordTitle: "Click to copy password",
      loadingPassword: "Loading...",
      edit: "Edit",
      delete: "Delete",
      empty: "No LP servers found.",
    },
    importPage: {
      title: "Import LP Servers",
      noPermission: "You do not have permission to import LP server records.",
      backToList: "Back to LP Servers",
    },
    importForm: {
      title: "Import LP Servers",
      uploadTitle: "Upload CSV",
      uploadDescription:
        "Upload a CSV file or paste CSV text to preview new, updated, unchanged, and invalid LP server rows before importing. Existing records are matched by Brand.",
      hideCsvView: "Hide CSV View",
      showCsvView: "Show CSV View",
      downloadTemplate: "Download Template",
      chooseFile: "Choose CSV file",
      fileHelp: "Use the export format: Brand, URL, Server IP, Username, Password, Note.",
      csvContent: "CSV content",
      noCsvLoaded: "No CSV content loaded yet",
      loadedLines: (count) => `Loaded ${count} non-empty line${count === 1 ? "" : "s"}`,
      csvReady: "CSV content is ready for preview.",
      csvHidden: "CSV editor is hidden.",
      templatePreview: "Template preview",
      templateLines: (count) => `Sample template with ${count} non-empty line${count === 1 ? "" : "s"}`,
      templateHidden: "Template preview is hidden.",
      importPreview: "Import Preview",
      checkingRows: "Checking CSV rows...",
      uploadToPreview: "Upload CSV content to generate an import preview.",
      readyCount: (count) => `Ready: ${count}`,
      filteredCount: (count) => `Filtered: ${count}`,
      importAction: "Import LP Servers",
      cards: {
        ready: "Ready To Apply",
        new: "New",
        update: "Update",
        unchanged: "Unchanged",
        invalid: "Invalid",
      },
      searchPreview: "Search preview",
      searchPlaceholder: "Brand, URL, Server IP, Username, Note",
      all: "All",
      ready: "Ready",
      resetPreviewFilters: "Reset preview filters",
      tableHeaders: {
        row: "Row",
        incoming: "Incoming Server",
        current: "Current Record",
        difference: "Difference",
        result: "Result",
      },
      rowLabel: (rowNumber) => `Row ${rowNumber}`,
      incoming: "Incoming",
      current: "Current",
      noExistingRecord: "No existing record",
      needsCorrection: "Needs correction",
      rowWillBeApplied: "This row will be applied.",
      rowWillNotChange: "This row will not change existing data.",
      noRowsMatch: "No rows match the current preview filters.",
      confirmTitle: "Confirm Import",
      confirmDescription:
        "Review the summary below and confirm before importing LP server rows from this CSV.",
      reviewedConfirmation:
        "I reviewed the import preview and want to import these LP server changes.",
      importing: "Importing...",
      importResult: (createdCount, updatedCount, skippedCount) =>
        `Imported ${createdCount || 0} new LP server${(createdCount || 0) === 1 ? "" : "s"}, updated ${updatedCount || 0} existing server${(updatedCount || 0) === 1 ? "" : "s"}, and skipped ${skippedCount || 0} row${(skippedCount || 0) === 1 ? "" : "s"}.`,
      summary: (summary = {}) =>
        `${summary.actionableCount || 0} ready, ${summary.newCount || 0} new, ${summary.updateCount || 0} updates, ${summary.unchangedCount || 0} unchanged, ${summary.invalidCount || 0} invalid.`,
      previewError: "Failed to preview LP server CSV import",
      readFileError: "Failed to read the CSV file.",
      csvRequired: "CSV content is required.",
      waitForPreview: "Please wait until the preview finishes.",
      noValidRows: "No valid rows are ready to import.",
      reviewRequired: "Confirm that you reviewed the import preview before importing.",
      importError: "Failed to import LP servers CSV",
      actionLabels: {
        create: "Create",
        update: "Update",
        invalid: "Invalid",
        unchanged: "Unchanged",
        skip: "Skip",
      },
      fieldLabels: {
        brand: "Brand",
        serverIp: "Server IP",
        username: "Username",
        password: "Password",
        note: "Note",
      },
      previewMessages: {
        invalid: "Row has validation errors",
        create: "New LP server will be imported",
        unchanged: "Existing LP server already matches current data",
        update: (changedLabels) => `Existing LP server will update: ${changedLabels}`,
        needsPrivilege: (changedLabels) =>
          `Change detected (${changedLabels}) but update requires Edit LP Servers Details privilege`,
        skipped: (changedLabels) => `Change detected (${changedLabels}) and will be skipped`,
      },
    },
  },
  indonesian: {
    common: {
      close: "Tutup",
      cancel: "Batal",
      save: "Simpan",
      saving: "Menyimpan...",
      delete: "Hapus",
      working: "Memproses...",
      edit: "Edit",
      create: "Buat",
      search: "Cari",
      loading: "Memuat...",
      copied: (label) => `${label} berhasil disalin.`,
      copyEmpty: (label) => `${label} kosong.`,
      copyFailed: (label) => `Gagal menyalin ${String(label || "").toLowerCase()}.`,
      fetchPasswordError: "Gagal mengambil password.",
      passwordNotReceived: "Kata sandi tidak diterima dari server.",
      passwordMask: "........",
      openResourceImage: "Buka gambar sumber",
      notAvailable: "-",
    },
    page: {
      title: "Server LP",
      description:
        "Kelola kredensial hosting landing page, IP server, serta data yang dikontrol akses untuk impor atau ekspor.",
      importCsv: "Impor CSV",
      exportCsv: "Ekspor CSV",
      exporting: "Mengekspor...",
      createServer: "Buat Server",
      matchingServers: "Server yang cocok",
      loadError: "Gagal memuat server LP",
      updateSuccess: "Server LP berhasil diperbarui.",
      createSuccess: "Server LP berhasil dibuat.",
      saveError: "Gagal menyimpan server LP",
      deleteSuccess: "Server LP berhasil dihapus.",
      deleteError: "Gagal menghapus server LP",
      exportError: "Gagal mengekspor CSV server LP",
      editPermissionError: "Anda tidak memiliki izin untuk mengedit.",
      deletePermissionError: "Anda tidak memiliki izin untuk menghapus.",
      deleteTitle: "Hapus Server LP",
      deleteConfirm: (url) => `Hapus ${url}? Tindakan ini tidak dapat dibatalkan.`,
      loadingTitle: "Memuat",
      loadingDescription: "Mengambil data server...",
    },
    form: {
      titleCreate: "Buat Server",
      titleEdit: "Edit Server",
      requiredError: "Brand, URL, Username, dan Password wajib diisi.",
      brand: "Brand",
      selectBrand: "Pilih Brand",
      brandFixedHelp: "Brand tetap untuk data server LP yang sudah ada.",
      brandHelp: "Pilih brand yang memiliki data server LP ini.",
      url: "URL",
      urlPlaceholder: "https://example.com",
      urlHelp: "Tempel URL landing page lengkap. `https://` akan ditambahkan otomatis jika belum ada.",
      serverIp: "IP Server",
      serverIpPlaceholder: "203.0.113.10",
      serverIpHelp: "Opsional. Kosongkan jika IP server belum tersedia.",
      username: "Username",
      usernamePlaceholder: "server-admin",
      usernameHelp: "Masukkan username yang digunakan untuk mengakses server, panel, atau akun hosting.",
      password: "Password",
      passwordPlaceholder: "Password saat ini",
      passwordLoading: "Memuat...",
      passwordHelp: "Simpan password saat ini yang digunakan untuk login server atau hosting ini.",
      showPassword: "Tampilkan password",
      hidePassword: "Sembunyikan password",
      note: "Catatan",
      notePlaceholder: "Catatan internal opsional",
      noteHelp: "Catatan internal opsional untuk pengingat, detail akses, atau konteks hosting.",
      save: "Simpan",
      cancel: "Batal",
    },
    table: {
      copyHint: "Klik nilai URL, IP Server, Username, atau Password untuk menyalinnya.",
      searchPlaceholder: "Brand, URL, IP Server, Username",
      headers: {
        brand: "Brand",
        url: "URL",
        serverIp: "IP Server",
        username: "Username",
        password: "Password",
        note: "Catatan",
        actions: "Aksi",
      },
      openUrlTitle: "Buka URL di tab baru",
      copyUrlTitle: "Klik untuk menyalin URL",
      copyServerIpTitle: "Klik untuk menyalin IP server",
      copyUsernameTitle: "Klik untuk menyalin username",
      copyPasswordTitle: "Klik untuk menyalin password",
      loadingPassword: "Memuat...",
      edit: "Edit",
      delete: "Hapus",
      empty: "Tidak ada server LP ditemukan.",
    },
    importPage: {
      title: "Impor Server LP",
      noPermission: "Anda tidak memiliki izin untuk mengimpor data server LP.",
      backToList: "Kembali ke Server LP",
    },
    importForm: {
      title: "Impor Server LP",
      uploadTitle: "Unggah CSV",
      uploadDescription:
        "Unggah file CSV atau tempel teks CSV untuk melihat pratinjau baris server LP baru, diperbarui, tidak berubah, dan tidak valid sebelum impor. Data yang sudah ada dicocokkan berdasarkan Brand.",
      hideCsvView: "Sembunyikan Tampilan CSV",
      showCsvView: "Tampilkan Tampilan CSV",
      downloadTemplate: "Unduh Template",
      chooseFile: "Pilih file CSV",
      fileHelp: "Gunakan format ekspor: Brand, URL, Server IP, Username, Password, Note.",
      csvContent: "Konten CSV",
      noCsvLoaded: "Belum ada konten CSV dimuat",
      loadedLines: (count) => `${count} baris tidak kosong dimuat`,
      csvReady: "Konten CSV siap untuk pratinjau.",
      csvHidden: "Editor CSV disembunyikan.",
      templatePreview: "Pratinjau template",
      templateLines: (count) => `Contoh template dengan ${count} baris tidak kosong`,
      templateHidden: "Pratinjau template disembunyikan.",
      importPreview: "Pratinjau Impor",
      checkingRows: "Memeriksa baris CSV...",
      uploadToPreview: "Unggah konten CSV untuk membuat pratinjau impor.",
      readyCount: (count) => `Siap: ${count}`,
      filteredCount: (count) => `Tersaring: ${count}`,
      importAction: "Impor Server LP",
      cards: {
        ready: "Siap Diterapkan",
        new: "Baru",
        update: "Perbarui",
        unchanged: "Tidak Berubah",
        invalid: "Tidak Valid",
      },
      searchPreview: "Cari pratinjau",
      searchPlaceholder: "Brand, URL, IP Server, Username, Catatan",
      all: "Semua",
      ready: "Siap",
      resetPreviewFilters: "Reset filter pratinjau",
      tableHeaders: {
        row: "Baris",
        incoming: "Server Masuk",
        current: "Data Saat Ini",
        difference: "Perbedaan",
        result: "Hasil",
      },
      rowLabel: (rowNumber) => `Baris ${rowNumber}`,
      incoming: "Masuk",
      current: "Saat Ini",
      noExistingRecord: "Tidak ada data saat ini",
      needsCorrection: "Perlu diperbaiki",
      rowWillBeApplied: "Baris ini akan diterapkan.",
      rowWillNotChange: "Baris ini tidak akan mengubah data yang ada.",
      noRowsMatch: "Tidak ada baris yang cocok dengan filter pratinjau saat ini.",
      confirmTitle: "Konfirmasi Impor",
      confirmDescription:
        "Tinjau ringkasan di bawah ini dan konfirmasi sebelum mengimpor baris server LP dari CSV ini.",
      reviewedConfirmation:
        "Saya sudah meninjau pratinjau impor dan ingin mengimpor perubahan server LP ini.",
      importing: "Mengimpor...",
      importResult: (createdCount, updatedCount, skippedCount) =>
        `Berhasil mengimpor ${createdCount || 0} server LP baru, memperbarui ${updatedCount || 0} server yang ada, dan melewati ${skippedCount || 0} baris.`,
      summary: (summary = {}) =>
        `${summary.actionableCount || 0} siap, ${summary.newCount || 0} baru, ${summary.updateCount || 0} diperbarui, ${summary.unchangedCount || 0} tidak berubah, ${summary.invalidCount || 0} tidak valid.`,
      previewError: "Gagal membuat pratinjau impor CSV server LP",
      readFileError: "Gagal membaca file CSV.",
      csvRequired: "Konten CSV wajib diisi.",
      waitForPreview: "Harap tunggu sampai pratinjau selesai.",
      noValidRows: "Tidak ada baris valid yang siap diimpor.",
      reviewRequired: "Konfirmasi bahwa Anda sudah meninjau pratinjau impor sebelum mengimpor.",
      importError: "Gagal mengimpor CSV server LP",
      actionLabels: {
        create: "Buat",
        update: "Perbarui",
        invalid: "Tidak Valid",
        unchanged: "Tidak Berubah",
        skip: "Lewati",
      },
      fieldLabels: {
        brand: "Brand",
        serverIp: "IP Server",
        username: "Username",
        password: "Password",
        note: "Catatan",
      },
      previewMessages: {
        invalid: "Baris memiliki error validasi",
        create: "Server LP baru akan diimpor",
        unchanged: "Server LP yang ada sudah sama dengan data saat ini",
        update: (changedLabels) => `Server LP yang ada akan diperbarui: ${changedLabels}`,
        needsPrivilege: (changedLabels) =>
          `Perubahan terdeteksi (${changedLabels}) tetapi pembaruan memerlukan hak akses Edit LP Servers Details`,
        skipped: (changedLabels) => `Perubahan terdeteksi (${changedLabels}) dan akan dilewati`,
      },
    },
  },
};

export function normalizeLpServersLanguage(value) {
  return value === "indonesian" ? "indonesian" : "english";
}

export function getLpServersUiCopy(language) {
  return LP_SERVERS_UI_COPY[normalizeLpServersLanguage(language)];
}

export function getLpServersLocale(language) {
  return normalizeLpServersLanguage(language) === "indonesian" ? "id-ID" : "en-US";
}
