export const privilegeCatalog = [
  {
    key: "ADMIN_ACCESS",
    name: "Admin",
    module: "admin",
    description: "Full administrative access across all modules, settings, and operational workflows.",
  },
  {
    key: "VIEW_SYSTEM_AUDIT_LOGS",
    name: "View Complete System Logs",
    module: "audit-logs",
    description: "Review full platform activity logs for monitoring, investigations, and compliance checks.",
  },
  {
    key: "VIEW_OWN_AUDIT_LOGS",
    name: "View Own Logs",
    module: "audit-logs",
    description: "Review audit records related to your own actions and account activity.",
  },
  {
    key: "VIEW_SITE_ANALYTICS",
    name: "View Website Analytics",
    module: "site-analytics",
    description:
      "Review page views, clicks, devices, and detected bots collected from tracked HTML and AMP pages.",
  },
  {
    key: "MANAGE_SITE_ANALYTICS",
    name: "Manage Website Analytics",
    module: "site-analytics",
    description:
      "Clear stats, delete tracked URLs, and block or unblock future analytics collection for selected pages.",
  },
  {
    key: "VIEW_WEBSITE_SNAPSHOTS",
    name: "View Website Snapshots",
    module: "website-snapshots",
    description:
      "Search historical website snapshots by URL, date range, and Wayback match scope.",
  },
  {
    key: "DOWNLOAD_WEBSITE_SNAPSHOTS",
    name: "Download Website Snapshot ZIPs",
    module: "website-snapshots",
    description:
      "Download best-effort ZIP archives containing archived HTML, documents, scripts, styles, and image assets.",
  },
  {
    key: "MANAGE_WEBSITE_SNAPSHOTS",
    name: "Manage Website Snapshot History",
    module: "website-snapshots",
    description:
      "Delete saved website snapshot search and download history records when cleanup is needed.",
  },
  {
    key: "VIEW_DATABASE_BACKUPS",
    name: "View Database Backups",
    module: "database-backups",
    description:
      "Review full database backup history, latest backup times, file status, and restore readiness.",
  },
  {
    key: "EXPORT_DATABASE_BACKUPS",
    name: "Export Database Backups",
    module: "database-backups",
    description:
      "Create and download full MongoDB backup archives from the server backup storage.",
  },
  {
    key: "MANAGE_DATABASE_BACKUPS",
    name: "Manage Database Backups",
    module: "database-backups",
    description:
      "Delete older backup archives while keeping the newest protected restore points intact.",
  },
  {
    key: "SEND_DATABASE_BACKUPS_TELEGRAM",
    name: "Send Database Backups To Telegram",
    module: "database-backups",
    description:
      "Send saved database backup archives from the backup library to the configured Telegram chats.",
  },
  {
    key: "RESTORE_DATABASE_BACKUPS",
    name: "Restore Database Backups",
    module: "database-backups",
    description:
      "Request Telegram verification codes, create safety backups, and restore database backups when approved.",
  },
  {
    key: "RESET_OTHER_USER_PASSWORDS",
    name: "Reset Other Users Passwords",
    module: "password-resets",
    description: "Approve and reset passwords for other users when they submit a reset request.",
  },
  {
    key: "CREATE_BRANDS",
    name: "Create Brands",
    module: "brands",
    description: "Add new brand records to the platform.",
  },
  {
    key: "EDIT_BRANDS",
    name: "Edit Brands",
    module: "brands",
    description: "Update brand information and maintain existing brand records.",
  },
  {
    key: "DELETE_BRANDS",
    name: "Delete Brands",
    module: "brands",
    description: "Remove brand records that are no longer needed.",
  },
  {
    key: "VIEW_MONEY_SITES",
    name: "View Money Site Checker",
    module: "money-sites",
    description: "View money-site records, their brand mapping, and live nawala status updates.",
  },
  {
    key: "CREATE_MONEY_SITES",
    name: "Create Money Sites",
    module: "money-sites",
    description: "Add money-site domains individually or in bulk CSV imports.",
  },
  {
    key: "EDIT_MONEY_SITES",
    name: "Edit Money Sites",
    module: "money-sites",
    description: "Update money-site brand assignments, domains, notes, and active status.",
  },
  {
    key: "DELETE_MONEY_SITES",
    name: "Delete Money Sites",
    module: "money-sites",
    description: "Remove money-site records that should no longer be checked.",
  },
  {
    key: "VIEW_SCREENSHOT_TAKER",
    name: "View Screenshot Taker",
    module: "screenshot-taker",
    description: "View assigned website screenshots and capture history.",
  },
  {
    key: "MANAGE_SCREENSHOT_TAKER",
    name: "Manage Screenshot Sites",
    module: "screenshot-taker",
    description: "Assign and remove websites that should be captured by the screenshot taker service.",
  },
  {
    key: "CAPTURE_SCREENSHOT_TAKER",
    name: "Capture Screenshots",
    module: "screenshot-taker",
    description: "Run immediate website screenshot captures for assigned sites.",
  },
  {
    key: "SCHEDULE_SCREENSHOT_TAKER",
    name: "Schedule Screenshot Captures",
    module: "screenshot-taker",
    description: "Manage automatic screenshot capture schedules.",
  },
  {
    key: "VIEW_SHORT_LINK_CHECKER",
    name: "View Short Link Checker",
    module: "short-link-checker",
    description: "View short links, their assigned money sites, status codes, and latest check results.",
  },
  {
    key: "MANAGE_SHORT_LINK_CHECKER",
    name: "Manage Short Links",
    module: "short-link-checker",
    description: "Add, edit, delete, and assign money sites to short links.",
  },
  {
    key: "CHECK_SHORT_LINKS",
    name: "Check Short Links",
    module: "short-link-checker",
    description: "Run Playwright checks for short links and capture their destination pages.",
  },
  {
    key: "MANAGE_SHORT_LINK_TELEGRAM",
    name: "Manage Short Link Telegram Alerts",
    module: "short-link-checker",
    description: "Configure Telegram error alerts for short link checks.",
  },
  {
    key: "SCHEDULE_SHORT_LINK_CHECKER",
    name: "Schedule Short Link Checks",
    module: "short-link-checker",
    description: "Configure automatic short link checks and scan frequency.",
  },
  {
    key: "VIEW_CUTTLY_LINK_CHECKER",
    name: "View Cutt.ly Link Checker",
    module: "cuttly-link-checker",
    description: "View Cutt.ly URL validation results, blocked-domain status, and latest check history.",
  },
  {
    key: "MANAGE_CUTTLY_LINK_CHECKER",
    name: "Manage Cutt.ly Links",
    module: "cuttly-link-checker",
    description: "Add, edit, remove, and activate URLs checked through the Cutt.ly API.",
  },
  {
    key: "CHECK_CUTTLY_LINKS",
    name: "Check Cutt.ly Links",
    module: "cuttly-link-checker",
    description: "Run immediate Cutt.ly API checks for selected URLs or all active URLs.",
  },
  {
    key: "SCHEDULE_CUTTLY_LINK_CHECKER",
    name: "Schedule Cutt.ly Checks",
    module: "cuttly-link-checker",
    description: "Configure automatic Cutt.ly API checks and scan frequency.",
  },
  {
    key: "MANAGE_CUTTLY_API_SETTINGS",
    name: "Manage Cutt.ly API Key",
    module: "cuttly-link-checker",
    description: "Save and rotate the Cutt.ly API key used by manual and scheduled checks.",
  },
  {
    key: "MANAGE_CUTTLY_LINK_TELEGRAM",
    name: "Manage Cutt.ly Telegram Alerts",
    module: "cuttly-link-checker",
    description: "Configure the dedicated Telegram bot used for scheduled Cutt.ly blocked-domain alerts.",
  },
  {
    key: "CREATE_DOMAINS",
    name: "Add Domains",
    module: "domains",
    description: "Add new domains for landing page development and related delivery workflows.",
  },
  {
    key: "EDIT_DOMAINS",
    name: "Edit Domains",
    module: "domains",
    description: "Update existing domain details used for landing page development.",
  },
  {
    key: "DELETE_DOMAINS",
    name: "Delete Domains",
    module: "domains",
    description: "Remove domains that should no longer be used in development workflows.",
  },
  {
    key: "VIEW_EXPIRED_DOMAINS",
    name: "View Expired Domains",
    module: "expired-domains",
    description: "View uploaded expired domain records.",
  },
  {
    key: "CREATE_EXPIRED_DOMAINS",
    name: "Create Expired Domains",
    module: "expired-domains",
    description: "Create expired domain records manually or via import.",
  },
  {
    key: "IMPORT_EXPIRED_DOMAINS",
    name: "Import Expired Domains",
    module: "expired-domains",
    description: "Import expired domains from CSV or bulk uploads.",
  },
  {
    key: "DELETE_EXPIRED_DOMAINS",
    name: "Delete Expired Domains",
    module: "expired-domains",
    description: "Delete expired domain records when required.",
  },
  {
    key: "ASSIGN_DEVELOPMENT",
    name: "Assign Development",
    module: "development",
    description: "Assign landing page development work to the appropriate team members.",
  },
  {
    key: "DO_DEVELOPMENT",
    name: "Do Development",
    module: "development",
    description: "Carry out landing page development tasks and implementation work.",
  },
  {
    key: "VIEW_DEVELOPMENT_PROGRESS",
    name: "Check Development Progress",
    module: "development",
    description: "Track progress and current status across active development work.",
  },
  {
    key: "ADD_TEMPLATES",
    name: "Add Templates",
    module: "development",
    description: "Add template links used in development workflows.",
  },
  {
    key: "ADD_CONTENT",
    name: "Add Content",
    module: "content",
    description: "Add content for development.",
  },
  {
    key: "EDIT_CONTENT",
    name: "Edit Content",
    module: "content",
    description: "Edit content for development.",
  },
  {
    key: "READ_ARTICLE_POOL",
    name: "Read Content Pool",
    module: "article-pool",
    description: "View content pool records and creator details.",
  },
  {
    key: "CREATE_ARTICLE_POOL",
    name: "Create Content Pool",
    module: "article-pool",
    description: "Create content pool records with brand, title, description, content body, and resource links.",
  },
  {
    key: "EDIT_ARTICLE_POOL",
    name: "Update Content Pool",
    module: "article-pool",
    description: "Update content pool records when this privilege is assigned.",
  },
  {
    key: "DELETE_ARTICLE_POOL",
    name: "Delete Content Pool",
    module: "article-pool",
    description: "Delete content pool records when this privilege is assigned.",
  },
  {
    key: "IMPORT_ARTICLE_POOL",
    name: "Import Content Pool",
    module: "article-pool",
    description: "Preview and import content pool records from CSV files.",
  },
  {
    key: "EXPORT_ARTICLE_POOL",
    name: "Export Content Pool",
    module: "article-pool",
    description: "Export content pool records to CSV files.",
  },
  {
    key: "READ_REPORTING_TASKS",
    name: "Read Reporting Tasks",
    module: "reporting-tasks",
    description: "View the reporting tasks list and all task details.",
  },
  {
    key: "ADD_REPORTING_TASKS",
    name: "Add Reporting Tasks",
    module: "reporting-tasks",
    description: "Create reporting tasks and assign them to staff members.",
  },
  {
    key: "RECEIVE_REPORTING_TASKS",
    name: "Receive Reporting Tasks",
    module: "reporting-tasks",
    description: "View and receive reporting tasks, accept them, and submit reporting evidence.",
  },
  {
    key: "DO_DDOS_REPORTING_TASKS",
    name: "Submit DDoS Evidence",
    module: "reporting-tasks",
    description: "View the DDoS evidence column and submit DDoS screenshots for accepted reporting tasks.",
  },
  {
    key: "TRACK_REPORTING_TASKS",
    name: "Track Reporting Tasks",
    module: "reporting-tasks",
    description: "Access the Track panel to view reporting URLs and IT team data for reporting tasks.",
  },
  {
    key: "ADD_REPORTING_URLS",
    name: "Create Reporting Tasks",
    module: "reporting",
    description: "Create new reporting tasks and place URLs into the reporting queue.",
  },
  {
    key: "EDIT_REPORTING_TASKS",
    name: "Edit Reporting Tasks",
    module: "reporting",
    description: "Edit reporting task details such as brand, issue type, URL, rank, DDOS flag, and notes.",
  },
  {
    key: "DELETE_REPORTING_TASKS",
    name: "Delete Reporting Tasks",
    module: "reporting",
    description: "Delete reporting tasks that should no longer remain in the reporting workflow.",
  },
  {
    key: "VIEW_REPORTING_PROGRESS",
    name: "View Reporting Queue",
    module: "reporting",
    description: "Open the reporting page and view reporting tasks and their status.",
  },
  {
    key: "DO_REPORTING",
    name: "Submit Reporting Evidence",
    module: "reporting",
    description: "Open a reporting task, upload Google Drive links or image evidence, and submit it for review.",
  },
  {
    key: "GENERATE_REPORTING_AI_EMAIL",
    name: "Generate Reporting AI Email Content",
    module: "reporting",
    description: "Generate reporting email drafts with AI and maintain the personal Gemini AI setup used for reporting.",
  },
  {
    key: "SEND_REPORTING_EMAIL",
    name: "Send Reporting Email",
    module: "reporting",
    description: "Compose, save drafts, send reporting emails, and manage personal reporting SMTP profiles.",
  },
  {
    key: "VIEW_REPORTING_ADMIN_REVIEW",
    name: "Review Reporting Evidence",
    module: "reporting",
    description: "Review submitted reporting evidence and mark tasks as checked or unchecked.",
  },
  {
    key: "EDIT_REPORTING_WORKFLOWS",
    name: "Edit Reporting Workflows",
    module: "reporting",
    description: "Edit the reporting SOP workflows, notes, steps, and quick links.",
  },
  {
    key: "MANAGE_REPORTING_SMTP_PROFILES",
    name: "Manage Reporting SMTP Profiles",
    module: "reporting",
    description: "Create, update, test, and remove shared reporting SMTP profiles for brands or custom mail identities.",
  },
  {
    key: "CREATE_USERS",
    name: "Create Users",
    module: "users",
    description: "Create new user accounts and assign them to the appropriate groups.",
  },
  {
    key: "EDIT_USERS",
    name: "Edit Users",
    module: "users",
    description: "Update user details, group assignments, and account information.",
  },
  {
    key: "DELETE_USERS",
    name: "Delete Users",
    module: "users",
    description: "Remove user accounts that should no longer access the system.",
  },
  {
    key: "CREATE_GROUPS",
    name: "Create Groups",
    module: "groups",
    description: "Create new groups and define the privileges assigned to them.",
  },
  {
    key: "EDIT_GROUPS",
    name: "Edit Groups",
    module: "groups",
    description: "Update group names, descriptions, and assigned privileges.",
  },
  {
    key: "DELETE_GROUPS",
    name: "Delete Groups",
    module: "groups",
    description: "Delete groups and manage safe reassignment of affected users.",
  },
  {
    key: "SHOW_RANK_CHECKER",
    name: "Show",
    module: "rank-checker",
    description: "It will show rank checker to them else it will hide.",
  },
  {
    key: "RANK_CHECKER_ADD_DOMAINS",
    name: "Add Domains",
    module: "rank-checker",
    description: "It will give the privilege to add domains to the Brands in Rank Checker",
  },
  {
    key: "RANK_CHECKER_MANUAL_CHECKER",
    name: "Manual Checker",
    module: "rank-checker",
    description: "It will show the Manual Checker menu option",
  },
  {
    key: "RANK_CHECKER_BULK_CHECKER",
    name: "Bulk Checker",
    module: "rank-checker",
    description: "it will show the Bulk checker menu option.",
  },
  {
    key: "RANK_CHECKER_ADMIN_PRIVS",
    name: "Rank Checker Admin Privs",
    module: "rank-checker",
    description: "it will give them all the access and also show Admin Config menu or else it wont show it to them",
  },
  {
    key: "RANK_CHECKER_LOGS",
    name: "Rank Checker Logs",
    module: "rank-checker",
    description: "the domain logs and auto check logos menu option will be enabled else hidden.",
  },
  {
    key: "VIEW_LP_SERVERS_DETAILS",
    name: "View LP Servers Details",
    module: "lp-servers",
    description: "View hosting configuration and related details.",
  },
  {
    key: "CREATE_LP_SERVERS_DETAILS",
    name: "Create LP Servers Details",
    module: "lp-servers",
    description: "Create new hosting configurations and related details.",
  },
  {
    key: "EDIT_LP_SERVERS_DETAILS",
    name: "Edit LP Servers Details",
    module: "lp-servers",
    description: "Edit existing hosting configurations and related details.",
  },
  {
    key: "DELETE_LP_SERVERS_DETAILS",
    name: "Delete LP Servers Details",
    module: "lp-servers",
    description: "Delete hosting configurations and related details that are no longer needed.",
  },
  {
    key: "IMPORT_LP_SERVERS_DETAILS",
    name: "Import LP Servers Details",
    module: "lp-servers",
    description: "Preview and import LP server records from CSV files.",
  },
  {
    key: "EXPORT_LP_SERVERS_DETAILS",
    name: "Export LP Servers Details",
    module: "lp-servers",
    description: "Export LP server records and credentials to CSV files.",
  },
];
