export const MONEY_SITE_LANGUAGE_OPTIONS = [
  { value: "english", label: "English" },
  { value: "indonesian", label: "Bahasa Indonesia" },
];

const CHANGE_FIELD_LABELS = {
  brand: {
    english: "Brand",
    indonesian: "Brand",
  },
  note: {
    english: "Note",
    indonesian: "Catatan",
  },
  statusText: {
    english: "Status",
    indonesian: "Status",
  },
};

const SERVER_MESSAGE_MAP = {
  "Brand is required or could not be matched": {
    english: "Brand is required or could not be matched",
    indonesian: "Brand wajib diisi atau tidak dapat dicocokkan",
  },
  "Domain is required": {
    english: "Domain is required",
    indonesian: "Domain wajib diisi",
  },
  "Domain must be a valid domain or URL": {
    english: "Domain must be a valid domain or URL",
    indonesian: "Domain harus berupa domain atau URL yang valid",
  },
  "Duplicate domain inside this upload": {
    english: "Duplicate domain inside this upload",
    indonesian: "Domain duplikat di dalam unggahan ini",
  },
  "CSV content is required": {
    english: "CSV content is required",
    indonesian: "Isi CSV wajib diisi",
  },
  "No valid rows are ready to import": {
    english: "No valid rows are ready to import",
    indonesian: "Tidak ada baris valid yang siap diimpor",
  },
  "Enter the 4-digit Telegram verification code": {
    english: "Enter the 4-digit Telegram verification code",
    indonesian: "Masukkan kode verifikasi Telegram 4 digit",
  },
  "Request a new Telegram verification code before importing": {
    english: "Request a new Telegram verification code before importing",
    indonesian: "Minta kode verifikasi Telegram baru sebelum impor",
  },
  "Telegram verification code expired. Request a new code": {
    english: "Telegram verification code expired. Request a new code",
    indonesian: "Kode verifikasi Telegram sudah kedaluwarsa. Minta kode baru",
  },
  "Telegram verification code is incorrect": {
    english: "Telegram verification code is incorrect",
    indonesian: "Kode verifikasi Telegram tidak benar",
  },
  "Add at least one active Telegram bot in Profile before importing money sites": {
    english: "Add at least one active Telegram bot in Profile before importing money sites",
    indonesian: "Tambahkan setidaknya satu bot Telegram aktif di Profil sebelum mengimpor situs",
  },
  "Failed to send verification code to active Telegram bots": {
    english: "Failed to send verification code to active Telegram bots",
    indonesian: "Gagal mengirim kode verifikasi ke bot Telegram aktif",
  },
  "Current password is required for verification": {
    english: "Current password is required for verification",
    indonesian: "Kata sandi saat ini wajib diisi untuk verifikasi",
  },
  "Password is incorrect": {
    english: "Password is incorrect",
    indonesian: "Kata sandi salah",
  },
  "Request a new Telegram verification code before continuing": {
    english: "Request a new Telegram verification code before continuing",
    indonesian: "Minta kode verifikasi Telegram baru sebelum melanjutkan",
  },
  "Add at least one active Telegram bot in Profile before deleting money sites": {
    english: "Add at least one active Telegram bot in Profile before deleting money sites",
    indonesian: "Tambahkan setidaknya satu bot Telegram aktif di Profil sebelum menghapus situs",
  },
  "Failed to send delete verification code to active Telegram bots": {
    english: "Failed to send delete verification code to active Telegram bots",
    indonesian: "Gagal mengirim kode verifikasi hapus ke bot Telegram aktif",
  },
  "No money sites available to delete": {
    english: "No money sites available to delete",
    indonesian: "Tidak ada situs yang tersedia untuk dihapus",
  },
  "Money site total changed. Review and request a new verification before deleting.": {
    english: "Money site total changed. Review and request a new verification before deleting.",
    indonesian: "Total situs berubah. Tinjau kembali dan minta verifikasi baru sebelum menghapus.",
  },
};

const MONEY_SITE_UI_COPY = {
  english: {
    profile: {
      sectionTitle: "Language Preference",
      sectionDescription:
        "Choose your interface language. For now, this applies to Money Site Checker sections.",
      fieldLabel: "Language",
      saveButton: "Save Language",
      savingButton: "Saving...",
      successMessage: "Language preference updated successfully.",
      errorMessage: "Failed to update language preference",
    },
    common: {
      brand: "Brand",
      domain: "Domain",
      note: "Note",
      statusText: "Status",
      nawala: "Nawala",
      updated: "Updated",
      action: "Action",
      edit: "Edit",
      delete: "Delete",
      cancel: "Cancel",
      reset: "Reset",
      loading: "Loading",
      previous: "Previous",
      next: "Next",
      close: "Close",
      statusLabels: {
        ada: "Blocked",
        "tidak ada": "Not Blocked",
        unknown: "Not Checked",
      },
    },
    page: {
      title: "Money Site Checker",
      liveLabel: "Live",
      liveStatus: {
        connected: "Connected",
        connecting: "Connecting",
        offline: "Offline",
        error: "Offline",
      },
      blockedLabel: "Blocked",
      addDomain: "Add Domain",
      importCsv: "Import CSV",
      exportCsv: "Export CSV",
      exportingCsv: "Exporting...",
      exportSuccess: "Money sites CSV exported successfully.",
      exportError: "Failed to export money sites CSV",
      updateSuccess: "Money site updated successfully.",
      createSuccess: "Money site created successfully.",
      saveError: "Failed to save money site",
      deleteSuccess: "Money site deleted successfully.",
      deleteError: "Failed to delete money site",
      editPermissionError: "You do not have permission to edit money sites.",
      deletePermissionError: "You do not have permission to delete money sites.",
      latestBlockedDetected: (count) =>
        `${count} new blocked money site${count === 1 ? "" : "s"} detected`,
      showBlocked: "Show Blocked",
      dismiss: "Dismiss",
      filtersTitle: "Filters",
      searchLabel: "Search",
      searchPlaceholder: "Search domain, note, or status",
      brandLabel: "Brand",
      allBrands: "All brands",
      nawalaStatusLabel: "Nawala Status",
      allStatuses: "All statuses",
      assignmentFilterLabel: "Screenshot Assignment",
      assignmentFilterAll: "All",
      assignmentFilterAssigned: "Assigned",
      assignmentFilterUnassigned: "Unassigned",
      rowsPerPage: "Rows Per Page",
      reset: "Reset",
      loadingTitle: "Loading",
      loadingDescription: "Fetching brands and money sites...",
      loadErrorFallback: "Unable to load money sites.",
      activityLogButton: "Activity Log",
      deleteModalTitle: "Delete Money Site",
      deleteModalMessage: (domain) => `Delete ${domain}? This action cannot be undone.`,
      bulkDeleteTitle: "Delete Selected Blocked Money Sites",
      continueButton: "Continue",
      bulkDeleteMessage: (count) =>
        `Delete ${count} blocked money site${count === 1 ? "" : "s"}? This will permanently remove only the currently selected blocked rows.`,
      finalConfirmationTitle: "Final Confirmation Required",
      finalConfirmationMessage: (count) =>
        `You are about to permanently delete ${count} blocked money site${count === 1 ? "" : "s"}. Type DELETE to confirm.`,
      typeDeleteLabel: "Type DELETE",
      deleteBlockedButton: "Delete Blocked Money Sites",
      deletingButton: "Deleting...",
      bulkDeleteTypeDeleteError: "Type DELETE to confirm the bulk removal.",
      bulkDeleteSelectionError: "Select at least one blocked money site before bulk delete.",
      bulkDeleteSuccess: (deletedCount, skippedCount) =>
        `Deleted ${deletedCount} blocked money site${deletedCount === 1 ? "" : "s"}${skippedCount ? `. Skipped ${skippedCount}.` : "."}`,
      bulkDeleteError: "Failed to delete blocked money sites",
      paginationSummary: (page, totalPages, count, total) =>
        `Page ${page} of ${totalPages} | Showing ${count} of ${total}`,
    },
    summary: {
      total: "Total Money Sites",
      blocked: "Blocked Now",
      clear: "Clear Sites",
      waiting: "Waiting For Check",
    },
    form: {
      addTitle: "Add Money Site",
      editTitle: "Edit Money Site",
      description: "Attach a money-site domain to a brand so the external checker can fetch and update it.",
      brandLabel: "Brand",
      selectBrand: "Select brand",
      domainLabel: "Domain / URL",
      noteLabel: "Note",
      notePlaceholder: 'Optional note like "ads ddy"',
      statusLabel: "Status",
      statusPlaceholder: 'Optional status like "ready"',
      saveButton: "Save Money Site",
      createButton: "Create Money Site",
      savingButton: "Saving...",
      cancelButton: "Cancel",
      brandRequired: "Brand is required.",
      domainRequired: "Domain is required.",
    },
    table: {
      title: "Money Sites",
      selectedBlocked: (count) => `Selected blocked: ${count}`,
      deleteSelectedBlocked: "Delete Selected Blocked",
      selectBlocked: "Select Blocked",
      clearBlockedSelection: "Clear Selection",
      selectingBlocked: "Selecting...",
      selectLabel: "Select",
      selectAllAria: "Select all blocked money sites in the current filtered results",
      selectBlockedAria: (domain) => `Select blocked money site ${domain}`,
      openDomainAria: (domain) => `Open ${domain} in a new tab`,
      doubleClickPreview: "Double-click to preview live screenshot",
      screenshotAssignTitle: (domain) => `Assign ${domain} to Screenshot Taker`,
      screenshotUnassignTitle: (domain) => `Unassign ${domain} from Screenshot Taker`,
      screenshotAssignButton: "Assign",
      screenshotUnassignButton: "Unassign",
      noResults: "No money sites found for the current filters.",
    },
    activity: {
      title: "Money Site Activity",
      description: "Admin-only history of create, update, delete, and import actions.",
      searchLabel: "Search Activity",
      searchPlaceholder: "Search user, domain, or summary",
      searchButton: "Search",
      loadingButton: "Loading...",
      loading: "Loading activity logs...",
      empty: "No money site activity logs found.",
      loadErrorFallback: "Failed to load money site activity logs",
      unknownUser: "Unknown",
      headers: {
        time: "Time",
        user: "User",
        action: "Action",
        target: "Target",
        summary: "Summary",
      },
      paginationSummary: (page, totalPages, total) => `Page ${page} of ${totalPages} | ${total} records`,
      actionLabels: {
        create: "Create",
        update: "Update",
        delete: "Delete",
        import: "Import",
        deleteAll: "Delete All",
        deleteBlocked: "Delete Blocked",
      },
      fallbackAction: "Action",
    },
    screenshot: {
      bulkAriaLabel: "Screenshot Taker bulk actions",
      assignedSummary: (count) => `Screenshot Taker: ${count} assigned`,
      bulkAssignTooltip: "Assign all matching filtered money sites to Screenshot Taker",
      bulkUnassignTooltip: "Unassign all matching filtered money sites from Screenshot Taker",
      bulkChecking: "Checking...",
      bulkAssignTitle: "Assign all to Screenshot Taker",
      bulkUnassignTitle: "Unassign all from Screenshot Taker",
      bulkAssignMessage: (count) =>
        `Assign ${count} matching money site${count === 1 ? "" : "s"} to Screenshot Taker? Existing captures will stay untouched.`,
      bulkUnassignMessage: (count) =>
        `Unassign ${count} matching money site${count === 1 ? "" : "s"} from Screenshot Taker? Existing capture images are not deleted by this action.`,
      bulkAssignButton: "Assign All",
      bulkUnassignButton: "Unassign All",
      permissionAssignError: "You do not have permission to assign screenshot sites.",
      permissionManageError: "You do not have permission to manage Screenshot Taker assignments.",
      permissionCaptureError: "You do not have permission to capture screenshots.",
      permissionUnassignError: "You do not have permission to unassign screenshot sites.",
      assignSuccess: (domain) => `${domain} assigned to Screenshot Taker.`,
      assignError: "Failed to assign website to Screenshot Taker",
      allAssigned: "All matching money sites are already assigned to Screenshot Taker.",
      noAssignedMatches: "No matching assigned screenshot sites found.",
      prepareBulkError: "Failed to prepare Screenshot Taker bulk action",
      bulkCompleteSuccess: (successCount, failedCount, mode) =>
        `${successCount} money site${successCount === 1 ? "" : "s"} ${mode === "assign" ? "assigned to" : "unassigned from"} Screenshot Taker.${failedCount ? ` ${failedCount} failed.` : ""}`,
      bulkCompleteError: "Failed to complete Screenshot Taker bulk action",
      networkError:
        "Screenshot service did not respond. Please check the screenshot service URL, proxy secret, and server status.",
      captureFailed: "Failed to capture screenshot",
      unassignConfirm: (domain) => `Unassign ${domain} from Screenshot Taker?`,
      unassignSuccess: (domain) => `${domain} unassigned from Screenshot Taker.`,
      unassignError: "Failed to unassign screenshot site",
      previewBadgeLoading: "Capturing live view",
      previewBadgeReady: "Live screenshot",
      previewTitleFallback: "Website preview",
      previewCapturedAt: (value) => `Captured ${value}`,
      previewWaiting: "The screenshot service is visiting this website now.",
      previewLoadingTitle: "Capturing screenshot...",
      previewLoadingDescription: "Please wait while the backend opens the site and takes a fresh image.",
      previewFailedTitle: "Preview failed",
      previewEmptyTitle: "No screenshot available",
      previewAlt: (domain) => `${domain || "Website"} screenshot`,
    },
    importPage: {
      title: "Import Money Sites",
      noPermission: "You do not have permission to import money sites.",
      backButton: "Back to Money Site Checker",
    },
    import: {
      uploadTitle: "CSV Upload",
      uploadDescription: "Use brand,domain,note,status. Domain decides new, update, or unchanged.",
      showCsvView: "Show CSV View",
      hideCsvView: "Hide CSV View",
      downloadTemplate: "Download Template",
      csvFileLabel: "CSV File",
      csvFileHelp: "Upload a CSV or paste rows manually below.",
      csvContentTitle: "CSV Content",
      csvContentLoaded: (count) => `${count} line${count === 1 ? "" : "s"} loaded`,
      csvContentEmpty: "Paste only when needed",
      csvContentReady: "CSV content is loaded and ready for preview.",
      csvContentHidden: "Hidden until you want to paste or edit CSV manually.",
      templatePreviewTitle: "Template Preview",
      templateSampleLines: (count) => `${count} sample line${count === 1 ? "" : "s"}`,
      templateHidden: "Open only if you need the sample format before importing.",
      previewTitle: "Import Preview",
      previewChecking: "Checking CSV rows against existing domains...",
      previewEmpty: "Paste or upload CSV content to preview import changes.",
      previewSummary: (summary = {}) =>
        [
          `${summary.totalRows || 0} rows`,
          `${summary.newCount || 0} new`,
          `${summary.updateCount || 0} update`,
          `${summary.unchangedCount || 0} unchanged`,
          `${summary.invalidCount || 0} invalid`,
        ].join(", "),
      ready: "Ready",
      filtered: "Filtered",
      finalVerification: "Final Verification",
      readyToApply: "Ready to Apply",
      newLabel: "New",
      updateLabel: "Update",
      unchangedLabel: "Unchanged",
      invalidLabel: "Invalid",
      allLabel: "All",
      filterPreview: "Filter Preview",
      filterPlaceholder: "Search domain, brand, note, status, or message",
      tableHeaders: {
        row: "Row",
        incoming: "Incoming Record",
        existing: "Existing Record",
        difference: "Detected Difference",
        action: "Action",
      },
      mobileIncoming: "Incoming",
      mobileCurrent: "Current",
      mobileDifference: "Difference",
      rowLabel: (rowNumber) => `Row #${rowNumber}`,
      noExistingRecord: "No existing record",
      activeRecord: "Active record",
      inactiveRecord: "Inactive record",
      needsCorrection: "Needs correction",
      willApply: "Will be applied on import",
      willNotChange: "Will not change stored data",
      noRowsMatch: "No preview rows match the current filters.",
      verificationTitle: "Final Verification",
      verificationDescription: "Confirm the preview and enter the 4-digit code.",
      verificationMethodLabel: "Verification Method",
      verificationUsePassword: "Use Password",
      verificationUseTelegram: "Use Telegram Code",
      reviewConfirmation: "I reviewed the import preview and want to apply these changes.",
      telegramCodeLabel: "Telegram Verification Code",
      passwordLabel: "Current Password",
      passwordPlaceholder: "Enter your current password",
      sending: "Sending...",
      sendNewCode: "Send New Code",
      sendCode: "Send Code",
      noCodeRequested: "No code requested yet",
      codeExpiry: (value) => `Code expires at ${value} (valid for 5 minutes)`,
      importing: "Importing...",
      verifyAndImport: "Verify and Import",
      deleteAllButton: "Delete All Money Sites",
      deleteAllTitle: "Delete All Money Sites",
      deleteAllDescription:
        "Permanently remove every stored money site. This action cannot be undone.",
      deleteAllCountLabel: "Current total money sites",
      deleteAllReviewConfirmation:
        "I understand this will permanently delete all money sites.",
      deletingAll: "Deleting...",
      deleteAllConfirm: "Verify and Delete All",
      deleteAllResult: (deletedCount) =>
        `Deleted ${deletedCount} money site${deletedCount === 1 ? "" : "s"} successfully.`,
      deleteAllError: "Failed to delete all money sites.",
      importResult: (createdCount, updatedCount, skippedCount) =>
        `Imported ${createdCount} new row${createdCount === 1 ? "" : "s"} and updated ${updatedCount} existing row${updatedCount === 1 ? "" : "s"}${skippedCount ? `. Skipped ${skippedCount}.` : "."}`,
      verificationResult: (sentCount, failedCount) =>
        `4-digit code sent to ${sentCount} Telegram bot${sentCount === 1 ? "" : "s"}${failedCount ? ` (${failedCount} failed)` : ""}. Any previous import code is now expired.`,
      csvRequiredBeforeVerification: "CSV content is required before requesting verification.",
      previewWaitMessage: "CSV preview is still checking the rows. Please wait.",
      noValidRows: "No valid rows are ready to import.",
      sendCodeError: "Failed to send Telegram verification code.",
      csvRequired: "CSV content is required.",
      confirmPreviewRequired: "Please confirm that you reviewed the preview before importing.",
      requestCodeRequired: "Request a Telegram verification code before importing.",
      enterCodeRequired: "Enter the 4-digit Telegram verification code.",
      importError: "Failed to import CSV.",
      previewError: "Failed to preview CSV import.",
      fileReadError: "Failed to read the selected CSV file.",
      actionLabels: {
        create: "Import",
        update: "Update",
        invalid: "Invalid",
        unchanged: "Unchanged",
        skip: "Skip",
      },
      changedWillUpdate: (labels) => `Existing domain will update: ${labels}`,
      changedNeedsUpdatePrivilege: (labels) =>
        `Change detected (${labels}) but update requires Edit Money Sites privilege`,
      changedWillSkip: (labels) => `Change detected (${labels}) and will be skipped`,
      newDomainMessage: "New domain will be imported",
      unchangedMessage: "Existing domain already matches current data",
      invalidMessage: "Row has validation errors",
    },
  },
  indonesian: {
    profile: {
      sectionTitle: "Preferensi Bahasa",
      sectionDescription:
        "Pilih bahasa antarmuka Anda. Untuk sekarang, ini diterapkan pada bagian pengecek Nawala.",
      fieldLabel: "Bahasa",
      saveButton: "Simpan Bahasa",
      savingButton: "Menyimpan...",
      successMessage: "Preferensi bahasa berhasil diperbarui.",
      errorMessage: "Gagal memperbarui preferensi bahasa",
    },
    common: {
      brand: "Brand",
      domain: "Domain",
      note: "Catatan",
      statusText: "Status",
      nawala: "Nawala",
      updated: "Diperbarui",
      action: "Aksi",
      edit: "Edit",
      delete: "Hapus",
      cancel: "Batal",
      reset: "Reset",
      loading: "Memuat",
      previous: "Sebelumnya",
      next: "Berikutnya",
      close: "Tutup",
      statusLabels: {
        ada: "Diblokir",
        "tidak ada": "Tidak Diblokir",
        unknown: "Belum Dicek",
      },
    },
    page: {
      title: "Pemeriksa Nawala",
      liveLabel: "Live",
      liveStatus: {
        connected: "Terhubung",
        connecting: "Menghubungkan",
        offline: "Offline",
        error: "Offline",
      },
      blockedLabel: "Diblokir",
      addDomain: "Tambah Domain",
      importCsv: "Impor CSV",
      exportCsv: "Ekspor CSV",
      exportingCsv: "Mengekspor...",
      exportSuccess: "CSV situs berhasil diekspor.",
      exportError: "Gagal mengekspor CSV situs",
      updateSuccess: "Situs berhasil diperbarui.",
      createSuccess: "Situs berhasil ditambahkan.",
      saveError: "Gagal menyimpan situs",
      deleteSuccess: "Situs berhasil dihapus.",
      deleteError: "Gagal menghapus situs",
      editPermissionError: "Anda tidak memiliki izin untuk mengedit situs.",
      deletePermissionError: "Anda tidak memiliki izin untuk menghapus situs.",
      latestBlockedDetected: (count) =>
        `${count} situs baru yang diblokir terdeteksi`,
      showBlocked: "Tampilkan Diblokir",
      dismiss: "Tutup",
      filtersTitle: "Filter",
      searchLabel: "Cari",
      searchPlaceholder: "Cari domain, catatan, atau status",
      brandLabel: "Brand",
      allBrands: "Semua brand",
      nawalaStatusLabel: "Status Nawala",
      allStatuses: "Semua status",
      assignmentFilterLabel: "Penugasan Screenshot",
      assignmentFilterAll: "Semua",
      assignmentFilterAssigned: "Ditugaskan",
      assignmentFilterUnassigned: "Belum Ditugaskan",
      rowsPerPage: "Baris per Halaman",
      reset: "Reset",
      loadingTitle: "Memuat",
      loadingDescription: "Memuat brand dan situs...",
      loadErrorFallback: "Gagal memuat situs.",
      activityLogButton: "Log Aktivitas",
      deleteModalTitle: "Hapus Situs",
      deleteModalMessage: (domain) => `Hapus ${domain}? Tindakan ini tidak dapat dibatalkan.`,
      bulkDeleteTitle: "Hapus Situs Diblokir yang Dipilih",
      continueButton: "Lanjutkan",
      bulkDeleteMessage: (count) =>
        `Hapus ${count} situs diblokir${count === 1 ? "" : ""}? Tindakan ini hanya akan menghapus baris diblokir yang saat ini dipilih secara permanen.`,
      finalConfirmationTitle: "Konfirmasi Akhir Diperlukan",
      finalConfirmationMessage: (count) =>
        `Anda akan menghapus permanen ${count} situs diblokir. Ketik DELETE untuk konfirmasi.`,
      typeDeleteLabel: "Ketik DELETE",
      deleteBlockedButton: "Hapus Situs Diblokir",
      deletingButton: "Menghapus...",
      bulkDeleteTypeDeleteError: "Ketik DELETE untuk mengonfirmasi penghapusan massal.",
      bulkDeleteSelectionError: "Pilih setidaknya satu situs diblokir sebelum penghapusan massal.",
      bulkDeleteSuccess: (deletedCount, skippedCount) =>
        `Berhasil menghapus ${deletedCount} situs diblokir${skippedCount ? `. Melewati ${skippedCount}.` : "."}`,
      bulkDeleteError: "Gagal menghapus situs diblokir",
      paginationSummary: (page, totalPages, count, total) =>
        `Halaman ${page} dari ${totalPages} | Menampilkan ${count} dari ${total}`,
    },
    summary: {
      total: "Total Situs",
      blocked: "Sedang Diblokir",
      clear: "Situs Bersih",
      waiting: "Menunggu Pengecekan",
    },
    form: {
      addTitle: "Tambah Situs",
      editTitle: "Edit Situs",
      description: "Hubungkan domain money-site ke brand agar pemeriksa eksternal bisa mengambil dan memperbarui datanya.",
      brandLabel: "Brand",
      selectBrand: "Pilih brand",
      domainLabel: "Domain / URL",
      noteLabel: "Catatan",
      notePlaceholder: 'Catatan opsional seperti "ads ddy"',
      statusLabel: "Status",
      statusPlaceholder: 'Status opsional seperti "siap"',
      saveButton: "Simpan Situs",
      createButton: "Buat Situs",
      savingButton: "Menyimpan...",
      cancelButton: "Batal",
      brandRequired: "Brand wajib dipilih.",
      domainRequired: "Domain wajib diisi.",
    },
    table: {
      title: "Situs Nawala",
      selectedBlocked: (count) => `Diblokir terpilih: ${count}`,
      deleteSelectedBlocked: "Hapus Diblokir Terpilih",
      selectBlocked: "Pilih Yang Diblokir",
      clearBlockedSelection: "Hapus Pilihan",
      selectingBlocked: "Memilih...",
      selectLabel: "Pilih",
      selectAllAria: "Pilih semua situs diblokir pada hasil filter saat ini",
      selectBlockedAria: (domain) => `Pilih situs diblokir ${domain}`,
      openDomainAria: (domain) => `Buka ${domain} di tab baru`,
      doubleClickPreview: "Klik dua kali untuk melihat screenshot langsung",
      screenshotAssignTitle: (domain) => `Tugaskan ${domain} ke Screenshot Taker`,
      screenshotUnassignTitle: (domain) => `Lepaskan ${domain} dari Screenshot Taker`,
      screenshotAssignButton: "Tugaskan",
      screenshotUnassignButton: "Lepaskan",
      noResults: "Tidak ada situs yang cocok dengan filter saat ini.",
    },
    activity: {
      title: "Aktivitas Situs",
      description: "Riwayat khusus admin untuk tindakan buat, ubah, hapus, dan impor.",
      searchLabel: "Cari Aktivitas",
      searchPlaceholder: "Cari pengguna, domain, atau ringkasan",
      searchButton: "Cari",
      loadingButton: "Memuat...",
      loading: "Memuat log aktivitas...",
      empty: "Tidak ada log aktivitas situs.",
      loadErrorFallback: "Gagal memuat log aktivitas situs",
      unknownUser: "Tidak diketahui",
      headers: {
        time: "Waktu",
        user: "Pengguna",
        action: "Aksi",
        target: "Target",
        summary: "Ringkasan",
      },
      paginationSummary: (page, totalPages, total) => `Halaman ${page} dari ${totalPages} | ${total} data`,
      actionLabels: {
        create: "Buat",
        update: "Perbarui",
        delete: "Hapus",
        import: "Impor",
        deleteAll: "Hapus Semua",
        deleteBlocked: "Hapus Diblokir",
      },
      fallbackAction: "Aksi",
    },
    screenshot: {
      bulkAriaLabel: "Aksi massal Screenshot Taker",
      assignedSummary: (count) => `Screenshot Taker: ${count} ditugaskan`,
      bulkAssignTooltip: "Tugaskan semua situs yang cocok dengan filter ke Screenshot Taker",
      bulkUnassignTooltip: "Lepaskan semua situs yang cocok dengan filter dari Screenshot Taker",
      bulkChecking: "Memeriksa...",
      bulkAssignTitle: "Tugaskan semua ke Screenshot Taker",
      bulkUnassignTitle: "Lepaskan semua dari Screenshot Taker",
      bulkAssignMessage: (count) =>
        `Tugaskan ${count} situs yang cocok ke Screenshot Taker? Hasil tangkapan yang sudah ada tidak akan diubah.`,
      bulkUnassignMessage: (count) =>
        `Lepaskan ${count} situs yang cocok dari Screenshot Taker? Gambar tangkapan yang sudah ada tidak akan dihapus oleh tindakan ini.`,
      bulkAssignButton: "Tugaskan Semua",
      bulkUnassignButton: "Lepaskan Semua",
      permissionAssignError: "Anda tidak memiliki izin untuk menugaskan situs screenshot.",
      permissionManageError: "Anda tidak memiliki izin untuk mengelola penugasan Screenshot Taker.",
      permissionCaptureError: "Anda tidak memiliki izin untuk mengambil screenshot.",
      permissionUnassignError: "Anda tidak memiliki izin untuk melepaskan situs screenshot.",
      assignSuccess: (domain) => `${domain} berhasil ditugaskan ke Screenshot Taker.`,
      assignError: "Gagal menugaskan website ke Screenshot Taker",
      allAssigned: "Semua situs yang cocok sudah ditugaskan ke Screenshot Taker.",
      noAssignedMatches: "Tidak ada situs screenshot yang ditugaskan dan cocok ditemukan.",
      prepareBulkError: "Gagal menyiapkan aksi massal Screenshot Taker",
      bulkCompleteSuccess: (successCount, failedCount, mode) =>
        `Berhasil ${mode === "assign" ? "menugaskan" : "melepaskan"} ${successCount} situs.${failedCount ? ` ${failedCount} gagal.` : ""}`,
      bulkCompleteError: "Gagal menyelesaikan aksi massal Screenshot Taker",
      networkError:
        "Layanan screenshot tidak merespons. Periksa URL layanan screenshot, proxy secret, dan status server.",
      captureFailed: "Gagal mengambil screenshot",
      unassignConfirm: (domain) => `Lepaskan ${domain} dari Screenshot Taker?`,
      unassignSuccess: (domain) => `${domain} berhasil dilepaskan dari Screenshot Taker.`,
      unassignError: "Gagal melepaskan situs screenshot",
      previewBadgeLoading: "Mengambil tampilan langsung",
      previewBadgeReady: "Screenshot langsung",
      previewTitleFallback: "Pratinjau website",
      previewCapturedAt: (value) => `Diambil ${value}`,
      previewWaiting: "Layanan screenshot sedang mengunjungi website ini.",
      previewLoadingTitle: "Mengambil screenshot...",
      previewLoadingDescription: "Mohon tunggu saat backend membuka situs dan mengambil gambar terbaru.",
      previewFailedTitle: "Pratinjau gagal",
      previewEmptyTitle: "Screenshot tidak tersedia",
      previewAlt: (domain) => `Screenshot ${domain || "website"}`,
    },
    importPage: {
      title: "Impor Situs Nawala",
      noPermission: "Anda tidak memiliki izin untuk mengimpor situs.",
      backButton: "Kembali ke Pemeriksa Nawala",
    },
    import: {
      uploadTitle: "Unggah CSV",
      uploadDescription: "Gunakan brand,domain,note,status. Domain menentukan apakah data baru, diperbarui, atau tidak berubah.",
      showCsvView: "Tampilkan Tampilan CSV",
      hideCsvView: "Sembunyikan Tampilan CSV",
      downloadTemplate: "Unduh Template",
      csvFileLabel: "File CSV",
      csvFileHelp: "Unggah CSV atau tempel baris secara manual di bawah.",
      csvContentTitle: "Isi CSV",
      csvContentLoaded: (count) => `${count} baris dimuat`,
      csvContentEmpty: "Tempel hanya bila diperlukan",
      csvContentReady: "Isi CSV sudah dimuat dan siap dipratinjau.",
      csvContentHidden: "Disembunyikan sampai Anda ingin menempel atau mengedit CSV secara manual.",
      templatePreviewTitle: "Pratinjau Template",
      templateSampleLines: (count) => `${count} baris contoh`,
      templateHidden: "Buka hanya jika Anda perlu melihat format contoh sebelum impor.",
      previewTitle: "Pratinjau Impor",
      previewChecking: "Sedang memeriksa baris CSV terhadap domain yang sudah ada...",
      previewEmpty: "Tempel atau unggah CSV untuk melihat pratinjau perubahan impor.",
      previewSummary: (summary = {}) =>
        [
          `${summary.totalRows || 0} baris`,
          `${summary.newCount || 0} baru`,
          `${summary.updateCount || 0} diperbarui`,
          `${summary.unchangedCount || 0} tidak berubah`,
          `${summary.invalidCount || 0} tidak valid`,
        ].join(", "),
      ready: "Siap",
      filtered: "Tersaring",
      finalVerification: "Verifikasi Akhir",
      readyToApply: "Siap Diterapkan",
      newLabel: "Baru",
      updateLabel: "Perbarui",
      unchangedLabel: "Tidak Berubah",
      invalidLabel: "Tidak Valid",
      allLabel: "Semua",
      filterPreview: "Filter Pratinjau",
      filterPlaceholder: "Cari domain, brand, catatan, status, atau pesan",
      tableHeaders: {
        row: "Baris",
        incoming: "Data Masuk",
        existing: "Data Tersimpan",
        difference: "Perbedaan Terdeteksi",
        action: "Aksi",
      },
      mobileIncoming: "Masuk",
      mobileCurrent: "Saat Ini",
      mobileDifference: "Perbedaan",
      rowLabel: (rowNumber) => `Baris #${rowNumber}`,
      noExistingRecord: "Belum ada data tersimpan",
      activeRecord: "Data aktif",
      inactiveRecord: "Data nonaktif",
      needsCorrection: "Perlu diperbaiki",
      willApply: "Akan diterapkan saat impor",
      willNotChange: "Tidak akan mengubah data tersimpan",
      noRowsMatch: "Tidak ada baris pratinjau yang cocok dengan filter saat ini.",
      verificationTitle: "Verifikasi Akhir",
      verificationDescription: "Konfirmasi pratinjau lalu masukkan kode 4 digit.",
      verificationMethodLabel: "Metode Verifikasi",
      verificationUsePassword: "Gunakan Kata Sandi",
      verificationUseTelegram: "Gunakan Kode Telegram",
      reviewConfirmation: "Saya sudah meninjau pratinjau impor dan ingin menerapkan perubahan ini.",
      telegramCodeLabel: "Kode Verifikasi Telegram",
      passwordLabel: "Kata Sandi Saat Ini",
      passwordPlaceholder: "Masukkan kata sandi Anda saat ini",
      sending: "Mengirim...",
      sendNewCode: "Kirim Kode Baru",
      sendCode: "Kirim Kode",
      noCodeRequested: "Belum ada kode diminta",
      codeExpiry: (value) => `Kode berlaku sampai ${value} (valid 5 menit)`,
      importing: "Mengimpor...",
      verifyAndImport: "Verifikasi dan Impor",
      deleteAllButton: "Hapus Semua Situs",
      deleteAllTitle: "Hapus Semua Situs",
      deleteAllDescription:
        "Hapus permanen semua situs yang tersimpan. Tindakan ini tidak dapat dibatalkan.",
      deleteAllCountLabel: "Total situs saat ini",
      deleteAllReviewConfirmation:
        "Saya paham tindakan ini akan menghapus permanen semua situs.",
      deletingAll: "Menghapus...",
      deleteAllConfirm: "Verifikasi dan Hapus Semua",
      deleteAllResult: (deletedCount) =>
        `Berhasil menghapus ${deletedCount} situs.`,
      deleteAllError: "Gagal menghapus semua situs.",
      importResult: (createdCount, updatedCount, skippedCount) =>
        `Berhasil mengimpor ${createdCount} baris baru dan memperbarui ${updatedCount} baris yang sudah ada${skippedCount ? `. Melewati ${skippedCount}.` : "."}`,
      verificationResult: (sentCount, failedCount) =>
        `Kode 4 digit dikirim ke ${sentCount} bot Telegram${failedCount ? ` (${failedCount} gagal)` : ""}. Kode impor sebelumnya sekarang kedaluwarsa.`,
      csvRequiredBeforeVerification: "Isi CSV wajib ada sebelum meminta verifikasi.",
      previewWaitMessage: "Pratinjau CSV masih memeriksa baris. Mohon tunggu.",
      noValidRows: "Tidak ada baris valid yang siap diimpor.",
      sendCodeError: "Gagal mengirim kode verifikasi Telegram.",
      csvRequired: "Isi CSV wajib diisi.",
      confirmPreviewRequired: "Harap konfirmasi bahwa Anda sudah meninjau pratinjau sebelum impor.",
      requestCodeRequired: "Minta kode verifikasi Telegram sebelum impor.",
      enterCodeRequired: "Masukkan kode verifikasi Telegram 4 digit.",
      importError: "Gagal mengimpor CSV.",
      previewError: "Gagal mempratinjau impor CSV.",
      fileReadError: "Gagal membaca file CSV yang dipilih.",
      actionLabels: {
        create: "Impor",
        update: "Perbarui",
        invalid: "Tidak Valid",
        unchanged: "Tidak Berubah",
        skip: "Lewati",
      },
      changedWillUpdate: (labels) => `Domain yang sudah ada akan diperbarui: ${labels}`,
      changedNeedsUpdatePrivilege: (labels) =>
        `Perubahan terdeteksi (${labels}) tetapi pembaruan membutuhkan izin Edit Money Sites`,
      changedWillSkip: (labels) => `Perubahan terdeteksi (${labels}) dan akan dilewati`,
      newDomainMessage: "Domain baru akan diimpor",
      unchangedMessage: "Domain yang ada sudah sama dengan data saat ini",
      invalidMessage: "Baris memiliki kesalahan validasi",
    },
  },
};

export function normalizeMoneySiteLanguage(value) {
  return value === "indonesian" ? "indonesian" : "english";
}

export function getMoneySiteUiCopy(language) {
  return MONEY_SITE_UI_COPY[normalizeMoneySiteLanguage(language)];
}

export function getMoneySiteChangeFieldLabel(language, field) {
  const normalizedLanguage = normalizeMoneySiteLanguage(language);
  return CHANGE_FIELD_LABELS[field]?.[normalizedLanguage] || field;
}

export function translateMoneySiteServerMessage(language, message) {
  return SERVER_MESSAGE_MAP[message]?.[normalizeMoneySiteLanguage(language)] || message;
}
