name: Deploy - Prod

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    uses: ./.github/workflows/reusable-build-deploy-env.yml
    with:
      environment: prod
      base_sha: ${{ github.event.before }}
      head_sha: ${{ github.sha }}
    secrets: inherit
