name: Deploy - QA

on:
  push:
    branches:
      - qa

jobs:
  build-deploy:
    uses: ./.github/workflows/reusable-build-deploy-env.yml
    with:
      environment: qa
      base_sha: ${{ github.event.before }}
      head_sha: ${{ github.sha }}
    secrets: inherit
